[workspace]
resolver = "2"
members = ["crates/ooxmlsdk", "crates/ooxmlsdk-build", "examples/*"]

[workspace.package]
version = "0.1.13"
edition = "2021"
rust-version = "1.73"
authors = ["KaiserY"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/KaiserY/ooxmlsdk"
description = "Open XML SDK for Rust"
keywords = ["xml", "office", "docx", "pptx", "xlsx"]
categories = ["parser-implementations"]
readme = "README.md"

[workspace.dependencies]
ooxmlsdk = { version = "0.1.13", path = "crates/ooxmlsdk" }
ooxmlsdk-build = { version = "0.1.13", path = "crates/ooxmlsdk-build" }
quick-xml = "0.36.2"
anyhow = "1.0.89"
serde = { version = "1.0.210", features = ["derive"] }
serde_derive = "1.0.210"
serde_json = "1.0.128"
quote = "1.0.37"
syn = "2.0.77"
prettyplease = "0.2.22"
proc-macro2 = "1.0.86"
heck = "0.5.0"
zip = "2.2.0"
thiserror = "1.0.64"
path-clean = "1.0.1"
criterion = "0.5.1"
