[workspace]
resolver = "2"
members = ["crates/ooxmlsdk", "crates/ooxmlsdk-build", "examples/*"]

[workspace.package]
version = "0.2.3"
edition = "2021"
rust-version = "1.73"
authors = ["KaiserY"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/KaiserY/ooxmlsdk"
documentation = "https://docs.rs/ooxmlsdk"
description = "Open XML SDK for Rust"
keywords = ["xml", "office", "docx", "pptx", "xlsx"]
categories = ["parser-implementations"]
readme = "README.md"

[workspace.dependencies]
ooxmlsdk = { version = "0.2.3", path = "crates/ooxmlsdk", default-features = false }
ooxmlsdk-build = { version = "0.2.3", path = "crates/ooxmlsdk-build" }
quick-xml = "0.37.5"
serde = { version = "1.0.219", features = ["derive"] }
serde_derive = "1.0.219"
serde_json = "1.0.140"
quote = "1.0.40"
syn = "2.0.104"
prettyplease = "0.2.35"
proc-macro2 = "1.0.95"
heck = "0.5.0"
zip = { version = "4.2.0", default-features = false, features = ["deflate"] }
thiserror = "2.0.12"
criterion = "0.5.1"
pprof = { version = "0.14", features = ["criterion", "flamegraph"] }
