[workspace]
resolver = "2"
members = ["crates/ooxmlsdk", "crates/ooxmlsdk-build", "examples/*"]

[workspace.package]
version = "0.1.18"
edition = "2021"
rust-version = "1.73"
authors = ["KaiserY"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/KaiserY/ooxmlsdk"
documentation = "https://docs.rs/ooxmlsdk"
description = "Open XML SDK for Rust"
keywords = ["xml", "office", "docx", "pptx", "xlsx"]
categories = ["parser-implementations"]
readme = "README.md"

[workspace.dependencies]
ooxmlsdk = { version = "0.1.18", path = "crates/ooxmlsdk", default-features = false }
ooxmlsdk-build = { version = "0.1.18", path = "crates/ooxmlsdk-build" }
quick-xml = "0.37.0"
anyhow = "1.0.92"
serde = { version = "1.0.214", features = ["derive"] }
serde_derive = "1.0.214"
serde_json = "1.0.132"
quote = "1.0.37"
syn = "2.0.87"
prettyplease = "0.2.25"
proc-macro2 = "1.0.89"
heck = "0.5.0"
zip = "2.2.0"
thiserror = "1.0.68"
path-clean = "1.0.1"
criterion = "0.5.1"
