use std::borrow::Cow;

mod args;
mod dispatch;
mod reader;

pub(crate) use args::{EvalContext, FunctionArgs};
pub(crate) use dispatch::evaluate_function;
#[cfg(test)]
pub(crate) use dispatch::format_complex_result;
pub(crate) use reader::FunctionArgReader;

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(crate) enum FormulaFunctionId {
  OrgDotOpenofficeDotErrortype,
  ComDotMicrosoftDotCeiling,
  ComDotMicrosoftDotFloor,
  Let,
  If,
  Iferror,
  Ifna,
  Ifs,
  Switch,
  Sum,
  Product,
  Average,
  Count,
  Counta,
  Iserror,
  Isna,
  Iserr,
  Isblank,
  Istext,
  Isnontext,
  Islogical,
  Isnumber,
  Isref,
  Isformula,
  ErrorDotType,
  Errortype,
  Type,
  Areas,
  Min,
  Mina,
  Max,
  Maxa,
  And,
  Or,
  Xor,
  Not,
  True,
  False,
  Na,
  Style,
  Current,
  N,
  Countblank,
  Abs,
  Sign,
  Int,
  Trunc,
  Mod,
  Even,
  Odd,
  Rawsubtract,
  Iseven,
  Isodd,
  Sqrt,
  Power,
  Pi,
  Sqrtpi,
  Radians,
  Degrees,
  Sin,
  Csc,
  Cos,
  Sec,
  Tan,
  Cot,
  Sinh,
  Csch,
  Cosh,
  Sech,
  Tanh,
  Coth,
  Asin,
  Asinh,
  Acos,
  Acosh,
  Acot,
  Atan,
  Atanh,
  Acoth,
  Atan2,
  Exp,
  Ln,
  Log10,
  Log,
  Sumsq,
  Sumproduct,
  Round,
  Roundsig,
  Roundup,
  Rounddown,
  Date,
  Datevalue,
  Time,
  Year,
  Month,
  Day,
  Weekday,
  Hour,
  Minute,
  Second,
  Days,
  Days360,
  Today,
  Eomonth,
  Edate,
  Isleapyear,
  Trim,
  Upper,
  Lower,
  Rot13,
  Proper,
  Len,
  Lenb,
  T,
  Value,
  Numbervalue,
  Dollar,
  Fixed,
  Base,
  Decimal,
  Convert,
  Bin2dec,
  Oct2dec,
  Hex2dec,
  Bin2oct,
  Bin2hex,
  Oct2bin,
  Oct2hex,
  Hex2bin,
  Hex2oct,
  Dec2bin,
  Dec2oct,
  Dec2hex,
  Bitand,
  Bitor,
  Bitxor,
  Bitlshift,
  Bitrshift,
  Code,
  Unicode,
  Char,
  Unichar,
  Clean,
  Choose,
  Concat,
  Concatenate,
  Exact,
  Find,
  Findb,
  Search,
  Searchb,
  Rept,
  Substitute,
  Replace,
  Textbefore,
  Textafter,
  Textsplit,
  Textjoin,
  Replaceb,
  Asc,
  Jis,
  Median,
  Large,
  Small,
  Trimmean,
  Devsq,
  Avedev,
  Averagea,
  StdevDotP,
  StdevDotS,
  Stdev,
  Stdeva,
  Stdevpa,
  VarDotP,
  VarDotS,
  Vara,
  Varpa,
  Skew,
  SkewDotP,
  Geomean,
  Harmean,
  Gauss,
  Text,
  Timevalue,
  Basisodatetime,
  Datedif,
  Yearfrac,
  Weeknum,
  Isoweeknum,
  Weeks,
  Weeksinyear,
  Years,
  Months,
  Daysinmonth,
  Daysinyear,
  Indirect,
  Index,
  Offset,
  Lookup,
  Match,
  Xmatch,
  Vlookup,
  Hlookup,
  Xlookup,
  Sheets,
  Sheet,
  Formula,
  Cell,
  Address,
  Row,
  Column,
  Rows,
  Columns,
  Mid,
  Midb,
  Left,
  Leftb,
  Right,
  Rightb,
  Roman,
  Arabic,
  Hyperlink,
  Tocol,
  Torow,
  Chooserows,
  Choosecols,
  Expand,
  Hstack,
  Vstack,
  Wrapcols,
  Wraprows,
  Filter,
  Unique,
  Sequence,
  Transpose,
  Drop,
  Take,
  Sort,
  Sortby,
  Mmult,
  Mdeterm,
  Minverse,
  Munit,
  Gcd,
  Lcm,
  Fact,
  Factdouble,
  Multinomial,
  Combin,
  Combina,
  Permut,
  Permutationa,
  Mround,
  Quotient,
  Pmt,
  Fv,
  Fvschedule,
  Npv,
  Effect,
  Rate,
  Ispmt,
  Ipmt,
  Ppmt,
  Cumipmt,
  Cumprinc,
  Ddb,
  Vdb,
  Sumifs,
  Countifs,
  Maxifs,
  Minifs,
  Sumif,
  Countif,
  Averageif,
  Averageifs,
  Dsum,
  Dcount,
  Dcounta,
  Daverage,
  Dget,
  Dmax,
  Dmin,
  Dproduct,
  Dvar,
  Dvarp,
  Dstdev,
  Dstdevp,
  Ceiling,
  CeilingDotMath,
  CeilingDotPrecise,
  Floor,
  FloorDotMath,
  FloorDotPrecise,
  B,
  BetaDotDist,
  Betadist,
  BetaDotInv,
  BinomDotDist,
  BinomDotDistDotRange,
  BinomDotInv,
  ChisqDotDist,
  ChisqDotDistDotRt,
  Chisqdist,
  ChisqDotInv,
  Chisqinv,
  ChisqDotInvDotRt,
  ChisqDotTest,
  ConfidenceDotNorm,
  ConfidenceDotT,
  CovarianceDotP,
  CovarianceDotS,
  Covar,
  Correl,
  Pearson,
  Phi,
  ErfDotPrecise,
  Erf,
  ErfcDotPrecise,
  ExponDotDist,
  FDotDist,
  FDotDistDotRt,
  FDotInv,
  FDotInvDotRt,
  FDotTest,
  GammaDotDist,
  GammaDotInv,
  Gamma,
  GammalnDotPrecise,
  HypgeomDotDist,
  LognormDotDist,
  LognormDotInv,
  ModeDotMult,
  ModeDotSngl,
  Mode,
  NegbinomDotDist,
  Negbinomdist,
  NormDotDist,
  NormDotInv,
  NormDotSDotDist,
  NormDotSDotInv,
  PercentileDotExc,
  PercentileDotInc,
  Percentrank,
  PercentrankDotExc,
  PoissonDotDist,
  Poisson,
  QuartileDotExc,
  QuartileDotInc,
  RankDotAvg,
  RankDotEq,
  Kurt,
  TDotDist,
  TDotDistDot2t,
  TDotDistDotRt,
  Tdist,
  TDotInv,
  TDotInvDot2t,
  TDotTest,
  Fisher,
  Fisherinv,
  Besseli,
  Besselj,
  Besselk,
  Bessely,
  Fourier,
  Imreal,
  Imaginary,
  Imabs,
  Imargument,
  Imconjugate,
  Imexp,
  Imln,
  Imlog10,
  Imlog2,
  Imsin,
  Imsinh,
  Imcosh,
  Imtan,
  Imcot,
  Imcsc,
  Imsqrt,
  Imcos,
  Imsec,
  Imsech,
  Imcsch,
  Imsub,
  Imdiv,
  Impower,
  Imsum,
  Improduct,
  Complex,
  Delta,
  Gestep,
  Slope,
  Intercept,
  Forecast,
  ForecastDotEts,
  ForecastDotEtsDotMult,
  ForecastDotEtsDotStat,
  ForecastDotEtsDotStatDotMult,
  ForecastDotEtsDotSeasonality,
  Rsq,
  Steyx,
  Linest,
  Logest,
  Trend,
  Growth,
  WeibullDotDist,
  NetworkdaysDotIntl,
  Networkdays,
  WorkdayDotIntl,
  Workday,
  ZDotTest,
  Standardize,
  Subtotal,
  Aggregate,
  Db,
  Price,
  Yield,
  Pricedisc,
  Pricemat,
  Yielddisc,
  Accrint,
  Accrintm,
  Oddlprice,
  Oddlyield,
  Amorlinc,
  Amordegrc,
  Disc,
  Received,
  Intrate,
  Mduration,
  Coupdays,
  Coupdaybs,
  Coupdaysnc,
  Coupncd,
  Coupnum,
  Couppcd,
  Tbilleq,
  Tbillprice,
  Tbillyield,
  Pv,
  Nper,
  Rri,
  Pduration,
  Seriessum,
  Eastersunday,
  Xirr,
  Xnpv,
  Irr,
  Mirr,
  Euroconvert,
  Bahttext,
  Nominal,
  Sln,
  Syd,
  Prob,
  Frequency,
  Sumx2my2,
  Sumx2py2,
  Sumxmy2,
  Dollarde,
  Dollarfr,
  Info,
  Regex,
  Encodeurl,
  OrgDotOpenofficeDotRot13,
  Getpivotdata,
  Color,
  Dhfg,
  Testfuncbool,
  Testfunccurr,
  Testfuncdate,
  Randbetween,
  Randarray,
  Testfuncint,
  Testfuncsingle,
}

impl FormulaFunctionId {
  pub(crate) fn is_volatile(self) -> bool {
    matches!(
      self,
      Self::Indirect | Self::Offset | Self::Randarray | Self::Randbetween | Self::Today
    )
  }
}

pub(crate) fn normalize_function_name(name: &str) -> Cow<'_, str> {
  let name = strip_excel_function_prefix(name.trim_start_matches('@'));
  if name.as_bytes().iter().any(u8::is_ascii_lowercase) {
    Cow::Owned(name.to_ascii_uppercase())
  } else {
    Cow::Borrowed(name)
  }
}

pub(crate) fn resolve_function_name(name: &str) -> Option<FormulaFunctionId> {
  let normalized = normalize_function_name(name);
  match normalized.as_ref() {
    "ORG.OPENOFFICE.ERRORTYPE" => Some(FormulaFunctionId::OrgDotOpenofficeDotErrortype),
    "COM.MICROSOFT.CEILING" => Some(FormulaFunctionId::ComDotMicrosoftDotCeiling),
    "COM.MICROSOFT.FLOOR" => Some(FormulaFunctionId::ComDotMicrosoftDotFloor),
    _ => resolve_canonical_function_name(strip_known_namespace_prefix(normalized.as_ref())),
  }
}

fn strip_excel_function_prefix(name: &str) -> &str {
  name
    .strip_prefix("_xlfn.")
    .or_else(|| name.strip_prefix("_xlws."))
    .unwrap_or(name)
}

fn strip_known_namespace_prefix(name: &str) -> &str {
  for prefix in ["COM.MICROSOFT.", "ORG.LIBREOFFICE.", "ORG.OPENOFFICE."] {
    if let Some(stripped) = name.strip_prefix(prefix) {
      return stripped;
    }
  }
  name
}

fn resolve_canonical_function_name(name: &str) -> Option<FormulaFunctionId> {
  match name {
    "LET" => Some(FormulaFunctionId::Let),
    "IF" => Some(FormulaFunctionId::If),
    "IFERROR" => Some(FormulaFunctionId::Iferror),
    "IFNA" => Some(FormulaFunctionId::Ifna),
    "IFS" => Some(FormulaFunctionId::Ifs),
    "SWITCH" => Some(FormulaFunctionId::Switch),
    "SUM" => Some(FormulaFunctionId::Sum),
    "PRODUCT" => Some(FormulaFunctionId::Product),
    "AVERAGE" => Some(FormulaFunctionId::Average),
    "COUNT" => Some(FormulaFunctionId::Count),
    "COUNTA" => Some(FormulaFunctionId::Counta),
    "ISERROR" => Some(FormulaFunctionId::Iserror),
    "ISNA" => Some(FormulaFunctionId::Isna),
    "ISERR" => Some(FormulaFunctionId::Iserr),
    "ISBLANK" => Some(FormulaFunctionId::Isblank),
    "ISTEXT" => Some(FormulaFunctionId::Istext),
    "ISNONTEXT" => Some(FormulaFunctionId::Isnontext),
    "ISLOGICAL" => Some(FormulaFunctionId::Islogical),
    "ISNUMBER" => Some(FormulaFunctionId::Isnumber),
    "ISREF" => Some(FormulaFunctionId::Isref),
    "ISFORMULA" => Some(FormulaFunctionId::Isformula),
    "ERROR.TYPE" => Some(FormulaFunctionId::ErrorDotType),
    "ERRORTYPE" => Some(FormulaFunctionId::Errortype),
    "TYPE" => Some(FormulaFunctionId::Type),
    "AREAS" => Some(FormulaFunctionId::Areas),
    "MIN" => Some(FormulaFunctionId::Min),
    "MINA" => Some(FormulaFunctionId::Mina),
    "MAX" => Some(FormulaFunctionId::Max),
    "MAXA" => Some(FormulaFunctionId::Maxa),
    "AND" => Some(FormulaFunctionId::And),
    "OR" => Some(FormulaFunctionId::Or),
    "XOR" => Some(FormulaFunctionId::Xor),
    "NOT" => Some(FormulaFunctionId::Not),
    "TRUE" => Some(FormulaFunctionId::True),
    "FALSE" => Some(FormulaFunctionId::False),
    "NA" => Some(FormulaFunctionId::Na),
    "STYLE" => Some(FormulaFunctionId::Style),
    "CURRENT" => Some(FormulaFunctionId::Current),
    "N" => Some(FormulaFunctionId::N),
    "COUNTBLANK" => Some(FormulaFunctionId::Countblank),
    "ABS" => Some(FormulaFunctionId::Abs),
    "SIGN" => Some(FormulaFunctionId::Sign),
    "INT" => Some(FormulaFunctionId::Int),
    "TRUNC" => Some(FormulaFunctionId::Trunc),
    "MOD" => Some(FormulaFunctionId::Mod),
    "EVEN" => Some(FormulaFunctionId::Even),
    "ODD" => Some(FormulaFunctionId::Odd),
    "RAWSUBTRACT" => Some(FormulaFunctionId::Rawsubtract),
    "ISEVEN" => Some(FormulaFunctionId::Iseven),
    "ISODD" => Some(FormulaFunctionId::Isodd),
    "SQRT" => Some(FormulaFunctionId::Sqrt),
    "POWER" => Some(FormulaFunctionId::Power),
    "PI" => Some(FormulaFunctionId::Pi),
    "SQRTPI" => Some(FormulaFunctionId::Sqrtpi),
    "RADIANS" => Some(FormulaFunctionId::Radians),
    "DEGREES" => Some(FormulaFunctionId::Degrees),
    "SIN" => Some(FormulaFunctionId::Sin),
    "CSC" => Some(FormulaFunctionId::Csc),
    "COS" => Some(FormulaFunctionId::Cos),
    "SEC" => Some(FormulaFunctionId::Sec),
    "TAN" => Some(FormulaFunctionId::Tan),
    "COT" => Some(FormulaFunctionId::Cot),
    "SINH" => Some(FormulaFunctionId::Sinh),
    "CSCH" => Some(FormulaFunctionId::Csch),
    "COSH" => Some(FormulaFunctionId::Cosh),
    "SECH" => Some(FormulaFunctionId::Sech),
    "TANH" => Some(FormulaFunctionId::Tanh),
    "COTH" => Some(FormulaFunctionId::Coth),
    "ASIN" => Some(FormulaFunctionId::Asin),
    "ASINH" => Some(FormulaFunctionId::Asinh),
    "ACOS" => Some(FormulaFunctionId::Acos),
    "ACOSH" => Some(FormulaFunctionId::Acosh),
    "ACOT" => Some(FormulaFunctionId::Acot),
    "ATAN" => Some(FormulaFunctionId::Atan),
    "ATANH" => Some(FormulaFunctionId::Atanh),
    "ACOTH" => Some(FormulaFunctionId::Acoth),
    "ATAN2" => Some(FormulaFunctionId::Atan2),
    "EXP" => Some(FormulaFunctionId::Exp),
    "LN" => Some(FormulaFunctionId::Ln),
    "LOG10" => Some(FormulaFunctionId::Log10),
    "LOG" => Some(FormulaFunctionId::Log),
    "SUMSQ" => Some(FormulaFunctionId::Sumsq),
    "SUMPRODUCT" => Some(FormulaFunctionId::Sumproduct),
    "ROUND" => Some(FormulaFunctionId::Round),
    "ROUNDSIG" => Some(FormulaFunctionId::Roundsig),
    "ROUNDUP" => Some(FormulaFunctionId::Roundup),
    "ROUNDDOWN" => Some(FormulaFunctionId::Rounddown),
    "DATE" => Some(FormulaFunctionId::Date),
    "DATEVALUE" => Some(FormulaFunctionId::Datevalue),
    "TIME" => Some(FormulaFunctionId::Time),
    "YEAR" => Some(FormulaFunctionId::Year),
    "MONTH" => Some(FormulaFunctionId::Month),
    "DAY" => Some(FormulaFunctionId::Day),
    "WEEKDAY" => Some(FormulaFunctionId::Weekday),
    "HOUR" => Some(FormulaFunctionId::Hour),
    "MINUTE" => Some(FormulaFunctionId::Minute),
    "SECOND" => Some(FormulaFunctionId::Second),
    "DAYS" => Some(FormulaFunctionId::Days),
    "DAYS360" => Some(FormulaFunctionId::Days360),
    "TODAY" => Some(FormulaFunctionId::Today),
    "EOMONTH" => Some(FormulaFunctionId::Eomonth),
    "EDATE" => Some(FormulaFunctionId::Edate),
    "ISLEAPYEAR" => Some(FormulaFunctionId::Isleapyear),
    "TRIM" => Some(FormulaFunctionId::Trim),
    "UPPER" => Some(FormulaFunctionId::Upper),
    "LOWER" => Some(FormulaFunctionId::Lower),
    "ROT13" => Some(FormulaFunctionId::Rot13),
    "PROPER" => Some(FormulaFunctionId::Proper),
    "LEN" => Some(FormulaFunctionId::Len),
    "LENB" => Some(FormulaFunctionId::Lenb),
    "T" => Some(FormulaFunctionId::T),
    "VALUE" => Some(FormulaFunctionId::Value),
    "NUMBERVALUE" => Some(FormulaFunctionId::Numbervalue),
    "DOLLAR" => Some(FormulaFunctionId::Dollar),
    "FIXED" => Some(FormulaFunctionId::Fixed),
    "BASE" => Some(FormulaFunctionId::Base),
    "DECIMAL" | "DEC" => Some(FormulaFunctionId::Decimal),
    "CONVERT" | "CONVERT_OOO" => Some(FormulaFunctionId::Convert),
    "BIN2DEC" => Some(FormulaFunctionId::Bin2dec),
    "OCT2DEC" => Some(FormulaFunctionId::Oct2dec),
    "HEX2DEC" => Some(FormulaFunctionId::Hex2dec),
    "BIN2OCT" => Some(FormulaFunctionId::Bin2oct),
    "BIN2HEX" => Some(FormulaFunctionId::Bin2hex),
    "OCT2BIN" => Some(FormulaFunctionId::Oct2bin),
    "OCT2HEX" => Some(FormulaFunctionId::Oct2hex),
    "HEX2BIN" => Some(FormulaFunctionId::Hex2bin),
    "HEX2OCT" => Some(FormulaFunctionId::Hex2oct),
    "DEC2BIN" => Some(FormulaFunctionId::Dec2bin),
    "DEC2OCT" => Some(FormulaFunctionId::Dec2oct),
    "DEC2HEX" => Some(FormulaFunctionId::Dec2hex),
    "BITAND" => Some(FormulaFunctionId::Bitand),
    "BITOR" => Some(FormulaFunctionId::Bitor),
    "BITXOR" => Some(FormulaFunctionId::Bitxor),
    "BITLSHIFT" => Some(FormulaFunctionId::Bitlshift),
    "BITRSHIFT" => Some(FormulaFunctionId::Bitrshift),
    "CODE" => Some(FormulaFunctionId::Code),
    "UNICODE" => Some(FormulaFunctionId::Unicode),
    "CHAR" => Some(FormulaFunctionId::Char),
    "UNICHAR" => Some(FormulaFunctionId::Unichar),
    "CLEAN" => Some(FormulaFunctionId::Clean),
    "CHOOSE" => Some(FormulaFunctionId::Choose),
    "CONCAT" => Some(FormulaFunctionId::Concat),
    "CONCATENATE" => Some(FormulaFunctionId::Concatenate),
    "EXACT" => Some(FormulaFunctionId::Exact),
    "FIND" => Some(FormulaFunctionId::Find),
    "FINDB" => Some(FormulaFunctionId::Findb),
    "SEARCH" => Some(FormulaFunctionId::Search),
    "SEARCHB" => Some(FormulaFunctionId::Searchb),
    "REPT" => Some(FormulaFunctionId::Rept),
    "SUBSTITUTE" => Some(FormulaFunctionId::Substitute),
    "REPLACE" => Some(FormulaFunctionId::Replace),
    "TEXTBEFORE" => Some(FormulaFunctionId::Textbefore),
    "TEXTAFTER" => Some(FormulaFunctionId::Textafter),
    "TEXTSPLIT" => Some(FormulaFunctionId::Textsplit),
    "TEXTJOIN" => Some(FormulaFunctionId::Textjoin),
    "REPLACEB" => Some(FormulaFunctionId::Replaceb),
    "ASC" => Some(FormulaFunctionId::Asc),
    "JIS" => Some(FormulaFunctionId::Jis),
    "MEDIAN" => Some(FormulaFunctionId::Median),
    "LARGE" => Some(FormulaFunctionId::Large),
    "SMALL" => Some(FormulaFunctionId::Small),
    "TRIMMEAN" => Some(FormulaFunctionId::Trimmean),
    "DEVSQ" => Some(FormulaFunctionId::Devsq),
    "AVEDEV" => Some(FormulaFunctionId::Avedev),
    "AVERAGEA" => Some(FormulaFunctionId::Averagea),
    "STDEV.P" | "STDEVP" => Some(FormulaFunctionId::StdevDotP),
    "STDEV.S" => Some(FormulaFunctionId::StdevDotS),
    "STDEV" => Some(FormulaFunctionId::Stdev),
    "STDEVA" => Some(FormulaFunctionId::Stdeva),
    "STDEVPA" => Some(FormulaFunctionId::Stdevpa),
    "VAR.P" | "VARP" => Some(FormulaFunctionId::VarDotP),
    "VAR.S" | "VAR" => Some(FormulaFunctionId::VarDotS),
    "VARA" => Some(FormulaFunctionId::Vara),
    "VARPA" => Some(FormulaFunctionId::Varpa),
    "SKEW" => Some(FormulaFunctionId::Skew),
    "SKEW.P" | "SKEWP" => Some(FormulaFunctionId::SkewDotP),
    "GEOMEAN" => Some(FormulaFunctionId::Geomean),
    "HARMEAN" => Some(FormulaFunctionId::Harmean),
    "GAUSS" => Some(FormulaFunctionId::Gauss),
    "TEXT" => Some(FormulaFunctionId::Text),
    "TIMEVALUE" => Some(FormulaFunctionId::Timevalue),
    "BASISODATETIME" => Some(FormulaFunctionId::Basisodatetime),
    "DATEDIF" => Some(FormulaFunctionId::Datedif),
    "YEARFRAC" => Some(FormulaFunctionId::Yearfrac),
    "WEEKNUM" => Some(FormulaFunctionId::Weeknum),
    "ISOWEEKNUM" => Some(FormulaFunctionId::Isoweeknum),
    "WEEKS" => Some(FormulaFunctionId::Weeks),
    "WEEKSINYEAR" => Some(FormulaFunctionId::Weeksinyear),
    "YEARS" => Some(FormulaFunctionId::Years),
    "MONTHS" => Some(FormulaFunctionId::Months),
    "DAYSINMONTH" => Some(FormulaFunctionId::Daysinmonth),
    "DAYSINYEAR" => Some(FormulaFunctionId::Daysinyear),
    "INDIRECT" => Some(FormulaFunctionId::Indirect),
    "INDEX" => Some(FormulaFunctionId::Index),
    "OFFSET" => Some(FormulaFunctionId::Offset),
    "LOOKUP" => Some(FormulaFunctionId::Lookup),
    "MATCH" => Some(FormulaFunctionId::Match),
    "XMATCH" => Some(FormulaFunctionId::Xmatch),
    "VLOOKUP" => Some(FormulaFunctionId::Vlookup),
    "HLOOKUP" => Some(FormulaFunctionId::Hlookup),
    "XLOOKUP" => Some(FormulaFunctionId::Xlookup),
    "SHEETS" => Some(FormulaFunctionId::Sheets),
    "SHEET" => Some(FormulaFunctionId::Sheet),
    "FORMULA" | "FORMULATEXT" => Some(FormulaFunctionId::Formula),
    "CELL" => Some(FormulaFunctionId::Cell),
    "ADDRESS" => Some(FormulaFunctionId::Address),
    "ROW" => Some(FormulaFunctionId::Row),
    "COLUMN" => Some(FormulaFunctionId::Column),
    "ROWS" => Some(FormulaFunctionId::Rows),
    "COLUMNS" => Some(FormulaFunctionId::Columns),
    "MID" => Some(FormulaFunctionId::Mid),
    "MIDB" => Some(FormulaFunctionId::Midb),
    "LEFT" => Some(FormulaFunctionId::Left),
    "LEFTB" => Some(FormulaFunctionId::Leftb),
    "RIGHT" => Some(FormulaFunctionId::Right),
    "RIGHTB" => Some(FormulaFunctionId::Rightb),
    "ROMAN" => Some(FormulaFunctionId::Roman),
    "ARABIC" => Some(FormulaFunctionId::Arabic),
    "HYPERLINK" => Some(FormulaFunctionId::Hyperlink),
    "TOCOL" => Some(FormulaFunctionId::Tocol),
    "TOROW" => Some(FormulaFunctionId::Torow),
    "CHOOSEROWS" => Some(FormulaFunctionId::Chooserows),
    "CHOOSECOLS" => Some(FormulaFunctionId::Choosecols),
    "EXPAND" => Some(FormulaFunctionId::Expand),
    "HSTACK" => Some(FormulaFunctionId::Hstack),
    "VSTACK" => Some(FormulaFunctionId::Vstack),
    "WRAPCOLS" => Some(FormulaFunctionId::Wrapcols),
    "WRAPROWS" => Some(FormulaFunctionId::Wraprows),
    "FILTER" => Some(FormulaFunctionId::Filter),
    "UNIQUE" => Some(FormulaFunctionId::Unique),
    "SEQUENCE" => Some(FormulaFunctionId::Sequence),
    "TRANSPOSE" => Some(FormulaFunctionId::Transpose),
    "DROP" => Some(FormulaFunctionId::Drop),
    "TAKE" => Some(FormulaFunctionId::Take),
    "SORT" => Some(FormulaFunctionId::Sort),
    "SORTBY" => Some(FormulaFunctionId::Sortby),
    "MMULT" => Some(FormulaFunctionId::Mmult),
    "MDETERM" => Some(FormulaFunctionId::Mdeterm),
    "MINVERSE" => Some(FormulaFunctionId::Minverse),
    "MUNIT" => Some(FormulaFunctionId::Munit),
    "GCD" => Some(FormulaFunctionId::Gcd),
    "LCM" => Some(FormulaFunctionId::Lcm),
    "FACT" => Some(FormulaFunctionId::Fact),
    "FACTDOUBLE" => Some(FormulaFunctionId::Factdouble),
    "MULTINOMIAL" => Some(FormulaFunctionId::Multinomial),
    "COMBIN" => Some(FormulaFunctionId::Combin),
    "COMBINA" => Some(FormulaFunctionId::Combina),
    "PERMUT" => Some(FormulaFunctionId::Permut),
    "PERMUTATIONA" => Some(FormulaFunctionId::Permutationa),
    "MROUND" => Some(FormulaFunctionId::Mround),
    "QUOTIENT" => Some(FormulaFunctionId::Quotient),
    "PMT" => Some(FormulaFunctionId::Pmt),
    "FV" => Some(FormulaFunctionId::Fv),
    "FVSCHEDULE" => Some(FormulaFunctionId::Fvschedule),
    "NPV" => Some(FormulaFunctionId::Npv),
    "EFFECT" => Some(FormulaFunctionId::Effect),
    "RATE" => Some(FormulaFunctionId::Rate),
    "ISPMT" => Some(FormulaFunctionId::Ispmt),
    "IPMT" => Some(FormulaFunctionId::Ipmt),
    "PPMT" => Some(FormulaFunctionId::Ppmt),
    "CUMIPMT" => Some(FormulaFunctionId::Cumipmt),
    "CUMPRINC" => Some(FormulaFunctionId::Cumprinc),
    "DDB" => Some(FormulaFunctionId::Ddb),
    "VDB" => Some(FormulaFunctionId::Vdb),
    "SUMIFS" => Some(FormulaFunctionId::Sumifs),
    "COUNTIFS" => Some(FormulaFunctionId::Countifs),
    "MAXIFS" => Some(FormulaFunctionId::Maxifs),
    "MINIFS" => Some(FormulaFunctionId::Minifs),
    "SUMIF" => Some(FormulaFunctionId::Sumif),
    "COUNTIF" => Some(FormulaFunctionId::Countif),
    "AVERAGEIF" => Some(FormulaFunctionId::Averageif),
    "AVERAGEIFS" => Some(FormulaFunctionId::Averageifs),
    "DSUM" => Some(FormulaFunctionId::Dsum),
    "DCOUNT" => Some(FormulaFunctionId::Dcount),
    "DCOUNTA" => Some(FormulaFunctionId::Dcounta),
    "DAVERAGE" => Some(FormulaFunctionId::Daverage),
    "DGET" => Some(FormulaFunctionId::Dget),
    "DMAX" => Some(FormulaFunctionId::Dmax),
    "DMIN" => Some(FormulaFunctionId::Dmin),
    "DPRODUCT" => Some(FormulaFunctionId::Dproduct),
    "DVAR" => Some(FormulaFunctionId::Dvar),
    "DVARP" => Some(FormulaFunctionId::Dvarp),
    "DSTDEV" => Some(FormulaFunctionId::Dstdev),
    "DSTDEVP" => Some(FormulaFunctionId::Dstdevp),
    "CEILING" => Some(FormulaFunctionId::Ceiling),
    "CEILING.MATH" => Some(FormulaFunctionId::CeilingDotMath),
    "CEILING.PRECISE" | "ISO.CEILING" => Some(FormulaFunctionId::CeilingDotPrecise),
    "FLOOR" => Some(FormulaFunctionId::Floor),
    "FLOOR.MATH" => Some(FormulaFunctionId::FloorDotMath),
    "FLOOR.PRECISE" => Some(FormulaFunctionId::FloorDotPrecise),
    "B" => Some(FormulaFunctionId::B),
    "BETA.DIST" => Some(FormulaFunctionId::BetaDotDist),
    "BETADIST" => Some(FormulaFunctionId::Betadist),
    "BETA.INV" | "BETAINV" => Some(FormulaFunctionId::BetaDotInv),
    "BINOM.DIST" | "BINOMDIST" => Some(FormulaFunctionId::BinomDotDist),
    "BINOM.DIST.RANGE" => Some(FormulaFunctionId::BinomDotDistDotRange),
    "BINOM.INV" | "CRITBINOM" => Some(FormulaFunctionId::BinomDotInv),
    "CHISQ.DIST" => Some(FormulaFunctionId::ChisqDotDist),
    "CHISQ.DIST.RT" | "CHIDIST" | "LEGACY.CHIDIST" => Some(FormulaFunctionId::ChisqDotDistDotRt),
    "CHISQDIST" => Some(FormulaFunctionId::Chisqdist),
    "CHISQ.INV" => Some(FormulaFunctionId::ChisqDotInv),
    "CHISQINV" => Some(FormulaFunctionId::Chisqinv),
    "CHISQ.INV.RT" | "LEGACY.CHIINV" => Some(FormulaFunctionId::ChisqDotInvDotRt),
    "CHISQ.TEST" | "CHITEST" | "LEGACY.CHITEST" => Some(FormulaFunctionId::ChisqDotTest),
    "CONFIDENCE.NORM" | "CONFIDENCE" => Some(FormulaFunctionId::ConfidenceDotNorm),
    "CONFIDENCE.T" => Some(FormulaFunctionId::ConfidenceDotT),
    "COVARIANCE.P" => Some(FormulaFunctionId::CovarianceDotP),
    "COVARIANCE.S" => Some(FormulaFunctionId::CovarianceDotS),
    "COVAR" => Some(FormulaFunctionId::Covar),
    "CORREL" => Some(FormulaFunctionId::Correl),
    "PEARSON" => Some(FormulaFunctionId::Pearson),
    "PHI" => Some(FormulaFunctionId::Phi),
    "ERF.PRECISE" => Some(FormulaFunctionId::ErfDotPrecise),
    "ERF" => Some(FormulaFunctionId::Erf),
    "ERFC.PRECISE" | "ERFC" => Some(FormulaFunctionId::ErfcDotPrecise),
    "EXPON.DIST" | "EXPONDIST" => Some(FormulaFunctionId::ExponDotDist),
    "F.DIST" => Some(FormulaFunctionId::FDotDist),
    "F.DIST.RT" | "FDIST" | "LEGACY.FDIST" => Some(FormulaFunctionId::FDotDistDotRt),
    "F.INV" | "FINV" => Some(FormulaFunctionId::FDotInv),
    "F.INV.RT" | "LEGACY.FINV" => Some(FormulaFunctionId::FDotInvDotRt),
    "F.TEST" | "FTEST" => Some(FormulaFunctionId::FDotTest),
    "GAMMA.DIST" | "GAMMADIST" => Some(FormulaFunctionId::GammaDotDist),
    "GAMMA.INV" | "GAMMAINV" => Some(FormulaFunctionId::GammaDotInv),
    "GAMMA" => Some(FormulaFunctionId::Gamma),
    "GAMMALN.PRECISE" | "GAMMALN" => Some(FormulaFunctionId::GammalnDotPrecise),
    "HYPGEOM.DIST" | "HYPGEOMDIST" => Some(FormulaFunctionId::HypgeomDotDist),
    "LOGNORM.DIST" | "LOGNORMDIST" => Some(FormulaFunctionId::LognormDotDist),
    "LOGNORM.INV" | "LOGINV" => Some(FormulaFunctionId::LognormDotInv),
    "MODE.MULT" => Some(FormulaFunctionId::ModeDotMult),
    "MODE.SNGL" => Some(FormulaFunctionId::ModeDotSngl),
    "MODE" => Some(FormulaFunctionId::Mode),
    "NEGBINOM.DIST" => Some(FormulaFunctionId::NegbinomDotDist),
    "NEGBINOMDIST" => Some(FormulaFunctionId::Negbinomdist),
    "NORM.DIST" | "NORMDIST" => Some(FormulaFunctionId::NormDotDist),
    "NORM.INV" | "NORMINV" => Some(FormulaFunctionId::NormDotInv),
    "NORM.S.DIST" | "NORMSDIST" | "LEGACY.NORMSDIST" => Some(FormulaFunctionId::NormDotSDotDist),
    "NORM.S.INV" | "NORMSINV" | "LEGACY.NORMSINV" => Some(FormulaFunctionId::NormDotSDotInv),
    "PERCENTILE.EXC" => Some(FormulaFunctionId::PercentileDotExc),
    "PERCENTILE.INC" | "PERCENTILE" => Some(FormulaFunctionId::PercentileDotInc),
    "PERCENTRANK" | "PERCENTRANK.INC" => Some(FormulaFunctionId::Percentrank),
    "PERCENTRANK.EXC" => Some(FormulaFunctionId::PercentrankDotExc),
    "POISSON.DIST" => Some(FormulaFunctionId::PoissonDotDist),
    "POISSON" => Some(FormulaFunctionId::Poisson),
    "QUARTILE.EXC" => Some(FormulaFunctionId::QuartileDotExc),
    "QUARTILE.INC" | "QUARTILE" => Some(FormulaFunctionId::QuartileDotInc),
    "RANK.AVG" => Some(FormulaFunctionId::RankDotAvg),
    "RANK.EQ" | "RANK" => Some(FormulaFunctionId::RankDotEq),
    "KURT" => Some(FormulaFunctionId::Kurt),
    "T.DIST" => Some(FormulaFunctionId::TDotDist),
    "T.DIST.2T" => Some(FormulaFunctionId::TDotDistDot2t),
    "T.DIST.RT" => Some(FormulaFunctionId::TDotDistDotRt),
    "TDIST" | "LEGACY.TDIST" => Some(FormulaFunctionId::Tdist),
    "T.INV" => Some(FormulaFunctionId::TDotInv),
    "T.INV.2T" | "TINV" => Some(FormulaFunctionId::TDotInvDot2t),
    "T.TEST" | "TTEST" => Some(FormulaFunctionId::TDotTest),
    "FISHER" => Some(FormulaFunctionId::Fisher),
    "FISHERINV" => Some(FormulaFunctionId::Fisherinv),
    "BESSELI" => Some(FormulaFunctionId::Besseli),
    "BESSELJ" => Some(FormulaFunctionId::Besselj),
    "BESSELK" => Some(FormulaFunctionId::Besselk),
    "BESSELY" => Some(FormulaFunctionId::Bessely),
    "FOURIER" | "ORG.LIBREOFFICE.FOURIER" => Some(FormulaFunctionId::Fourier),
    "IMREAL" => Some(FormulaFunctionId::Imreal),
    "IMAGINARY" => Some(FormulaFunctionId::Imaginary),
    "IMABS" => Some(FormulaFunctionId::Imabs),
    "IMARGUMENT" => Some(FormulaFunctionId::Imargument),
    "IMCONJUGATE" => Some(FormulaFunctionId::Imconjugate),
    "IMEXP" => Some(FormulaFunctionId::Imexp),
    "IMLN" => Some(FormulaFunctionId::Imln),
    "IMLOG10" => Some(FormulaFunctionId::Imlog10),
    "IMLOG2" => Some(FormulaFunctionId::Imlog2),
    "IMSIN" => Some(FormulaFunctionId::Imsin),
    "IMSINH" => Some(FormulaFunctionId::Imsinh),
    "IMCOSH" => Some(FormulaFunctionId::Imcosh),
    "IMTAN" => Some(FormulaFunctionId::Imtan),
    "IMCOT" => Some(FormulaFunctionId::Imcot),
    "IMCSC" => Some(FormulaFunctionId::Imcsc),
    "IMSQRT" => Some(FormulaFunctionId::Imsqrt),
    "IMCOS" => Some(FormulaFunctionId::Imcos),
    "IMSEC" => Some(FormulaFunctionId::Imsec),
    "IMSECH" => Some(FormulaFunctionId::Imsech),
    "IMCSCH" => Some(FormulaFunctionId::Imcsch),
    "IMSUB" => Some(FormulaFunctionId::Imsub),
    "IMDIV" => Some(FormulaFunctionId::Imdiv),
    "IMPOWER" => Some(FormulaFunctionId::Impower),
    "IMSUM" => Some(FormulaFunctionId::Imsum),
    "IMPRODUCT" => Some(FormulaFunctionId::Improduct),
    "COMPLEX" => Some(FormulaFunctionId::Complex),
    "DELTA" => Some(FormulaFunctionId::Delta),
    "GESTEP" => Some(FormulaFunctionId::Gestep),
    "SLOPE" => Some(FormulaFunctionId::Slope),
    "INTERCEPT" => Some(FormulaFunctionId::Intercept),
    "FORECAST" | "FORECAST.LINEAR" => Some(FormulaFunctionId::Forecast),
    "FORECAST.ETS" | "FORECAST.ETS.ADD" => Some(FormulaFunctionId::ForecastDotEts),
    "FORECAST.ETS.MULT" => Some(FormulaFunctionId::ForecastDotEtsDotMult),
    "FORECAST.ETS.STAT" | "FORECAST.ETS.STAT.ADD" => Some(FormulaFunctionId::ForecastDotEtsDotStat),
    "FORECAST.ETS.STAT.MULT" => Some(FormulaFunctionId::ForecastDotEtsDotStatDotMult),
    "FORECAST.ETS.SEASONALITY" => Some(FormulaFunctionId::ForecastDotEtsDotSeasonality),
    "RSQ" => Some(FormulaFunctionId::Rsq),
    "STEYX" => Some(FormulaFunctionId::Steyx),
    "LINEST" => Some(FormulaFunctionId::Linest),
    "LOGEST" => Some(FormulaFunctionId::Logest),
    "TREND" => Some(FormulaFunctionId::Trend),
    "GROWTH" => Some(FormulaFunctionId::Growth),
    "WEIBULL.DIST" | "WEIBULL" => Some(FormulaFunctionId::WeibullDotDist),
    "NETWORKDAYS.INTL" => Some(FormulaFunctionId::NetworkdaysDotIntl),
    "NETWORKDAYS" => Some(FormulaFunctionId::Networkdays),
    "WORKDAY.INTL" => Some(FormulaFunctionId::WorkdayDotIntl),
    "WORKDAY" => Some(FormulaFunctionId::Workday),
    "Z.TEST" | "ZTEST" => Some(FormulaFunctionId::ZDotTest),
    "STANDARDIZE" => Some(FormulaFunctionId::Standardize),
    "SUBTOTAL" => Some(FormulaFunctionId::Subtotal),
    "AGGREGATE" => Some(FormulaFunctionId::Aggregate),
    "DB" => Some(FormulaFunctionId::Db),
    "PRICE" => Some(FormulaFunctionId::Price),
    "YIELD" => Some(FormulaFunctionId::Yield),
    "PRICEDISC" => Some(FormulaFunctionId::Pricedisc),
    "PRICEMAT" => Some(FormulaFunctionId::Pricemat),
    "YIELDDISC" => Some(FormulaFunctionId::Yielddisc),
    "ACCRINT" => Some(FormulaFunctionId::Accrint),
    "ACCRINTM" => Some(FormulaFunctionId::Accrintm),
    "ODDLPRICE" => Some(FormulaFunctionId::Oddlprice),
    "ODDLYIELD" => Some(FormulaFunctionId::Oddlyield),
    "AMORLINC" => Some(FormulaFunctionId::Amorlinc),
    "AMORDEGRC" => Some(FormulaFunctionId::Amordegrc),
    "DISC" => Some(FormulaFunctionId::Disc),
    "RECEIVED" => Some(FormulaFunctionId::Received),
    "INTRATE" => Some(FormulaFunctionId::Intrate),
    "MDURATION" => Some(FormulaFunctionId::Mduration),
    "COUPDAYS" => Some(FormulaFunctionId::Coupdays),
    "COUPDAYBS" => Some(FormulaFunctionId::Coupdaybs),
    "COUPDAYSNC" => Some(FormulaFunctionId::Coupdaysnc),
    "COUPNCD" => Some(FormulaFunctionId::Coupncd),
    "COUPNUM" => Some(FormulaFunctionId::Coupnum),
    "COUPPCD" => Some(FormulaFunctionId::Couppcd),
    "TBILLEQ" => Some(FormulaFunctionId::Tbilleq),
    "TBILLPRICE" => Some(FormulaFunctionId::Tbillprice),
    "TBILLYIELD" => Some(FormulaFunctionId::Tbillyield),
    "PV" => Some(FormulaFunctionId::Pv),
    "NPER" => Some(FormulaFunctionId::Nper),
    "RRI" => Some(FormulaFunctionId::Rri),
    "PDURATION" => Some(FormulaFunctionId::Pduration),
    "SERIESSUM" => Some(FormulaFunctionId::Seriessum),
    "EASTERSUNDAY" | "ORG.OPENOFFICE.EASTERSUNDAY" => Some(FormulaFunctionId::Eastersunday),
    "XIRR" => Some(FormulaFunctionId::Xirr),
    "XNPV" => Some(FormulaFunctionId::Xnpv),
    "IRR" => Some(FormulaFunctionId::Irr),
    "MIRR" => Some(FormulaFunctionId::Mirr),
    "EUROCONVERT" => Some(FormulaFunctionId::Euroconvert),
    "BAHTTEXT" => Some(FormulaFunctionId::Bahttext),
    "NOMINAL" => Some(FormulaFunctionId::Nominal),
    "SLN" => Some(FormulaFunctionId::Sln),
    "SYD" => Some(FormulaFunctionId::Syd),
    "PROB" => Some(FormulaFunctionId::Prob),
    "FREQUENCY" => Some(FormulaFunctionId::Frequency),
    "SUMX2MY2" => Some(FormulaFunctionId::Sumx2my2),
    "SUMX2PY2" => Some(FormulaFunctionId::Sumx2py2),
    "SUMXMY2" => Some(FormulaFunctionId::Sumxmy2),
    "DOLLARDE" => Some(FormulaFunctionId::Dollarde),
    "DOLLARFR" => Some(FormulaFunctionId::Dollarfr),
    "INFO" => Some(FormulaFunctionId::Info),
    "REGEX" => Some(FormulaFunctionId::Regex),
    "ENCODEURL" => Some(FormulaFunctionId::Encodeurl),
    "ORG.OPENOFFICE.ROT13" => Some(FormulaFunctionId::OrgDotOpenofficeDotRot13),
    "GETPIVOTDATA" => Some(FormulaFunctionId::Getpivotdata),
    "COLOR" | "ORG.LIBREOFFICE.COLOR" => Some(FormulaFunctionId::Color),
    "DHFG" | "OF" => Some(FormulaFunctionId::Dhfg),
    "TESTFUNCBOOL" => Some(FormulaFunctionId::Testfuncbool),
    "TESTFUNCCURR" => Some(FormulaFunctionId::Testfunccurr),
    "TESTFUNCDATE" => Some(FormulaFunctionId::Testfuncdate),
    "RANDBETWEEN" => Some(FormulaFunctionId::Randbetween),
    "RANDARRAY" => Some(FormulaFunctionId::Randarray),
    "TESTFUNCINT" | "TESTFUNCLONG" => Some(FormulaFunctionId::Testfuncint),
    "TESTFUNCSINGLE" | "TESTFUNCDOUBLE" => Some(FormulaFunctionId::Testfuncsingle),
    _ => None,
  }
}
