use std::{
  collections::{BTreeMap, BTreeSet},
  env, fs,
  path::{Path, PathBuf},
};

fn main() {
  let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("missing manifest dir"));
  let workspace_dir = manifest_dir
    .parent()
    .and_then(Path::parent)
    .expect("manifest dir should be under crates/ooxmlsdk-test");
  let doc_samples_dir = manifest_dir.join("doc_samples");
  let test_data_dir = workspace_dir.join("test-data");
  let out_dir = PathBuf::from(env::var("OUT_DIR").expect("missing OUT_DIR"));
  let out_file = out_dir.join("doc_samples_tests.rs");
  let bool_attrs_file = out_dir.join("doc_samples_bool_attrs.rs");

  println!("cargo:rerun-if-changed={}", doc_samples_dir.display());
  println!("cargo:rerun-if-changed={}", test_data_dir.display());

  let samples = collect_doc_files(&doc_samples_dir, &doc_samples_dir);
  let test_data_files = collect_doc_files(&test_data_dir, workspace_dir);

  let mut generated = String::from("// @generated by build.rs\n\n");
  for file_name in samples {
    let slug = slugify(&file_name);
    let test_name = format!("doc_sample_{slug}");
    let version_cfg = version_cfg_attr(&file_name);

    if is_invalid(&file_name) {
      if !version_cfg.is_empty() {
        generated.push_str(&version_cfg);
      }
      generated.push_str(&format!(
        "#[test]\nfn invalid_{test_name}() {{\n  assert_doc_sample_invalid({file_name:?});\n}}\n\n"
      ));
      continue;
    }

    if is_valid_open_only(&file_name) {
      if !version_cfg.is_empty() {
        generated.push_str(&version_cfg);
      }
      generated.push_str(&format!(
        "#[test]\nfn open_valid_{test_name}() {{\n  assert_doc_sample_opens({file_name:?});\n}}\n\n"
      ));
      continue;
    }

    if !is_round_trip_supported(&file_name) {
      if !version_cfg.is_empty() {
        generated.push_str(&version_cfg);
      }
      generated.push_str(&format!(
        "#[test]\nfn open_{test_name}() {{\n  assert_doc_sample_opens({file_name:?});\n}}\n\n"
      ));
      continue;
    }

    if !version_cfg.is_empty() {
      generated.push_str(&version_cfg);
    }

    generated.push_str(&format!(
      "#[test]\nfn round_trip_{test_name}() {{\n  assert_doc_sample_round_trip({file_name:?});\n}}\n\n"
    ));
  }

  for file_name in test_data_files {
    let slug = slugify(&file_name);
    let test_name = format!("test_data_{slug}");

    if is_test_data_open_only(&file_name) {
      generated.push_str(&format!(
        "#[test]\nfn open_valid_{test_name}() {{\n  assert_test_data_opens({file_name:?});\n}}\n\n"
      ));
      continue;
    }

    generated.push_str(&format!(
      "#[test]\nfn round_trip_{test_name}() {{\n  assert_test_data_round_trip({file_name:?});\n}}\n\n"
    ));
  }

  fs::write(out_file, generated).expect("write generated doc sample tests");
  write_bool_attr_rules(workspace_dir, &bool_attrs_file);
}

fn collect_doc_files(root: &Path, rel_root: &Path) -> Vec<String> {
  if !root.exists() {
    return Vec::new();
  }

  let mut files = Vec::new();
  collect_doc_files_recursive(root, rel_root, &mut files);
  files.sort();
  files
}

fn collect_doc_files_recursive(dir: &Path, rel_root: &Path, files: &mut Vec<String>) {
  for entry in fs::read_dir(dir).expect("read doc file dir") {
    let entry = entry.expect("read doc file entry");
    let path = entry.path();

    if path.is_dir() {
      println!("cargo:rerun-if-changed={}", path.display());
      collect_doc_files_recursive(&path, rel_root, files);
      continue;
    }

    if path.is_file() && is_supported_document_path(&path) {
      println!("cargo:rerun-if-changed={}", path.display());
      files.push(
        path
          .strip_prefix(rel_root)
          .unwrap_or(&path)
          .to_string_lossy()
          .replace('\\', "/"),
      );
    }
  }
}

fn is_supported_document_path(path: &Path) -> bool {
  matches!(
    path.extension().and_then(|ext| ext.to_str()),
    Some("docx" | "dotx" | "xlsx" | "xltx" | "pptx" | "potx")
  )
}

fn is_invalid(file_name: &str) -> bool {
  matches!(
    file_name,
    "5Errors.docx"
      | "complex0.docx"
      | "complex2010.docx"
      | "mcdoc.docx"
      | "Of16-09-UnknownElement.docx"
      | "Strict01.docx"
      | "UnknownElement.docx"
      | "encrypted_pptx.pptx"
  )
}

fn is_round_trip_supported(file_name: &str) -> bool {
  !matches!(
    file_name,
    "animation.pptx"
      | "3dtestdash.pptx"
      | "3dtestdot.pptx"
      | "Complex01.docx"
      | "Complex01.xlsx"
      | "complex0.docx"
      | "complex2010.docx"
      | "Document.docx"
      | "extlst.xlsx"
      | "HelloWorld.docx"
      | "HelloO14.docx"
      | "layout_altcontent.pptx"
      | "malformed_uri.xlsx"
      | "malformed_uri_long.xlsx"
      | "master_altcontent.pptx"
      | "mcdoc.docx"
      | "MCExecl.xlsx"
      | "mcppt.pptx"
      | "missingcalcchainpart.xlsx"
      | "notes_altcontent.pptx"
      | "Of16-01.docx"
      | "Of16-01.pptx"
      | "Of16-02.docx"
      | "Of16-02.pptx"
      | "Of16-03.docx"
      | "Of16-03.pptx"
      | "Of16-04.docx"
      | "Of16-05.docx"
      | "Of16-06.docx"
      | "Of16-07.docx"
      | "Of16-08.docx"
      | "Of16-09-UnknownElement.docx"
      | "Of16-10-SymEx.docx"
      | "simpleSdt.docx"
      | "slide_altcontent.pptx"
      | "Spreadsheet.xlsx"
      | "Youtube.xlsx"
  )
}

fn is_valid_open_only(file_name: &str) -> bool {
  matches!(file_name, "5Errors.docx" | "InvalidDocProps.docx")
}

fn is_test_data_open_only(file_name: &str) -> bool {
  matches!(
    file_name,
    "test-data/document/minimal_empty.docx"
      | "test-data/document/minimal_table.docx"
      | "test-data/document/minimal_text.docx"
      | "test-data/drawingml/effects.pptx"
      | "test-data/mce/alternate_content_fallback.docx"
      | "test-data/mce/alternate_content_pptx.pptx"
      | "test-data/mce/ignorable_unknown_ns.docx"
      | "test-data/mce/must_understand_ok.docx"
      | "test-data/mce/nested_alternate_content.docx"
      | "test-data/mce/process_content.docx"
      | "test-data/opc/core_properties.docx"
      | "test-data/opc/thumbnail.docx"
  )
}

fn version_cfg_attr(file_name: &str) -> String {
  let _ = file_name;
  String::new()
}

fn slugify(input: &str) -> String {
  let mut out = String::new();
  let mut prev_underscore = false;

  for ch in input.chars() {
    if ch.is_ascii_alphanumeric() {
      out.push(ch.to_ascii_lowercase());
      prev_underscore = false;
    } else if !prev_underscore {
      out.push('_');
      prev_underscore = true;
    }
  }

  while out.starts_with('_') {
    out.remove(0);
  }
  while out.ends_with('_') {
    out.pop();
  }

  if out.is_empty() {
    out.push_str("sample");
  }

  if out.chars().next().is_some_and(|ch| ch.is_ascii_digit()) {
    out.insert_str(0, "sample_");
  }

  out
}

fn write_bool_attr_rules(workspace_dir: &Path, out_file: &Path) {
  let namespace_file = workspace_dir.join("sdk_data/namespaces.json");
  println!("cargo:rerun-if-changed={}", namespace_file.display());
  let namespaces = read_namespaces(&namespace_file);

  let schemas_dir = workspace_dir.join("sdk_data/schemas");
  println!("cargo:rerun-if-changed={}", schemas_dir.display());

  let mut pairs = BTreeSet::new();
  for entry in fs::read_dir(&schemas_dir).expect("read sdk_data schema dir") {
    let entry = entry.expect("read generated schema entry");
    let path = entry.path();
    if path.extension().and_then(|ext| ext.to_str()) != Some("json") {
      continue;
    }
    println!("cargo:rerun-if-changed={}", path.display());
    collect_schema_bool_attrs_from_data(&path, &namespaces, &mut pairs);
  }

  let mut generated = String::from("// @generated by build.rs\n\n");
  generated.push_str("fn is_schema_bool_attr(element_name: &str, attr_name: &str) -> bool {\n");
  generated.push_str("  matches!((element_name, attr_name),\n");
  for (element_name, attr_name) in pairs {
    generated.push_str("    (");
    generated.push_str(&format!("{element_name:?}, {attr_name:?}"));
    generated.push_str(") |\n");
  }
  generated.push_str("    (\"\", \"\")\n");
  generated.push_str("  )\n");
  generated.push_str("}\n");

  fs::write(out_file, generated).expect("write generated bool attribute rules");
}

fn read_namespaces(path: &Path) -> BTreeMap<String, String> {
  let raw = fs::read_to_string(path).expect("read namespaces.json");
  let values: Vec<serde_json::Value> = serde_json::from_str(&raw).expect("parse namespaces.json");
  values
    .into_iter()
    .filter_map(|value| {
      let prefix = value.get("Prefix")?.as_str()?.to_string();
      let uri = value.get("Uri")?.as_str()?.to_string();
      Some((prefix, uri))
    })
    .collect()
}

fn collect_schema_bool_attrs_from_data(
  path: &Path,
  namespaces: &BTreeMap<String, String>,
  pairs: &mut BTreeSet<(String, String)>,
) {
  let raw = fs::read_to_string(path).expect("read sdk_data schema");
  let schema: serde_json::Value = serde_json::from_str(&raw).expect("parse sdk_data schema");
  let Some(types) = schema.get("Types").and_then(serde_json::Value::as_array) else {
    return;
  };
  let type_by_name = types
    .iter()
    .filter_map(|ty| Some((ty.get("RustName")?.as_str()?, ty)))
    .collect::<BTreeMap<_, _>>();

  for ty in types {
    let Some(element_qname) = ty.get("XmlQName").and_then(serde_json::Value::as_str) else {
      continue;
    };
    let element_name = expand_generated_qname(element_qname, namespaces, false);
    collect_type_bool_attrs(ty, &type_by_name, namespaces, &element_name, pairs);
  }
}

fn collect_type_bool_attrs(
  ty: &serde_json::Value,
  type_by_name: &BTreeMap<&str, &serde_json::Value>,
  namespaces: &BTreeMap<String, String>,
  element_name: &str,
  pairs: &mut BTreeSet<(String, String)>,
) {
  if let Some(base_name) = ty.get("BaseRustName").and_then(serde_json::Value::as_str)
    && let Some(base_ty) = type_by_name.get(base_name)
  {
    collect_type_bool_attrs(base_ty, type_by_name, namespaces, element_name, pairs);
  }

  let Some(members) = ty.get("Members").and_then(serde_json::Value::as_array) else {
    return;
  };
  for member in members {
    let Some(field) = member.get("Field") else {
      continue;
    };
    let Some(type_ref) = field
      .get("TypeRef")
      .and_then(|type_ref| type_ref.get("RustType"))
      .and_then(serde_json::Value::as_str)
    else {
      continue;
    };
    if !is_bool_attr_type(type_ref) {
      continue;
    }
    let Some(attr_qname) = field
      .get("Wire")
      .and_then(|wire| wire.get("Attribute"))
      .and_then(|attr| attr.get("QName"))
      .and_then(serde_json::Value::as_str)
    else {
      continue;
    };
    pairs.insert((
      element_name.to_string(),
      expand_generated_qname(attr_qname, namespaces, true),
    ));
  }
}

fn is_bool_attr_type(type_name: &str) -> bool {
  matches!(
    type_name,
    "BooleanValue" | "OnOffValue" | "TrueFalseValue" | "TrueFalseBlankValue"
  )
}

fn expand_generated_qname(
  qname: &str,
  namespaces: &BTreeMap<String, String>,
  is_attr: bool,
) -> String {
  let element_qname = qname.rsplit('/').next().unwrap_or(qname);
  let Some((prefix, local_name)) = element_qname.split_once(':') else {
    return element_qname.to_string();
  };
  if prefix.is_empty() && is_attr {
    return local_name.to_string();
  }
  let Some(uri) = namespaces.get(prefix) else {
    return element_qname.to_string();
  };
  format!("{{{uri}}}{local_name}")
}
