use std::{env, fs, path::PathBuf};

fn main() {
  let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("missing manifest dir"));
  let doc_samples_dir = manifest_dir.join("doc_samples");
  let out_dir = PathBuf::from(env::var("OUT_DIR").expect("missing OUT_DIR"));
  let out_file = out_dir.join("doc_samples_tests.rs");

  println!("cargo:rerun-if-changed={}", doc_samples_dir.display());

  let mut samples = Vec::new();
  for entry in fs::read_dir(&doc_samples_dir).expect("read doc_samples dir") {
    let entry = entry.expect("read doc_samples entry");
    let path = entry.path();
    if path.is_file() {
      println!("cargo:rerun-if-changed={}", path.display());
      samples.push(entry.file_name().to_string_lossy().into_owned());
    }
  }
  samples.sort();

  let mut generated = String::from("// @generated by build.rs\n\n");
  for file_name in samples {
    let slug = slugify(&file_name);
    let test_name = format!("doc_sample_{slug}");

    if is_open_failure(&file_name) {
      generated.push_str(&format!(
        "#[test]\nfn open_failure_{test_name}() {{\n  assert_doc_sample_open_failure({file_name:?});\n}}\n\n"
      ));
      continue;
    }

    if is_valid_open_only(&file_name) {
      generated.push_str(&format!(
        "#[test]\nfn open_valid_{test_name}() {{\n  assert_doc_sample_opens({file_name:?});\n}}\n\n"
      ));
      continue;
    }

    if !is_round_trip_supported(&file_name) {
      generated.push_str(&format!(
        "#[test]\nfn open_{test_name}() {{\n  assert_doc_sample_opens({file_name:?});\n}}\n\n"
      ));
      continue;
    }

    if file_name == "Strict01.docx" {
      generated.push_str("#[cfg(feature = \"strict\")]\n");
    }
    if file_name == "AnnotationRef.docx" {
      generated.push_str("#[cfg(feature = \"strict\")]\n");
    }
    if file_name == "HelloWorld.docx" || file_name == "Youtube.xlsx" {
      generated.push_str("#[cfg(feature = \"microsoft365\")]\n");
    }

    generated.push_str(&format!(
      "#[test]\nfn round_trip_{test_name}() {{\n  assert_doc_sample_round_trip({file_name:?});\n}}\n\n"
    ));
  }

  fs::write(out_file, generated).expect("write generated doc sample tests");
}

fn is_open_failure(file_name: &str) -> bool {
  matches!(
    file_name,
    "5Errors.docx"
      | "Of16-09-UnknownElement.docx"
      | "UnknownElement.docx"
      | "complex0.docx"
      | "complex2010.docx"
  )
}

fn is_round_trip_supported(file_name: &str) -> bool {
  matches!(
    file_name,
    "BadDocProps.docx"
      | "AnnotationRef.docx"
      | "Comments.docx"
      | "Comments.xlsx"
      | "Data-Bound-Content-Controls.docx"
      | "HelloWorld.docx"
      | "Hyperlink.docx"
      | "Presentation.pptx"
      | "Presentation.potx"
      | "autosave.pptx"
      | "Document.dotx"
      | "Spreadsheet.xltx"
      | "vmldrawingroot.xlsx"
      | "DocProps.docx"
      | "EmptyRelationshipElement.docx"
      | "InvalidDocPropsct.docx"
      | "MoreDocProps.docx"
      | "NoDocProps.docx"
      | "Plain.docx"
      | "Revision_NameCommentChange.xlsx"
  )
}

fn is_valid_open_only(file_name: &str) -> bool {
  matches!(
    file_name,
    "Algn_tab_TabAlignment.pptx"
      | "MCExecl.xlsx"
      | "Of16-10-SymEx.docx"
      | "3dtestdash.pptx"
      | "3dtestdot.pptx"
      | "Complex01.docx"
      | "Complex01.xlsx"
      | "Document.docx"
      | "Dickinson_Sample_Slides.pptx"
      | "demo.docx"
      | "Notes.docx"
      | "animation.pptx"
      | "basicspreadsheet.xlsx"
      | "excel14.xlsx"
      | "extlst.xlsx"
      | "HelloO14.docx"
      | "mailmerge.docx"
      | "malformed_uri.xlsx"
      | "malformed_uri_long.xlsx"
      | "May_12_04.docx"
      | "mcdoc.docx"
      | "mcinleaf.docx"
      | "mcppt.pptx"
      | "mediareference.pptx"
      | "missingcalcchainpart.xlsx"
      | "o09_Performance_typical.pptx"
      | "Products.xlsx"
      | "simpleSdt.docx"
      | "Spreadsheet.xlsx"
      | "svg.docx"
      | "Youtube.xlsx"
      | "Of16-01.docx"
      | "Of16-02.docx"
      | "Of16-03.docx"
      | "Of16-04.docx"
      | "Of16-05.docx"
      | "Of16-06.docx"
      | "Of16-07.docx"
      | "Of16-08.docx"
      | "Of16-01.pptx"
      | "Of16-02.pptx"
      | "Of16-03.pptx"
  )
}

fn slugify(input: &str) -> String {
  let mut out = String::new();
  let mut prev_underscore = false;

  for ch in input.chars() {
    if ch.is_ascii_alphanumeric() {
      out.push(ch.to_ascii_lowercase());
      prev_underscore = false;
    } else if !prev_underscore {
      out.push('_');
      prev_underscore = true;
    }
  }

  while out.starts_with('_') {
    out.remove(0);
  }
  while out.ends_with('_') {
    out.pop();
  }

  if out.is_empty() {
    out.push_str("sample");
  }

  if out.chars().next().is_some_and(|ch| ch.is_ascii_digit()) {
    out.insert_str(0, "sample_");
  }

  out
}
