use std::{
  collections::BTreeMap,
  env, fs,
  path::{Path, PathBuf},
};

fn main() {
  let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("missing manifest dir"));
  let workspace_dir = manifest_dir
    .parent()
    .and_then(Path::parent)
    .expect("manifest dir should be under crates/ooxmlsdk-test");
  let test_data_dir = workspace_dir.join("test-data/ooxmlsdk-test");
  let upstream_fixtures_dir = test_data_dir.join("Open-XML-SDK");
  let libreoffice_dir = test_data_dir.join("libreoffice");
  let specs_dir = test_data_dir.join("specs");
  let misc_dir = test_data_dir.join("misc");
  let out_dir = PathBuf::from(env::var("OUT_DIR").expect("missing OUT_DIR"));
  let out_file = out_dir.join("doc_samples_tests.rs");
  let float_rules_file = out_dir.join("doc_samples_float_rules.rs");

  println!("cargo:rerun-if-changed={}", test_data_dir.display());
  println!("cargo:rerun-if-changed={}", upstream_fixtures_dir.display());
  println!("cargo:rerun-if-changed={}", libreoffice_dir.display());

  write_float_rules(workspace_dir, &float_rules_file);

  let samples = collect_doc_files(&upstream_fixtures_dir, &upstream_fixtures_dir);
  let mut test_data_files = collect_doc_files(&libreoffice_dir, &test_data_dir);
  test_data_files.extend(collect_doc_files(&specs_dir, &test_data_dir));
  test_data_files.extend(collect_doc_files(&misc_dir, &test_data_dir));
  test_data_files.sort();

  let mut generated = String::from("// @generated by build.rs\n\n");
  for file_name in samples {
    let slug = slugify(&file_name);
    let test_name = format!("doc_sample_{slug}");
    let version_cfg = version_cfg_attr(&file_name);

    if is_invalid(&file_name) {
      if !version_cfg.is_empty() {
        generated.push_str(&version_cfg);
      }
      generated.push_str(&format!(
        "#[test]\nfn invalid_{test_name}() {{\n  assert_doc_sample_invalid({file_name:?});\n}}\n\n"
      ));
      continue;
    }

    if is_valid_open_only(&file_name) {
      if !version_cfg.is_empty() {
        generated.push_str(&version_cfg);
      }
      generated.push_str(&format!(
        "#[test]\nfn open_valid_{test_name}() {{\n  assert_doc_sample_opens({file_name:?});\n}}\n\n"
      ));
      continue;
    }

    if !is_round_trip_supported(&file_name) {
      if !version_cfg.is_empty() {
        generated.push_str(&version_cfg);
      }
      generated.push_str(&format!(
        "#[test]\nfn open_{test_name}() {{\n  assert_doc_sample_opens({file_name:?});\n}}\n\n"
      ));
      continue;
    }

    if !version_cfg.is_empty() {
      generated.push_str(&version_cfg);
    }

    generated.push_str(&format!(
      "#[test]\nfn round_trip_{test_name}() {{\n  assert_doc_sample_round_trip({file_name:?});\n}}\n\n"
    ));
  }

  for file_name in test_data_files {
    let slug = slugify(&file_name);
    let test_name = format!("test_data_{slug}");

    if is_invalid(&file_name) {
      generated.push_str(&format!(
        "#[test]\nfn invalid_{test_name}() {{\n  assert_test_data_invalid({file_name:?});\n}}\n\n"
      ));
      continue;
    }

    if is_test_data_open_only(&file_name) {
      generated.push_str(&format!(
        "#[test]\nfn open_valid_{test_name}() {{\n  assert_test_data_opens({file_name:?});\n}}\n\n"
      ));
      continue;
    }

    generated.push_str(&format!(
      "#[test]\nfn round_trip_{test_name}() {{\n  assert_test_data_round_trip({file_name:?});\n}}\n\n"
    ));
  }

  fs::write(out_file, generated).expect("write generated fixture tests");
}

fn collect_doc_files(root: &Path, rel_root: &Path) -> Vec<String> {
  if !root.exists() {
    return Vec::new();
  }

  let mut files = Vec::new();
  collect_doc_files_recursive(root, rel_root, &mut files);
  files.sort();
  files
}

fn collect_doc_files_recursive(dir: &Path, rel_root: &Path, files: &mut Vec<String>) {
  for entry in fs::read_dir(dir).expect("read doc file dir") {
    let entry = entry.expect("read doc file entry");
    let path = entry.path();

    if path.is_dir() {
      println!("cargo:rerun-if-changed={}", path.display());
      collect_doc_files_recursive(&path, rel_root, files);
      continue;
    }

    if path.is_file() && is_supported_document_path(&path) {
      println!("cargo:rerun-if-changed={}", path.display());
      files.push(
        path
          .strip_prefix(rel_root)
          .unwrap_or(&path)
          .to_string_lossy()
          .replace('\\', "/"),
      );
    }
  }
}

fn is_supported_document_path(path: &Path) -> bool {
  matches!(
    path.extension().and_then(|ext| ext.to_str()),
    Some(
      "docx"
        | "dotx"
        | "docm"
        | "dotm"
        | "xlsx"
        | "xltx"
        | "xlsm"
        | "xltm"
        | "pptx"
        | "potx"
        | "pptm"
        | "potm"
    )
  )
}

fn is_invalid(file_name: &str) -> bool {
  matches!(
    file_name,
    "Strict01.docx" | "encrypted_pptx.pptx" | "libreoffice/word/strict-lockedcanvas.docx"
  )
}

fn is_round_trip_supported(file_name: &str) -> bool {
  let _ = file_name;
  true
}

fn is_valid_open_only(file_name: &str) -> bool {
  matches!(file_name, "5Errors.docx" | "simpleSdt.docx")
}

fn is_test_data_open_only(file_name: &str) -> bool {
  matches!(
    file_name,
    "libreoffice/word/comment-annotationref.docx"
      | "libreoffice/presentation/chart-theme-override.pptx"
      | "libreoffice/presentation/import-characters.pptx"
      | "libreoffice/presentation/tdf147586.pptx"
  )
}

fn version_cfg_attr(file_name: &str) -> String {
  let _ = file_name;
  String::new()
}

fn slugify(input: &str) -> String {
  let mut out = String::new();
  let mut prev_underscore = false;

  for ch in input.chars() {
    if ch.is_ascii_alphanumeric() {
      out.push(ch.to_ascii_lowercase());
      prev_underscore = false;
    } else if !prev_underscore {
      out.push('_');
      prev_underscore = true;
    }
  }

  while out.starts_with('_') {
    out.remove(0);
  }
  while out.ends_with('_') {
    out.pop();
  }

  if out.is_empty() {
    out.push_str("sample");
  }

  if out.chars().next().is_some_and(|ch| ch.is_ascii_digit()) {
    out.insert_str(0, "sample_");
  }

  out
}

#[derive(Clone, Copy)]
enum GeneratedFloatKind {
  Single,
  Double,
}

impl GeneratedFloatKind {
  fn generated_name(self) -> &'static str {
    match self {
      Self::Single => "SchemaFloatKind::Single",
      Self::Double => "SchemaFloatKind::Double",
    }
  }
}

fn write_float_rules(workspace_dir: &Path, out_file: &Path) {
  let namespace_file = workspace_dir.join("sdk_data/namespaces.json");
  println!("cargo:rerun-if-changed={}", namespace_file.display());
  let namespaces = read_namespaces(&namespace_file);

  let schemas_dir = workspace_dir.join("sdk_data/schemas");
  println!("cargo:rerun-if-changed={}", schemas_dir.display());

  let mut attr_kinds = BTreeMap::new();
  let mut text_kinds = BTreeMap::new();
  for entry in fs::read_dir(&schemas_dir).expect("read sdk_data schema dir") {
    let entry = entry.expect("read generated schema entry");
    let path = entry.path();
    if path.extension().and_then(|ext| ext.to_str()) != Some("json") {
      continue;
    }
    println!("cargo:rerun-if-changed={}", path.display());
    collect_schema_float_rules_from_data(&path, &namespaces, &mut attr_kinds, &mut text_kinds);
  }

  let mut generated = String::from("// @generated by build.rs\n\n");
  generated.push_str(
    "fn schema_float_kind_for_attr(element_name: &str, attr_name: &str) -> Option<SchemaFloatKind> {\n",
  );
  generated.push_str("  match (element_name, attr_name) {\n");
  for ((element_name, attr_name), kind) in attr_kinds {
    generated.push_str("    (");
    generated.push_str(&format!("{element_name:?}, {attr_name:?}"));
    generated.push_str(") => Some(");
    generated.push_str(kind.generated_name());
    generated.push_str("),\n");
  }
  generated.push_str("    _ => None,\n");
  generated.push_str("  }\n");
  generated.push_str("}\n\n");
  generated
    .push_str("fn schema_float_kind_for_text(element_name: &str) -> Option<SchemaFloatKind> {\n");
  generated.push_str("  match element_name {\n");
  for (element_name, kind) in text_kinds {
    generated.push_str("    ");
    generated.push_str(&format!(
      "{element_name:?} => Some({}),\n",
      kind.generated_name()
    ));
  }
  generated.push_str("    _ => None,\n");
  generated.push_str("  }\n");
  generated.push_str("}\n");

  fs::write(out_file, generated).expect("write generated float rules");
}

fn read_namespaces(path: &Path) -> BTreeMap<String, String> {
  let raw = fs::read_to_string(path).expect("read namespaces.json");
  let values: Vec<serde_json::Value> = serde_json::from_str(&raw).expect("parse namespaces.json");
  values
    .into_iter()
    .filter_map(|value| {
      let prefix = value.get("Prefix")?.as_str()?.to_string();
      let uri = value.get("Uri")?.as_str()?.to_string();
      Some((prefix, uri))
    })
    .collect()
}

fn collect_schema_float_rules_from_data(
  path: &Path,
  namespaces: &BTreeMap<String, String>,
  attr_kinds: &mut BTreeMap<(String, String), GeneratedFloatKind>,
  text_kinds: &mut BTreeMap<String, GeneratedFloatKind>,
) {
  let raw = fs::read_to_string(path).expect("read sdk_data schema");
  let schema: serde_json::Value = serde_json::from_str(&raw).expect("parse sdk_data schema");
  let Some(types) = schema.get("Types").and_then(serde_json::Value::as_array) else {
    return;
  };
  let type_by_name = types
    .iter()
    .filter_map(|ty| Some((ty.get("RustName")?.as_str()?, ty)))
    .collect::<BTreeMap<_, _>>();

  for ty in types {
    let Some(element_qname) = ty.get("XmlQName").and_then(serde_json::Value::as_str) else {
      continue;
    };
    let element_name = expand_generated_qname(element_qname, namespaces, false);
    collect_type_float_attrs(ty, &type_by_name, namespaces, &element_name, attr_kinds);
    collect_type_float_text(ty, &type_by_name, &element_name, text_kinds);
  }
}

fn collect_type_float_attrs(
  ty: &serde_json::Value,
  type_by_name: &BTreeMap<&str, &serde_json::Value>,
  namespaces: &BTreeMap<String, String>,
  element_name: &str,
  attr_kinds: &mut BTreeMap<(String, String), GeneratedFloatKind>,
) {
  if let Some(base_name) = ty.get("BaseRustName").and_then(serde_json::Value::as_str)
    && let Some(base_ty) = type_by_name.get(base_name)
  {
    collect_type_float_attrs(base_ty, type_by_name, namespaces, element_name, attr_kinds);
  }

  let Some(members) = ty.get("Members").and_then(serde_json::Value::as_array) else {
    return;
  };
  for member in members {
    let Some(field) = member.get("Field") else {
      continue;
    };
    let Some(type_ref) = field
      .get("TypeRef")
      .and_then(|type_ref| type_ref.get("RustType"))
      .and_then(serde_json::Value::as_str)
    else {
      continue;
    };
    let Some(kind) = float_kind(type_ref) else {
      continue;
    };
    let Some(attr_qname) = field
      .get("Wire")
      .and_then(|wire| wire.get("Attribute"))
      .and_then(|attr| attr.get("QName"))
      .and_then(serde_json::Value::as_str)
    else {
      continue;
    };
    attr_kinds.insert(
      (
        element_name.to_string(),
        expand_generated_qname(attr_qname, namespaces, true),
      ),
      kind,
    );
  }
}

fn collect_type_float_text(
  ty: &serde_json::Value,
  type_by_name: &BTreeMap<&str, &serde_json::Value>,
  element_name: &str,
  text_kinds: &mut BTreeMap<String, GeneratedFloatKind>,
) {
  if let Some(base_name) = ty.get("BaseRustName").and_then(serde_json::Value::as_str)
    && let Some(base_ty) = type_by_name.get(base_name)
  {
    collect_type_float_text(base_ty, type_by_name, element_name, text_kinds);
  }

  let Some(type_name) = ty
    .get("XmlContent")
    .and_then(|content| content.get("RustType"))
    .and_then(serde_json::Value::as_str)
  else {
    return;
  };
  let Some(kind) = float_kind(type_name) else {
    return;
  };
  text_kinds.insert(element_name.to_string(), kind);
}

fn float_kind(type_name: &str) -> Option<GeneratedFloatKind> {
  Some(match type_name {
    "SingleValue" => GeneratedFloatKind::Single,
    "DoubleValue" => GeneratedFloatKind::Double,
    _ => return None,
  })
}

fn expand_generated_qname(
  qname: &str,
  namespaces: &BTreeMap<String, String>,
  is_attr: bool,
) -> String {
  let element_qname = qname.rsplit('/').next().unwrap_or(qname);
  let Some((prefix, local_name)) = element_qname.split_once(':') else {
    return element_qname.to_string();
  };
  if prefix.is_empty() && is_attr {
    return local_name.to_string();
  }
  let Some(uri) = namespaces.get(prefix) else {
    return element_qname.to_string();
  };
  format!("{{{uri}}}{local_name}")
}
