[package]
name = "ooxmlsdk"
version.workspace = true
edition.workspace = true

[dependencies]
quick-xml = { workspace = true }
thiserror = { workspace = true }

[build-dependencies]
ooxmlsdk-build = { workspace = true }
