[package]
name = "ooxmlsdk"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
documentation.workspace = true
description.workspace = true
keywords.workspace = true
categories.workspace = true
readme.workspace = true

[features]
# default = ["parts", "validators"]
# schemas = ["ooxmlsdk-build/schemas"]
# serializers = ["schemas", "ooxmlsdk-build/serializers"]
# deserializers = ["schemas", "ooxmlsdk-build/deserializers"]
# parts = [
#   "schemas",
#   "serializers",
#   "deserializers",
#   "packages",
#   "ooxmlsdk-build/parts",
#   "dep:zip",
# ]
# validators = ["schemas", "ooxmlsdk-build/validators"]
# packages = ["ooxmlsdk-build/packages"]

[dependencies]
quick-xml = { workspace = true }
thiserror = { workspace = true }
zip = { workspace = true, optional = true }

[build-dependencies]
ooxmlsdk-build = { workspace = true }
