//! Regenerates the checked-in DrawingML preset geometry tables.
//!
//! Run from the implementation repository root:
//! `cargo run -p ooxmlsdk-layout --example generate_preset_shape_data -- \
//!   ../core/oox/source/drawingml/customshapes/presetShapeDefinitions.xml`

use std::fmt::Write as _;
use std::{env, fs};

use ooxmlsdk::schemas::schemas_openxmlformats_org_drawingml_2006_main as a;

const DRAWINGML_NAMESPACE: &str = "http://schemas.openxmlformats.org/drawingml/2006/main";
const DEFAULT_INPUT: &str = "../core/oox/source/drawingml/customshapes/presetShapeDefinitions.xml";
const OUTPUT: &str = "crates/ooxmlsdk-layout/src/common/drawingml_preset_data_generated.rs";

fn main() {
  let input = env::args().nth(1).unwrap_or_else(|| DEFAULT_INPUT.into());
  let source =
    fs::read_to_string(&input).unwrap_or_else(|error| panic!("failed to read {input}: {error}"));
  let definitions = parse_definitions(&source);
  let mut output = String::from(
    "// @generated by examples/generate_preset_shape_data.rs; do not edit.\n\
     use super::drawingml_preset_data::{Definition, GuideDef, PathCommandDef, PathDef, PointDef};\n\
     use ooxmlsdk::schemas::schemas_openxmlformats_org_drawingml_2006_main as a;\n\n",
  );
  let mut arms = String::new();
  let mut path_count = 0;
  let mut stroke_only_count = 0;
  let mut fill_only_count = 0;
  for (preset, geometry) in &definitions {
    let variant = format!("{preset:?}");
    let symbol = screaming_snake_case(&variant);
    write_guides(
      &mut output,
      &format!("{symbol}_ADJUSTMENTS"),
      geometry
        .adjust_value_list
        .as_ref()
        .map(|list| list.shape_guide.as_slice())
        .unwrap_or_default(),
    );
    write_guides(
      &mut output,
      &format!("{symbol}_GUIDES"),
      geometry
        .shape_guide_list
        .as_ref()
        .map(|list| list.shape_guide.as_slice())
        .unwrap_or_default(),
    );
    for (index, path) in geometry.path_list.path.iter().enumerate() {
      path_count += 1;
      let filled = !matches!(path.fill, Some(a::PathFillModeValues::None));
      let stroked = path.stroke.as_ref().is_none_or(|value| value.as_bool());
      stroke_only_count += usize::from(!filled && stroked);
      fill_only_count += usize::from(filled && !stroked);
      write_commands(
        &mut output,
        &format!("{symbol}_PATH_{index}_COMMANDS"),
        &path.path_choice,
      );
    }
    writeln!(output, "const {symbol}_PATHS: &[PathDef] = &[").unwrap();
    for (index, path) in geometry.path_list.path.iter().enumerate() {
      writeln!(
        output,
        "  PathDef {{ width: {}, height: {}, fill: {}, stroke: {}, extrusion_allowed: {}, commands: {symbol}_PATH_{index}_COMMANDS }},",
        option_display(path.width.map(|value| value.to_emu().to_string())),
        option_display(path.height.map(|value| value.to_emu().to_string())),
        option_enum(path.fill),
        option_bool(path.stroke.as_ref().map(|value| value.as_bool())),
        option_bool(path.extrusion_ok.as_ref().map(|value| value.as_bool())),
      )
      .unwrap();
    }
    writeln!(output, "];").unwrap();
    writeln!(
      output,
      "const {symbol}: Definition = Definition {{ adjustments: {symbol}_ADJUSTMENTS, guides: {symbol}_GUIDES, paths: {symbol}_PATHS }};\n"
    )
    .unwrap();
    writeln!(arms, "    a::ShapeTypeValues::{variant} => &{symbol},").unwrap();
  }
  writeln!(
    output,
    "pub(super) const DEFINITION_COUNT: usize = {};\n\
     pub(super) const PATH_COUNT: usize = {path_count};\n\
     pub(super) const STROKE_ONLY_PATH_COUNT: usize = {stroke_only_count};\n\
     pub(super) const FILL_ONLY_PATH_COUNT: usize = {fill_only_count};\n\n\
     pub(super) fn definition(preset: a::ShapeTypeValues) -> &'static Definition {{\n\
     match preset {{\n{arms}  }}\n}}\n",
    definitions.len()
  )
  .unwrap();
  fs::write(OUTPUT, output).unwrap_or_else(|error| panic!("failed to write {OUTPUT}: {error}"));
}

fn parse_definitions(source: &str) -> Vec<(a::ShapeTypeValues, a::CustomGeometry)> {
  let mut definitions = Vec::new();
  let mut lines = source.lines();
  while let Some(line) = lines.next() {
    let Some(name) = line
      .strip_prefix("  <")
      .and_then(|line| line.strip_suffix('>'))
      .filter(|name| {
        !name.starts_with('/') && name.bytes().all(|byte| byte.is_ascii_alphanumeric())
      })
    else {
      continue;
    };
    let closing_tag = format!("  </{name}>");
    let mut body = String::new();
    for line in lines.by_ref() {
      if line == closing_tag {
        break;
      }
      body.push_str(line);
      body.push('\n');
    }
    let preset = name.parse::<a::ShapeTypeValues>().unwrap();
    let xml = format!(r#"<a:custGeom xmlns:a="{DRAWINGML_NAMESPACE}">{body}</a:custGeom>"#);
    definitions.push((preset, xml.parse::<a::CustomGeometry>().unwrap()));
  }
  definitions
}

fn write_guides(output: &mut String, symbol: &str, guides: &[a::ShapeGuide]) {
  writeln!(output, "const {symbol}: &[GuideDef] = &[").unwrap();
  for guide in guides {
    writeln!(
      output,
      "  GuideDef {{ name: {:?}, formula: {:?} }},",
      guide.name, guide.formula
    )
    .unwrap();
  }
  writeln!(output, "];").unwrap();
}

fn write_commands(output: &mut String, symbol: &str, commands: &[a::PathChoice]) {
  writeln!(output, "const {symbol}: &[PathCommandDef] = &[").unwrap();
  for command in commands {
    match command {
      a::PathChoice::CloseShapePath => {
        writeln!(output, "  PathCommandDef::Close,").unwrap();
      }
      a::PathChoice::MoveTo(command) => {
        write_point_command(output, "MoveTo", &command.point);
      }
      a::PathChoice::LineTo(command) => {
        write_point_command(output, "LineTo", &command.point);
      }
      a::PathChoice::ArcTo(command) => {
        writeln!(
          output,
          "  PathCommandDef::ArcTo {{ width_radius: {:?}, height_radius: {:?}, start_angle: {:?}, sweep_angle: {:?} }},",
          command.width_radius, command.height_radius, command.start_angle, command.swing_angle
        )
        .unwrap();
      }
      a::PathChoice::QuadraticBezierCurveTo(command) => {
        assert_eq!(command.point.len(), 2);
        write_curve_command(output, "QuadraticTo", &command.point);
      }
      a::PathChoice::CubicBezierCurveTo(command) => {
        assert_eq!(command.point.len(), 3);
        write_curve_command(output, "CubicTo", &command.point);
      }
    }
  }
  writeln!(output, "];").unwrap();
}

fn write_point_command(output: &mut String, variant: &str, point: &a::Point) {
  writeln!(
    output,
    "  PathCommandDef::{variant}(PointDef {{ x: {:?}, y: {:?} }}),",
    point.x, point.y
  )
  .unwrap();
}

fn write_curve_command(output: &mut String, variant: &str, points: &[a::Point]) {
  write!(output, "  PathCommandDef::{variant}(&[").unwrap();
  for point in points {
    write!(output, "PointDef {{ x: {:?}, y: {:?} }},", point.x, point.y).unwrap();
  }
  writeln!(output, "]),").unwrap();
}

fn option_display(value: Option<String>) -> String {
  value.map_or_else(|| "None".into(), |value| format!("Some({value:?})"))
}

fn option_bool(value: Option<bool>) -> String {
  value.map_or_else(|| "None".into(), |value| format!("Some({value})"))
}

fn option_enum(value: Option<a::PathFillModeValues>) -> String {
  value.map_or_else(
    || "None".into(),
    |value| format!("Some(a::PathFillModeValues::{value:?})"),
  )
}

fn screaming_snake_case(value: &str) -> String {
  let mut output = String::with_capacity(value.len());
  for (index, character) in value.chars().enumerate() {
    if character.is_ascii_uppercase() && index > 0 {
      output.push('_');
    }
    output.push(character.to_ascii_uppercase());
  }
  output
}
