// @generated by examples/generate_preset_shape_data.rs; do not edit.
use super::drawingml_preset_data::{Definition, GuideDef, PathCommandDef, PathDef, PointDef};
use ooxmlsdk::schemas::schemas_openxmlformats_org_drawingml_2006_main as a;

const TEXT_ARCH_DOWN_ADJUSTMENTS: &[GuideDef] = &[GuideDef {
  name: "adj",
  formula: "val 0",
}];
const TEXT_ARCH_DOWN_GUIDES: &[GuideDef] = &[
  GuideDef {
    name: "adval",
    formula: "pin 0 adj 21599999",
  },
  GuideDef {
    name: "v1",
    formula: "+- 10800000 0 adval",
  },
  GuideDef {
    name: "v2",
    formula: "+- 32400000 0 adval",
  },
  GuideDef {
    name: "nv1",
    formula: "+- 0 0 v1",
  },
  GuideDef {
    name: "stAng",
    formula: "?: nv1 v2 v1",
  },
  GuideDef {
    name: "w1",
    formula: "+- 5400000 0 adval",
  },
  GuideDef {
    name: "w2",
    formula: "+- 16200000 0 adval",
  },
  GuideDef {
    name: "d1",
    formula: "+- adval 0 stAng",
  },
  GuideDef {
    name: "d2",
    formula: "+- d1 0 21600000",
  },
  GuideDef {
    name: "v3",
    formula: "+- 0 0 10800000",
  },
  GuideDef {
    name: "c2",
    formula: "?: w2 d1 d2",
  },
  GuideDef {
    name: "c1",
    formula: "?: v1 d2 c2",
  },
  GuideDef {
    name: "c0",
    formula: "?: w1 d1 c1",
  },
  GuideDef {
    name: "swAng",
    formula: "?: stAng c0 v3",
  },
  GuideDef {
    name: "wt1",
    formula: "sin wd2 adj",
  },
  GuideDef {
    name: "ht1",
    formula: "cos hd2 adj",
  },
  GuideDef {
    name: "dx1",
    formula: "cat2 wd2 ht1 wt1",
  },
  GuideDef {
    name: "dy1",
    formula: "sat2 hd2 ht1 wt1",
  },
  GuideDef {
    name: "x1",
    formula: "+- hc dx1 0",
  },
  GuideDef {
    name: "y1",
    formula: "+- vc dy1 0",
  },
  GuideDef {
    name: "wt2",
    formula: "sin wd2 stAng",
  },
  GuideDef {
    name: "ht2",
    formula: "cos hd2 stAng",
  },
  GuideDef {
    name: "dx2",
    formula: "cat2 wd2 ht2 wt2",
  },
  GuideDef {
    name: "dy2",
    formula: "sat2 hd2 ht2 wt2",
  },
  GuideDef {
    name: "x2",
    formula: "+- hc dx2 0",
  },
  GuideDef {
    name: "y2",
    formula: "+- vc dy2 0",
  },
];
const TEXT_ARCH_DOWN_PATH_0_COMMANDS: &[PathCommandDef] = &[
  PathCommandDef::MoveTo(PointDef { x: "x2", y: "y2" }),
  PathCommandDef::ArcTo {
    width_radius: "wd2",
    height_radius: "hd2",
    start_angle: "stAng",
    sweep_angle: "swAng",
  },
];
const TEXT_ARCH_DOWN_PATHS: &[PathDef] = &[PathDef {
  width: None,
  height: None,
  fill: None,
  stroke: None,
  extrusion_allowed: None,
  commands: TEXT_ARCH_DOWN_PATH_0_COMMANDS,
}];
const TEXT_ARCH_DOWN: Definition = Definition {
  adjustments: TEXT_ARCH_DOWN_ADJUSTMENTS,
  guides: TEXT_ARCH_DOWN_GUIDES,
  paths: TEXT_ARCH_DOWN_PATHS,
};

const TEXT_ARCH_DOWN_POUR_ADJUSTMENTS: &[GuideDef] = &[
  GuideDef {
    name: "adj1",
    formula: "val 0",
  },
  GuideDef {
    name: "adj2",
    formula: "val 25000",
  },
];
const TEXT_ARCH_DOWN_POUR_GUIDES: &[GuideDef] = &[
  GuideDef {
    name: "adval",
    formula: "pin 0 adj1 21599999",
  },
  GuideDef {
    name: "v1",
    formula: "+- 10800000 0 adval",
  },
  GuideDef {
    name: "v2",
    formula: "+- 32400000 0 adval",
  },
  GuideDef {
    name: "nv1",
    formula: "+- 0 0 v1",
  },
  GuideDef {
    name: "stAng",
    formula: "?: nv1 v2 v1",
  },
  GuideDef {
    name: "w1",
    formula: "+- 5400000 0 adval",
  },
  GuideDef {
    name: "w2",
    formula: "+- 16200000 0 adval",
  },
  GuideDef {
    name: "d1",
    formula: "+- adval 0 stAng",
  },
  GuideDef {
    name: "d2",
    formula: "+- d1 0 21600000",
  },
  GuideDef {
    name: "v3",
    formula: "+- 0 0 10800000",
  },
  GuideDef {
    name: "c2",
    formula: "?: w2 d1 d2",
  },
  GuideDef {
    name: "c1",
    formula: "?: v1 d2 c2",
  },
  GuideDef {
    name: "c0",
    formula: "?: w1 d1 c1",
  },
  GuideDef {
    name: "swAng",
    formula: "?: stAng c0 v3",
  },
  GuideDef {
    name: "wt1",
    formula: "sin wd2 stAng",
  },
  GuideDef {
    name: "ht1",
    formula: "cos hd2 stAng",
  },
  GuideDef {
    name: "dx1",
    formula: "cat2 wd2 ht1 wt1",
  },
  GuideDef {
    name: "dy1",
    formula: "sat2 hd2 ht1 wt1",
  },
  GuideDef {
    name: "x1",
    formula: "+- hc dx1 0",
  },
  GuideDef {
    name: "y1",
    formula: "+- vc dy1 0",
  },
  GuideDef {
    name: "adval2",
    formula: "pin 0 adj2 99000",
  },
  GuideDef {
    name: "ratio",
    formula: "*/ adval2 1 100000",
  },
  GuideDef {
    name: "iwd2",
    formula: "*/ wd2 ratio 1",
  },
  GuideDef {
    name: "ihd2",
    formula: "*/ hd2 ratio 1",
  },
  GuideDef {
    name: "wt2",
    formula: "sin iwd2 adval",
  },
  GuideDef {
    name: "ht2",
    formula: "cos ihd2 adval",
  },
  GuideDef {
    name: "dx2",
    formula: "cat2 iwd2 ht2 wt2",
  },
  GuideDef {
    name: "dy2",
    formula: "sat2 ihd2 ht2 wt2",
  },
  GuideDef {
    name: "x2",
    formula: "+- hc dx2 0",
  },
  GuideDef {
    name: "y2",
    formula: "+- vc dy2 0",
  },
  GuideDef {
    name: "wt3",
    formula: "sin iwd2 stAng",
  },
  GuideDef {
    name: "ht3",
    formula: "cos ihd2 stAng",
  },
  GuideDef {
    name: "dx3",
    formula: "cat2 iwd2 ht3 wt3",
  },
  GuideDef {
    name: "dy3",
    formula: "sat2 ihd2 ht3 wt3",
  },
  GuideDef {
    name: "x3",
    formula: "+- hc dx3 0",
  },
  GuideDef {
    name: "y3",
    formula: "+- vc dy3 0",
  },
];
const TEXT_ARCH_DOWN_POUR_PATH_0_COMMANDS: &[PathCommandDef] = &[
  PathCommandDef::MoveTo(PointDef { x: "x3", y: "y3" }),
  PathCommandDef::ArcTo {
    width_radius: "iwd2",
    height_radius: "ihd2",
    start_angle: "stAng",
    sweep_angle: "swAng",
  },
];
const TEXT_ARCH_DOWN_POUR_PATH_1_COMMANDS: &[PathCommandDef] = &[
  PathCommandDef::MoveTo(PointDef { x: "x1", y: "y1" }),
  PathCommandDef::ArcTo {
    width_radius: "wd2",
    height_radius: "hd2",
    start_angle: "stAng",
    sweep_angle: "swAng",
  },
];
const TEXT_ARCH_DOWN_POUR_PATHS: &[PathDef] = &[
  PathDef {
    width: None,
    height: None,
    fill: None,
    stroke: None,
    extrusion_allowed: None,
    commands: TEXT_ARCH_DOWN_POUR_PATH_0_COMMANDS,
  },
  PathDef {
    width: None,
    height: None,
    fill: None,
    stroke: None,
    extrusion_allowed: None,
    commands: TEXT_ARCH_DOWN_POUR_PATH_1_COMMANDS,
  },
];
const TEXT_ARCH_DOWN_POUR: Definition = Definition {
  adjustments: TEXT_ARCH_DOWN_POUR_ADJUSTMENTS,
  guides: TEXT_ARCH_DOWN_POUR_GUIDES,
  paths: TEXT_ARCH_DOWN_POUR_PATHS,
};

const TEXT_ARCH_UP_ADJUSTMENTS: &[GuideDef] = &[GuideDef {
  name: "adj",
  formula: "val cd2",
}];
const TEXT_ARCH_UP_GUIDES: &[GuideDef] = &[
  GuideDef {
    name: "adval",
    formula: "pin 0 adj 21599999",
  },
  GuideDef {
    name: "v1",
    formula: "+- 10800000 0 adval",
  },
  GuideDef {
    name: "v2",
    formula: "+- 32400000 0 adval",
  },
  GuideDef {
    name: "end",
    formula: "?: v1 v1 v2",
  },
  GuideDef {
    name: "w1",
    formula: "+- 5400000 0 adval",
  },
  GuideDef {
    name: "w2",
    formula: "+- 16200000 0 adval",
  },
  GuideDef {
    name: "d1",
    formula: "+- end 0 adval",
  },
  GuideDef {
    name: "d2",
    formula: "+- 21600000 d1 0",
  },
  GuideDef {
    name: "c2",
    formula: "?: w2 d1 d2",
  },
  GuideDef {
    name: "c1",
    formula: "?: v1 d2 c2",
  },
  GuideDef {
    name: "swAng",
    formula: "?: w1 d1 c1",
  },
  GuideDef {
    name: "wt1",
    formula: "sin wd2 adj",
  },
  GuideDef {
    name: "ht1",
    formula: "cos hd2 adj",
  },
  GuideDef {
    name: "dx1",
    formula: "cat2 wd2 ht1 wt1",
  },
  GuideDef {
    name: "dy1",
    formula: "sat2 hd2 ht1 wt1",
  },
  GuideDef {
    name: "x1",
    formula: "+- hc dx1 0",
  },
  GuideDef {
    name: "y1",
    formula: "+- vc dy1 0",
  },
];
const TEXT_ARCH_UP_PATH_0_COMMANDS: &[PathCommandDef] = &[
  PathCommandDef::MoveTo(PointDef { x: "x1", y: "y1" }),
  PathCommandDef::ArcTo {
    width_radius: "wd2",
    height_radius: "hd2",
    start_angle: "adval",
    sweep_angle: "swAng",
  },
];
const TEXT_ARCH_UP_PATHS: &[PathDef] = &[PathDef {
  width: None,
  height: None,
  fill: None,
  stroke: None,
  extrusion_allowed: None,
  commands: TEXT_ARCH_UP_PATH_0_COMMANDS,
}];
const TEXT_ARCH_UP: Definition = Definition {
  adjustments: TEXT_ARCH_UP_ADJUSTMENTS,
  guides: TEXT_ARCH_UP_GUIDES,
  paths: TEXT_ARCH_UP_PATHS,
};

const TEXT_ARCH_UP_POUR_ADJUSTMENTS: &[GuideDef] = &[
  GuideDef {
    name: "adj1",
    formula: "val cd2",
  },
  GuideDef {
    name: "adj2",
    formula: "val 50000",
  },
];
const TEXT_ARCH_UP_POUR_GUIDES: &[GuideDef] = &[
  GuideDef {
    name: "adval",
    formula: "pin 0 adj1 21599999",
  },
  GuideDef {
    name: "v1",
    formula: "+- 10800000 0 adval",
  },
  GuideDef {
    name: "v2",
    formula: "+- 32400000 0 adval",
  },
  GuideDef {
    name: "end",
    formula: "?: v1 v1 v2",
  },
  GuideDef {
    name: "w1",
    formula: "+- 5400000 0 adval",
  },
  GuideDef {
    name: "w2",
    formula: "+- 16200000 0 adval",
  },
  GuideDef {
    name: "d1",
    formula: "+- end 0 adval",
  },
  GuideDef {
    name: "d2",
    formula: "+- 21600000 d1 0",
  },
  GuideDef {
    name: "c2",
    formula: "?: w2 d1 d2",
  },
  GuideDef {
    name: "c1",
    formula: "?: v1 d2 c2",
  },
  GuideDef {
    name: "swAng",
    formula: "?: w1 d1 c1",
  },
  GuideDef {
    name: "wt1",
    formula: "sin wd2 adval",
  },
  GuideDef {
    name: "ht1",
    formula: "cos hd2 adval",
  },
  GuideDef {
    name: "dx1",
    formula: "cat2 wd2 ht1 wt1",
  },
  GuideDef {
    name: "dy1",
    formula: "sat2 hd2 ht1 wt1",
  },
  GuideDef {
    name: "x1",
    formula: "+- hc dx1 0",
  },
  GuideDef {
    name: "y1",
    formula: "+- vc dy1 0",
  },
  GuideDef {
    name: "adval2",
    formula: "pin 0 adj2 99000",
  },
  GuideDef {
    name: "ratio",
    formula: "*/ adval2 1 100000",
  },
  GuideDef {
    name: "iwd2",
    formula: "*/ wd2 ratio 1",
  },
  GuideDef {
    name: "ihd2",
    formula: "*/ hd2 ratio 1",
  },
  GuideDef {
    name: "wt2",
    formula: "sin iwd2 adval",
  },
  GuideDef {
    name: "ht2",
    formula: "cos ihd2 adval",
  },
  GuideDef {
    name: "dx2",
    formula: "cat2 iwd2 ht2 wt2",
  },
  GuideDef {
    name: "dy2",
    formula: "sat2 ihd2 ht2 wt2",
  },
  GuideDef {
    name: "x2",
    formula: "+- hc dx2 0",
  },
  GuideDef {
    name: "y2",
    formula: "+- vc dy2 0",
  },
];
const TEXT_ARCH_UP_POUR_PATH_0_COMMANDS: &[PathCommandDef] = &[
  PathCommandDef::MoveTo(PointDef { x: "x1", y: "y1" }),
  PathCommandDef::ArcTo {
    width_radius: "wd2",
    height_radius: "hd2",
    start_angle: "adval",
    sweep_angle: "swAng",
  },
];
const TEXT_ARCH_UP_POUR_PATH_1_COMMANDS: &[PathCommandDef] = &[
  PathCommandDef::MoveTo(PointDef { x: "x2", y: "y2" }),
  PathCommandDef::ArcTo {
    width_radius: "iwd2",
    height_radius: "ihd2",
    start_angle: "adval",
    sweep_angle: "swAng",
  },
];
const TEXT_ARCH_UP_POUR_PATHS: &[PathDef] = &[
  PathDef {
    width: None,
    height: None,
    fill: None,
    stroke: None,
    extrusion_allowed: None,
    commands: TEXT_ARCH_UP_POUR_PATH_0_COMMANDS,
  },
  PathDef {
    width: None,
    height: None,
    fill: None,
    stroke: None,
    extrusion_allowed: None,
    commands: TEXT_ARCH_UP_POUR_PATH_1_COMMANDS,
  },
];
const TEXT_ARCH_UP_POUR: Definition = Definition {
  adjustments: TEXT_ARCH_UP_POUR_ADJUSTMENTS,
  guides: TEXT_ARCH_UP_POUR_GUIDES,
  paths: TEXT_ARCH_UP_POUR_PATHS,
};

const TEXT_BUTTON_ADJUSTMENTS: &[GuideDef] = &[GuideDef {
  name: "adj",
  formula: "val 10800000",
}];
const TEXT_BUTTON_GUIDES: &[GuideDef] = &[
  GuideDef {
    name: "adval",
    formula: "pin 0 adj 21599999",
  },
  GuideDef {
    name: "bot",
    formula: "+- 5400000 0 adval",
  },
  GuideDef {
    name: "lef",
    formula: "+- 10800000 0 adval",
  },
  GuideDef {
    name: "top",
    formula: "+- 16200000 0 adval",
  },
  GuideDef {
    name: "rig",
    formula: "+- 21600000 0 adval",
  },
  GuideDef {
    name: "c3",
    formula: "?: top adval 0",
  },
  GuideDef {
    name: "c2",
    formula: "?: lef 10800000 c3",
  },
  GuideDef {
    name: "c1",
    formula: "?: bot rig c2",
  },
  GuideDef {
    name: "stAng",
    formula: "?: adval c1 0",
  },
  GuideDef {
    name: "w1",
    formula: "+- 21600000 0 stAng",
  },
  GuideDef {
    name: "stAngB",
    formula: "?: stAng w1 0",
  },
  GuideDef {
    name: "td1",
    formula: "*/ bot 2 1",
  },
  GuideDef {
    name: "td2",
    formula: "*/ top 2 1",
  },
  GuideDef {
    name: "ntd2",
    formula: "+- 0 0 td2",
  },
  GuideDef {
    name: "w2",
    formula: "+- 0 0 10800000",
  },
  GuideDef {
    name: "c6",
    formula: "?: top ntd2 w2",
  },
  GuideDef {
    name: "c5",
    formula: "?: lef 10800000 c6",
  },
  GuideDef {
    name: "c4",
    formula: "?: bot td1 c5",
  },
  GuideDef {
    name: "v1",
    formula: "?: adval c4 10800000",
  },
  GuideDef {
    name: "swAngT",
    formula: "+- 0 0 v1",
  },
  GuideDef {
    name: "stT",
    formula: "?: lef stAngB stAng",
  },
  GuideDef {
    name: "stB",
    formula: "?: lef stAng stAngB",
  },
  GuideDef {
    name: "swT",
    formula: "?: lef v1 swAngT",
  },
  GuideDef {
    name: "swB",
    formula: "?: lef swAngT v1",
  },
  GuideDef {
    name: "wt1",
    formula: "sin wd2 stT",
  },
  GuideDef {
    name: "ht1",
    formula: "cos hd2 stT",
  },
  GuideDef {
    name: "dx1",
    formula: "cat2 wd2 ht1 wt1",
  },
  GuideDef {
    name: "dy1",
    formula: "sat2 hd2 ht1 wt1",
  },
  GuideDef {
    name: "x1",
    formula: "+- hc dx1 0",
  },
  GuideDef {
    name: "y1",
    formula: "+- vc dy1 0",
  },
  GuideDef {
    name: "wt2",
    formula: "sin wd2 stB",
  },
  GuideDef {
    name: "ht2",
    formula: "cos hd2 stB",
  },
  GuideDef {
    name: "dx2",
    formula: "cat2 wd2 ht2 wt2",
  },
  GuideDef {
    name: "dy2",
    formula: "sat2 hd2 ht2 wt2",
  },
  GuideDef {
    name: "x2",
    formula: "+- hc dx2 0",
  },
  GuideDef {
    name: "y2",
    formula: "+- vc dy2 0",
  },
  GuideDef {
    name: "wt3",
    formula: "sin wd2 adj",
  },
  GuideDef {
    name: "ht3",
    formula: "cos hd2 adj",
  },
  GuideDef {
    name: "dx3",
    formula: "cat2 wd2 ht3 wt3",
  },
  GuideDef {
    name: "dy3",
    formula: "sat2 hd2 ht3 wt3",
  },
  GuideDef {
    name: "x3",
    formula: "+- hc dx3 0",
  },
  GuideDef {
    name: "y3",
    formula: "+- vc dy3 0",
  },
];
const TEXT_BUTTON_PATH_0_COMMANDS: &[PathCommandDef] = &[
  PathCommandDef::MoveTo(PointDef { x: "x1", y: "y1" }),
  PathCommandDef::ArcTo {
    width_radius: "wd2",
    height_radius: "hd2",
    start_angle: "stT",
    sweep_angle: "swT",
  },
];
const TEXT_BUTTON_PATH_1_COMMANDS: &[PathCommandDef] = &[
  PathCommandDef::MoveTo(PointDef { x: "l", y: "vc" }),
  PathCommandDef::LineTo(PointDef { x: "r", y: "vc" }),
];
const TEXT_BUTTON_PATH_2_COMMANDS: &[PathCommandDef] = &[
  PathCommandDef::MoveTo(PointDef { x: "x2", y: "y2" }),
  PathCommandDef::ArcTo {
    width_radius: "wd2",
    height_radius: "hd2",
    start_angle: "stB",
    sweep_angle: "swB",
  },
];
const TEXT_BUTTON_PATHS: &[PathDef] = &[
  PathDef {
    width: None,
    height: None,
    fill: None,
    stroke: None,
    extrusion_allowed: None,
    commands: TEXT_BUTTON_PATH_0_COMMANDS,
  },
  PathDef {
    width: None,
    height: None,
    fill: None,
    stroke: None,
    extrusion_allowed: None,
    commands: TEXT_BUTTON_PATH_1_COMMANDS,
  },
  PathDef {
    width: None,
    height: None,
    fill: None,
    stroke: None,
    extrusion_allowed: None,
    commands: TEXT_BUTTON_PATH_2_COMMANDS,
  },
];
const TEXT_BUTTON: Definition = Definition {
  adjustments: TEXT_BUTTON_ADJUSTMENTS,
  guides: TEXT_BUTTON_GUIDES,
  paths: TEXT_BUTTON_PATHS,
};

const TEXT_BUTTON_POUR_ADJUSTMENTS: &[GuideDef] = &[
  GuideDef {
    name: "adj1",
    formula: "val cd2",
  },
  GuideDef {
    name: "adj2",
    formula: "val 50000",
  },
];
const TEXT_BUTTON_POUR_GUIDES: &[GuideDef] = &[
  GuideDef {
    name: "adval",
    formula: "pin 0 adj1 21599999",
  },
  GuideDef {
    name: "bot",
    formula: "+- 5400000 0 adval",
  },
  GuideDef {
    name: "lef",
    formula: "+- 10800000 0 adval",
  },
  GuideDef {
    name: "top",
    formula: "+- 16200000 0 adval",
  },
  GuideDef {
    name: "rig",
    formula: "+- 21600000 0 adval",
  },
  GuideDef {
    name: "c3",
    formula: "?: top adval 0",
  },
  GuideDef {
    name: "c2",
    formula: "?: lef 10800000 c3",
  },
  GuideDef {
    name: "c1",
    formula: "?: bot rig c2",
  },
  GuideDef {
    name: "stAng",
    formula: "?: adval c1 0",
  },
  GuideDef {
    name: "w1",
    formula: "+- 21600000 0 stAng",
  },
  GuideDef {
    name: "stAngB",
    formula: "?: stAng w1 0",
  },
  GuideDef {
    name: "td1",
    formula: "*/ bot 2 1",
  },
  GuideDef {
    name: "td2",
    formula: "*/ top 2 1",
  },
  GuideDef {
    name: "ntd2",
    formula: "+- 0 0 td2",
  },
  GuideDef {
    name: "w2",
    formula: "+- 0 0 10800000",
  },
  GuideDef {
    name: "c6",
    formula: "?: top ntd2 w2",
  },
  GuideDef {
    name: "c5",
    formula: "?: lef 10800000 c6",
  },
  GuideDef {
    name: "c4",
    formula: "?: bot td1 c5",
  },
  GuideDef {
    name: "v1",
    formula: "?: adval c4 10800000",
  },
  GuideDef {
    name: "swAngT",
    formula: "+- 0 0 v1",
  },
  GuideDef {
    name: "stT",
    formula: "?: lef stAngB stAng",
  },
  GuideDef {
    name: "stB",
    formula: "?: lef stAng stAngB",
  },
  GuideDef {
    name: "swT",
    formula: "?: lef v1 swAngT",
  },
  GuideDef {
    name: "swB",
    formula: "?: lef swAngT v1",
  },
  GuideDef {
    name: "wt1",
    formula: "sin wd2 stT",
  },
  GuideDef {
    name: "ht1",
    formula: "cos hd2 stT",
  },
  GuideDef {
    name: "dx1",
    formula: "cat2 wd2 ht1 wt1",
  },
  GuideDef {
    name: "dy1",
    formula: "sat2 hd2 ht1 wt1",
  },
  GuideDef {
    name: "x1",
    formula: "+- hc dx1 0",
  },
  GuideDef {
    name: "y1",
    formula: "+- vc dy1 0",
  },
  GuideDef {
    name: "wt6",
    formula: "sin wd2 stB",
  },
  GuideDef {
    name: "ht6",
    formula: "cos hd2 stB",
  },
  GuideDef {
    name: "dx6",
    formula: "cat2 wd2 ht6 wt6",
  },
  GuideDef {
    name: "dy6",
    formula: "sat2 hd2 ht6 wt6",
  },
  GuideDef {
    name: "x6",
    formula: "+- hc dx6 0",
  },
  GuideDef {
    name: "y6",
    formula: "+- vc dy6 0",
  },
  GuideDef {
    name: "adval2",
    formula: "pin 40000 adj2 99000",
  },
  GuideDef {
    name: "ratio",
    formula: "*/ adval2 1 100000",
  },
  GuideDef {
    name: "iwd2",
    formula: "*/ wd2 ratio 1",
  },
  GuideDef {
    name: "ihd2",
    formula: "*/ hd2 ratio 1",
  },
  GuideDef {
    name: "wt2",
    formula: "sin iwd2 stT",
  },
  GuideDef {
    name: "ht2",
    formula: "cos ihd2 stT",
  },
  GuideDef {
    name: "dx2",
    formula: "cat2 iwd2 ht2 wt2",
  },
  GuideDef {
    name: "dy2",
    formula: "sat2 ihd2 ht2 wt2",
  },
  GuideDef {
    name: "x2",
    formula: "+- hc dx2 0",
  },
  GuideDef {
    name: "y2",
    formula: "+- vc dy2 0",
  },
  GuideDef {
    name: "wt5",
    formula: "sin iwd2 stB",
  },
  GuideDef {
    name: "ht5",
    formula: "cos ihd2 stB",
  },
  GuideDef {
    name: "dx5",
    formula: "cat2 iwd2 ht5 wt5",
  },
  GuideDef {
    name: "dy5",
    formula: "sat2 ihd2 ht5 wt5",
  },
  GuideDef {
    name: "x5",
    formula: "+- hc dx5 0",
  },
  GuideDef {
    name: "y5",
    formula: "+- vc dy5 0",
  },
  GuideDef {
    name: "d1",
    formula: "+- hd2 0 ihd2",
  },
  GuideDef {
    name: "d12",
    formula: "*/ d1 1 2",
  },
  GuideDef {
    name: "yu",
    formula: "+- vc 0 d12",
  },
  GuideDef {
    name: "yd",
    formula: "+- vc d12 0",
  },
  GuideDef {
    name: "v1",
    formula: "*/ d12 d12 1",
  },
  GuideDef {
    name: "v2",
    formula: "*/ ihd2 ihd2 1",
  },
  GuideDef {
    name: "v3",
    formula: "*/ v1 1 v2",
  },
  GuideDef {
    name: "v4",
    formula: "+- 1 0 v3",
  },
  GuideDef {
    name: "v5",
    formula: "*/ iwd2 iwd2 1",
  },
  GuideDef {
    name: "v6",
    formula: "*/ v4 v5 1",
  },
  GuideDef {
    name: "v7",
    formula: "sqrt v6",
  },
  GuideDef {
    name: "xl",
    formula: "+- hc 0 v7",
  },
  GuideDef {
    name: "xr",
    formula: "+- hc v7 0",
  },
  GuideDef {
    name: "wtadj",
    formula: "sin iwd2 adj1",
  },
  GuideDef {
    name: "htadj",
    formula: "cos ihd2 adj1",
  },
  GuideDef {
    name: "dxadj",
    formula: "cat2 iwd2 htadj wtadj",
  },
  GuideDef {
    name: "dyadj",
    formula: "sat2 ihd2 htadj wtadj",
  },
  GuideDef {
    name: "xadj",
    formula: "+- hc dxadj 0",
  },
  GuideDef {
    name: "yadj",
    formula: "+- vc dyadj 0",
  },
];
const TEXT_BUTTON_POUR_PATH_0_COMMANDS: &[PathCommandDef] = &[
  PathCommandDef::MoveTo(PointDef { x: "x1", y: "y1" }),
  PathCommandDef::ArcTo {
    width_radius: "wd2",
    height_radius: "hd2",
    start_angle: "stT",
    sweep_angle: "swT",
  },
];
const TEXT_BUTTON_POUR_PATH_1_COMMANDS: &[PathCommandDef] = &[
  PathCommandDef::MoveTo(PointDef { x: "x2", y: "y2" }),
  PathCommandDef::ArcTo {
    width_radius: "iwd2",
    height_radius: "ihd2",
    start_angle: "stT",
    sweep_angle: "swT",
  },
];
const TEXT_BUTTON_POUR_PATH_2_COMMANDS: &[PathCommandDef] = &[
  PathCommandDef::MoveTo(PointDef { x: "xl", y: "yu" }),
  PathCommandDef::LineTo(PointDef { x: "xr", y: "yu" }),
];
const TEXT_BUTTON_POUR_PATH_3_COMMANDS: &[PathCommandDef] = &[
  PathCommandDef::MoveTo(PointDef { x: "xl", y: "yd" }),
  PathCommandDef::LineTo(PointDef { x: "xr", y: "yd" }),
];
const TEXT_BUTTON_POUR_PATH_4_COMMANDS: &[PathCommandDef] = &[
  PathCommandDef::MoveTo(PointDef { x: "x5", y: "y5" }),
  PathCommandDef::ArcTo {
    width_radius: "iwd2",
    height_radius: "ihd2",
    start_angle: "stB",
    sweep_angle: "swB",
  },
];
const TEXT_BUTTON_POUR_PATH_5_COMMANDS: &[PathCommandDef] = &[
  PathCommandDef::MoveTo(PointDef { x: "x6", y: "y6" }),
  PathCommandDef::ArcTo {
    width_radius: "wd2",
    height_radius: "hd2",
    start_angle: "stB",
    sweep_angle: "swB",
  },
];
const TEXT_BUTTON_POUR_PATHS: &[PathDef] = &[
  PathDef {
    width: None,
    height: None,
    fill: None,
    stroke: None,
    extrusion_allowed: None,
    commands: TEXT_BUTTON_POUR_PATH_0_COMMANDS,
  },
  PathDef {
    width: None,
    height: None,
    fill: None,
    stroke: None,
    extrusion_allowed: None,
    commands: TEXT_BUTTON_POUR_PATH_1_COMMANDS,
  },
  PathDef {
    width: None,
    height: None,
    fill: None,
    stroke: None,
    extrusion_allowed: None,
    commands: TEXT_BUTTON_POUR_PATH_2_COMMANDS,
  },
  PathDef {
    width: None,
    height: None,
    fill: None,
    stroke: None,
    extrusion_allowed: None,
    commands: TEXT_BUTTON_POUR_PATH_3_COMMANDS,
  },
  PathDef {
    width: None,
    height: None,
    fill: None,
    stroke: None,
    extrusion_allowed: None,
    commands: TEXT_BUTTON_POUR_PATH_4_COMMANDS,
  },
  PathDef {
    width: None,
    height: None,
    fill: None,
    stroke: None,
    extrusion_allowed: None,
    commands: TEXT_BUTTON_POUR_PATH_5_COMMANDS,
  },
];
const TEXT_BUTTON_POUR: Definition = Definition {
  adjustments: TEXT_BUTTON_POUR_ADJUSTMENTS,
  guides: TEXT_BUTTON_POUR_GUIDES,
  paths: TEXT_BUTTON_POUR_PATHS,
};

const TEXT_CAN_DOWN_ADJUSTMENTS: &[GuideDef] = &[GuideDef {
  name: "adj",
  formula: "val 14286",
}];
const TEXT_CAN_DOWN_GUIDES: &[GuideDef] = &[
  GuideDef {
    name: "a",
    formula: "pin 0 adj 33333",
  },
  GuideDef {
    name: "dy",
    formula: "*/ a h 100000",
  },
  GuideDef {
    name: "y0",
    formula: "+- t dy 0",
  },
  GuideDef {
    name: "y1",
    formula: "+- b 0 dy",
  },
  GuideDef {
    name: "ncd2",
    formula: "*/ cd2 -1 1",
  },
];
const TEXT_CAN_DOWN_PATH_0_COMMANDS: &[PathCommandDef] = &[
  PathCommandDef::MoveTo(PointDef { x: "l", y: "t" }),
  PathCommandDef::ArcTo {
    width_radius: "wd2",
    height_radius: "dy",
    start_angle: "cd2",
    sweep_angle: "ncd2",
  },
];
const TEXT_CAN_DOWN_PATH_1_COMMANDS: &[PathCommandDef] = &[
  PathCommandDef::MoveTo(PointDef { x: "l", y: "y1" }),
  PathCommandDef::ArcTo {
    width_radius: "wd2",
    height_radius: "dy",
    start_angle: "cd2",
    sweep_angle: "ncd2",
  },
];
const TEXT_CAN_DOWN_PATHS: &[PathDef] = &[
  PathDef {
    width: None,
    height: None,
    fill: None,
    stroke: None,
    extrusion_allowed: None,
    commands: TEXT_CAN_DOWN_PATH_0_COMMANDS,
  },
  PathDef {
    width: None,
    height: None,
    fill: None,
    stroke: None,
    extrusion_allowed: None,
    commands: TEXT_CAN_DOWN_PATH_1_COMMANDS,
  },
];
const TEXT_CAN_DOWN: Definition = Definition {
  adjustments: TEXT_CAN_DOWN_ADJUSTMENTS,
  guides: TEXT_CAN_DOWN_GUIDES,
  paths: TEXT_CAN_DOWN_PATHS,
};

const TEXT_CAN_UP_ADJUSTMENTS: &[GuideDef] = &[GuideDef {
  name: "adj",
  formula: "val 85714",
}];
const TEXT_CAN_UP_GUIDES: &[GuideDef] = &[
  GuideDef {
    name: "a",
    formula: "pin 66667 adj 100000",
  },
  GuideDef {
    name: "dy1",
    formula: "*/ a h 100000",
  },
  GuideDef {
    name: "dy",
    formula: "+- h 0 dy1",
  },
  GuideDef {
    name: "y0",
    formula: "+- t dy1 0",
  },
  GuideDef {
    name: "y1",
    formula: "+- t dy 0",
  },
];
const TEXT_CAN_UP_PATH_0_COMMANDS: &[PathCommandDef] = &[
  PathCommandDef::MoveTo(PointDef { x: "l", y: "y1" }),
  PathCommandDef::ArcTo {
    width_radius: "wd2",
    height_radius: "dy",
    start_angle: "cd2",
    sweep_angle: "cd2",
  },
];
const TEXT_CAN_UP_PATH_1_COMMANDS: &[PathCommandDef] = &[
  PathCommandDef::MoveTo(PointDef { x: "l", y: "b" }),
  PathCommandDef::ArcTo {
    width_radius: "wd2",
    height_radius: "dy",
    start_angle: "cd2",
    sweep_angle: "cd2",
  },
];
const TEXT_CAN_UP_PATHS: &[PathDef] = &[
  PathDef {
    width: None,
    height: None,
    fill: None,
    stroke: None,
    extrusion_allowed: None,
    commands: TEXT_CAN_UP_PATH_0_COMMANDS,
  },
  PathDef {
    width: None,
    height: None,
    fill: None,
    stroke: None,
    extrusion_allowed: None,
    commands: TEXT_CAN_UP_PATH_1_COMMANDS,
  },
];
const TEXT_CAN_UP: Definition = Definition {
  adjustments: TEXT_CAN_UP_ADJUSTMENTS,
  guides: TEXT_CAN_UP_GUIDES,
  paths: TEXT_CAN_UP_PATHS,
};

const TEXT_CASCADE_DOWN_ADJUSTMENTS: &[GuideDef] = &[GuideDef {
  name: "adj",
  formula: "val 44444",
}];
const TEXT_CASCADE_DOWN_GUIDES: &[GuideDef] = &[
  GuideDef {
    name: "a",
    formula: "pin 28570 adj 100000",
  },
  GuideDef {
    name: "dy",
    formula: "*/ a h 100000",
  },
  GuideDef {
    name: "y1",
    formula: "+- t dy 0",
  },
  GuideDef {
    name: "dy2",
    formula: "+- h 0 dy",
  },
  GuideDef {
    name: "dy3",
    formula: "*/ dy2 1 4",
  },
  GuideDef {
    name: "y2",
    formula: "+- t dy3 0",
  },
];
const TEXT_CASCADE_DOWN_PATH_0_COMMANDS: &[PathCommandDef] = &[
  PathCommandDef::MoveTo(PointDef { x: "l", y: "t" }),
  PathCommandDef::LineTo(PointDef { x: "r", y: "y2" }),
];
const TEXT_CASCADE_DOWN_PATH_1_COMMANDS: &[PathCommandDef] = &[
  PathCommandDef::MoveTo(PointDef { x: "l", y: "y1" }),
  PathCommandDef::LineTo(PointDef { x: "r", y: "b" }),
];
const TEXT_CASCADE_DOWN_PATHS: &[PathDef] = &[
  PathDef {
    width: None,
    height: None,
    fill: None,
    stroke: None,
    extrusion_allowed: None,
    commands: TEXT_CASCADE_DOWN_PATH_0_COMMANDS,
  },
  PathDef {
    width: None,
    height: None,
    fill: None,
    stroke: None,
    extrusion_allowed: None,
    commands: TEXT_CASCADE_DOWN_PATH_1_COMMANDS,
  },
];
const TEXT_CASCADE_DOWN: Definition = Definition {
  adjustments: TEXT_CASCADE_DOWN_ADJUSTMENTS,
  guides: TEXT_CASCADE_DOWN_GUIDES,
  paths: TEXT_CASCADE_DOWN_PATHS,
};

const TEXT_CASCADE_UP_ADJUSTMENTS: &[GuideDef] = &[GuideDef {
  name: "adj",
  formula: "val 44444",
}];
const TEXT_CASCADE_UP_GUIDES: &[GuideDef] = &[
  GuideDef {
    name: "a",
    formula: "pin 28570 adj 100000",
  },
  GuideDef {
    name: "dy",
    formula: "*/ a h 100000",
  },
  GuideDef {
    name: "y1",
    formula: "+- t dy 0",
  },
  GuideDef {
    name: "dy2",
    formula: "+- h 0 dy",
  },
  GuideDef {
    name: "dy3",
    formula: "*/ dy2 1 4",
  },
  GuideDef {
    name: "y2",
    formula: "+- t dy3 0",
  },
];
const TEXT_CASCADE_UP_PATH_0_COMMANDS: &[PathCommandDef] = &[
  PathCommandDef::MoveTo(PointDef { x: "l", y: "y2" }),
  PathCommandDef::LineTo(PointDef { x: "r", y: "t" }),
];
const TEXT_CASCADE_UP_PATH_1_COMMANDS: &[PathCommandDef] = &[
  PathCommandDef::MoveTo(PointDef { x: "l", y: "b" }),
  PathCommandDef::LineTo(PointDef { x: "r", y: "y1" }),
];
const TEXT_CASCADE_UP_PATHS: &[PathDef] = &[
  PathDef {
    width: None,
    height: None,
    fill: None,
    stroke: None,
    extrusion_allowed: None,
    commands: TEXT_CASCADE_UP_PATH_0_COMMANDS,
  },
  PathDef {
    width: None,
    height: None,
    fill: None,
    stroke: None,
    extrusion_allowed: None,
    commands: TEXT_CASCADE_UP_PATH_1_COMMANDS,
  },
];
const TEXT_CASCADE_UP: Definition = Definition {
  adjustments: TEXT_CASCADE_UP_ADJUSTMENTS,
  guides: TEXT_CASCADE_UP_GUIDES,
  paths: TEXT_CASCADE_UP_PATHS,
};

const TEXT_CHEVRON_ADJUSTMENTS: &[GuideDef] = &[GuideDef {
  name: "adj",
  formula: "val 25000",
}];
const TEXT_CHEVRON_GUIDES: &[GuideDef] = &[
  GuideDef {
    name: "a",
    formula: "pin 0 adj 50000",
  },
  GuideDef {
    name: "y",
    formula: "*/ a h 100000",
  },
  GuideDef {
    name: "y1",
    formula: "+- t b y",
  },
];
const TEXT_CHEVRON_PATH_0_COMMANDS: &[PathCommandDef] = &[
  PathCommandDef::MoveTo(PointDef { x: "l", y: "y" }),
  PathCommandDef::LineTo(PointDef { x: "hc", y: "t" }),
  PathCommandDef::LineTo(PointDef { x: "r", y: "y" }),
];
const TEXT_CHEVRON_PATH_1_COMMANDS: &[PathCommandDef] = &[
  PathCommandDef::MoveTo(PointDef { x: "l", y: "b" }),
  PathCommandDef::LineTo(PointDef { x: "hc", y: "y1" }),
  PathCommandDef::LineTo(PointDef { x: "r", y: "b" }),
];
const TEXT_CHEVRON_PATHS: &[PathDef] = &[
  PathDef {
    width: None,
    height: None,
    fill: None,
    stroke: None,
    extrusion_allowed: None,
    commands: TEXT_CHEVRON_PATH_0_COMMANDS,
  },
  PathDef {
    width: None,
    height: None,
    fill: None,
    stroke: None,
    extrusion_allowed: None,
    commands: TEXT_CHEVRON_PATH_1_COMMANDS,
  },
];
const TEXT_CHEVRON: Definition = Definition {
  adjustments: TEXT_CHEVRON_ADJUSTMENTS,
  guides: TEXT_CHEVRON_GUIDES,
  paths: TEXT_CHEVRON_PATHS,
};

const TEXT_CHEVRON_INVERTED_ADJUSTMENTS: &[GuideDef] = &[GuideDef {
  name: "adj",
  formula: "val 75000",
}];
const TEXT_CHEVRON_INVERTED_GUIDES: &[GuideDef] = &[
  GuideDef {
    name: "a",
    formula: "pin 50000 adj 100000",
  },
  GuideDef {
    name: "y",
    formula: "*/ a h 100000",
  },
  GuideDef {
    name: "y1",
    formula: "+- b 0 y",
  },
];
const TEXT_CHEVRON_INVERTED_PATH_0_COMMANDS: &[PathCommandDef] = &[
  PathCommandDef::MoveTo(PointDef { x: "l", y: "t" }),
  PathCommandDef::LineTo(PointDef { x: "hc", y: "y1" }),
  PathCommandDef::LineTo(PointDef { x: "r", y: "t" }),
];
const TEXT_CHEVRON_INVERTED_PATH_1_COMMANDS: &[PathCommandDef] = &[
  PathCommandDef::MoveTo(PointDef { x: "l", y: "y" }),
  PathCommandDef::LineTo(PointDef { x: "hc", y: "b" }),
  PathCommandDef::LineTo(PointDef { x: "r", y: "y" }),
];
const TEXT_CHEVRON_INVERTED_PATHS: &[PathDef] = &[
  PathDef {
    width: None,
    height: None,
    fill: None,
    stroke: None,
    extrusion_allowed: None,
    commands: TEXT_CHEVRON_INVERTED_PATH_0_COMMANDS,
  },
  PathDef {
    width: None,
    height: None,
    fill: None,
    stroke: None,
    extrusion_allowed: None,
    commands: TEXT_CHEVRON_INVERTED_PATH_1_COMMANDS,
  },
];
const TEXT_CHEVRON_INVERTED: Definition = Definition {
  adjustments: TEXT_CHEVRON_INVERTED_ADJUSTMENTS,
  guides: TEXT_CHEVRON_INVERTED_GUIDES,
  paths: TEXT_CHEVRON_INVERTED_PATHS,
};

const TEXT_CIRCLE_ADJUSTMENTS: &[GuideDef] = &[GuideDef {
  name: "adj",
  formula: "val 10800000",
}];
const TEXT_CIRCLE_GUIDES: &[GuideDef] = &[
  GuideDef {
    name: "adval",
    formula: "pin 0 adj 21599999",
  },
  GuideDef {
    name: "d0",
    formula: "+- adval 0 10800000",
  },
  GuideDef {
    name: "d1",
    formula: "+- 10800000 0 adval",
  },
  GuideDef {
    name: "d2",
    formula: "+- 21600000 0 adval",
  },
  GuideDef {
    name: "d3",
    formula: "?: d1 d1 10799999",
  },
  GuideDef {
    name: "d4",
    formula: "?: d0 d2 d3",
  },
  GuideDef {
    name: "swAng",
    formula: "*/ d4 2 1",
  },
  GuideDef {
    name: "wt1",
    formula: "sin wd2 adj",
  },
  GuideDef {
    name: "ht1",
    formula: "cos hd2 adj",
  },
  GuideDef {
    name: "dx1",
    formula: "cat2 wd2 ht1 wt1",
  },
  GuideDef {
    name: "dy1",
    formula: "sat2 hd2 ht1 wt1",
  },
  GuideDef {
    name: "x1",
    formula: "+- hc dx1 0",
  },
  GuideDef {
    name: "y1",
    formula: "+- vc dy1 0",
  },
];
const TEXT_CIRCLE_PATH_0_COMMANDS: &[PathCommandDef] = &[
  PathCommandDef::MoveTo(PointDef { x: "x1", y: "y1" }),
  PathCommandDef::ArcTo {
    width_radius: "wd2",
    height_radius: "hd2",
    start_angle: "adval",
    sweep_angle: "swAng",
  },
];
const TEXT_CIRCLE_PATHS: &[PathDef] = &[PathDef {
  width: None,
  height: None,
  fill: None,
  stroke: None,
  extrusion_allowed: None,
  commands: TEXT_CIRCLE_PATH_0_COMMANDS,
}];
const TEXT_CIRCLE: Definition = Definition {
  adjustments: TEXT_CIRCLE_ADJUSTMENTS,
  guides: TEXT_CIRCLE_GUIDES,
  paths: TEXT_CIRCLE_PATHS,
};

const TEXT_CIRCLE_POUR_ADJUSTMENTS: &[GuideDef] = &[
  GuideDef {
    name: "adj1",
    formula: "val cd2",
  },
  GuideDef {
    name: "adj2",
    formula: "val 50000",
  },
];
const TEXT_CIRCLE_POUR_GUIDES: &[GuideDef] = &[
  GuideDef {
    name: "adval",
    formula: "pin 0 adj1 21599999",
  },
  GuideDef {
    name: "d0",
    formula: "+- adval 0 10800000",
  },
  GuideDef {
    name: "d1",
    formula: "+- 10800000 0 adval",
  },
  GuideDef {
    name: "d2",
    formula: "+- 21600000 0 adval",
  },
  GuideDef {
    name: "d3",
    formula: "?: d1 d1 10799999",
  },
  GuideDef {
    name: "d4",
    formula: "?: d0 d2 d3",
  },
  GuideDef {
    name: "swAng",
    formula: "*/ d4 2 1",
  },
  GuideDef {
    name: "wt1",
    formula: "sin wd2 adval",
  },
  GuideDef {
    name: "ht1",
    formula: "cos hd2 adval",
  },
  GuideDef {
    name: "dx1",
    formula: "cat2 wd2 ht1 wt1",
  },
  GuideDef {
    name: "dy1",
    formula: "sat2 hd2 ht1 wt1",
  },
  GuideDef {
    name: "x1",
    formula: "+- hc dx1 0",
  },
  GuideDef {
    name: "y1",
    formula: "+- vc dy1 0",
  },
  GuideDef {
    name: "adval2",
    formula: "pin 0 adj2 99000",
  },
  GuideDef {
    name: "ratio",
    formula: "*/ adval2 1 100000",
  },
  GuideDef {
    name: "iwd2",
    formula: "*/ wd2 ratio 1",
  },
  GuideDef {
    name: "ihd2",
    formula: "*/ hd2 ratio 1",
  },
  GuideDef {
    name: "wt2",
    formula: "sin iwd2 adval",
  },
  GuideDef {
    name: "ht2",
    formula: "cos ihd2 adval",
  },
  GuideDef {
    name: "dx2",
    formula: "cat2 iwd2 ht2 wt2",
  },
  GuideDef {
    name: "dy2",
    formula: "sat2 ihd2 ht2 wt2",
  },
  GuideDef {
    name: "x2",
    formula: "+- hc dx2 0",
  },
  GuideDef {
    name: "y2",
    formula: "+- vc dy2 0",
  },
];
const TEXT_CIRCLE_POUR_PATH_0_COMMANDS: &[PathCommandDef] = &[
  PathCommandDef::MoveTo(PointDef { x: "x1", y: "y1" }),
  PathCommandDef::ArcTo {
    width_radius: "wd2",
    height_radius: "hd2",
    start_angle: "adval",
    sweep_angle: "swAng",
  },
];
const TEXT_CIRCLE_POUR_PATH_1_COMMANDS: &[PathCommandDef] = &[
  PathCommandDef::MoveTo(PointDef { x: "x2", y: "y2" }),
  PathCommandDef::ArcTo {
    width_radius: "iwd2",
    height_radius: "ihd2",
    start_angle: "adval",
    sweep_angle: "swAng",
  },
];
const TEXT_CIRCLE_POUR_PATHS: &[PathDef] = &[
  PathDef {
    width: None,
    height: None,
    fill: None,
    stroke: None,
    extrusion_allowed: None,
    commands: TEXT_CIRCLE_POUR_PATH_0_COMMANDS,
  },
  PathDef {
    width: None,
    height: None,
    fill: None,
    stroke: None,
    extrusion_allowed: None,
    commands: TEXT_CIRCLE_POUR_PATH_1_COMMANDS,
  },
];
const TEXT_CIRCLE_POUR: Definition = Definition {
  adjustments: TEXT_CIRCLE_POUR_ADJUSTMENTS,
  guides: TEXT_CIRCLE_POUR_GUIDES,
  paths: TEXT_CIRCLE_POUR_PATHS,
};

const TEXT_CURVE_DOWN_ADJUSTMENTS: &[GuideDef] = &[GuideDef {
  name: "adj",
  formula: "val 45977",
}];
const TEXT_CURVE_DOWN_GUIDES: &[GuideDef] = &[
  GuideDef {
    name: "a",
    formula: "pin 0 adj 56338",
  },
  GuideDef {
    name: "dy",
    formula: "*/ a h 100000",
  },
  GuideDef {
    name: "gd1",
    formula: "*/ dy 3 4",
  },
  GuideDef {
    name: "gd2",
    formula: "*/ dy 5 4",
  },
  GuideDef {
    name: "gd3",
    formula: "*/ dy 3 8",
  },
  GuideDef {
    name: "gd4",
    formula: "*/ dy 1 8",
  },
  GuideDef {
    name: "gd5",
    formula: "+- h 0 gd3",
  },
  GuideDef {
    name: "gd6",
    formula: "+- gd4 h 0",
  },
  GuideDef {
    name: "y0",
    formula: "+- t dy 0",
  },
  GuideDef {
    name: "y1",
    formula: "+- t gd1 0",
  },
  GuideDef {
    name: "y2",
    formula: "+- t gd2 0",
  },
  GuideDef {
    name: "y3",
    formula: "+- t gd3 0",
  },
  GuideDef {
    name: "y4",
    formula: "+- t gd4 0",
  },
  GuideDef {
    name: "y5",
    formula: "+- t gd5 0",
  },
  GuideDef {
    name: "y6",
    formula: "+- t gd6 0",
  },
  GuideDef {
    name: "x1",
    formula: "+- l wd3 0",
  },
  GuideDef {
    name: "x2",
    formula: "+- r 0 wd3",
  },
];
const TEXT_CURVE_DOWN_PATH_0_COMMANDS: &[PathCommandDef] = &[
  PathCommandDef::MoveTo(PointDef { x: "l", y: "t" }),
  PathCommandDef::CubicTo(&[
    PointDef { x: "x1", y: "y1" },
    PointDef { x: "x2", y: "y2" },
    PointDef { x: "r", y: "y0" },
  ]),
];
const TEXT_CURVE_DOWN_PATH_1_COMMANDS: &[PathCommandDef] = &[
  PathCommandDef::MoveTo(PointDef { x: "l", y: "y5" }),
  PathCommandDef::CubicTo(&[
    PointDef { x: "x1", y: "y6" },
    PointDef { x: "x2", y: "y6" },
    PointDef { x: "r", y: "y5" },
  ]),
];
const TEXT_CURVE_DOWN_PATHS: &[PathDef] = &[
  PathDef {
    width: None,
    height: None,
    fill: None,
    stroke: None,
    extrusion_allowed: None,
    commands: TEXT_CURVE_DOWN_PATH_0_COMMANDS,
  },
  PathDef {
    width: None,
    height: None,
    fill: None,
    stroke: None,
    extrusion_allowed: None,
    commands: TEXT_CURVE_DOWN_PATH_1_COMMANDS,
  },
];
const TEXT_CURVE_DOWN: Definition = Definition {
  adjustments: TEXT_CURVE_DOWN_ADJUSTMENTS,
  guides: TEXT_CURVE_DOWN_GUIDES,
  paths: TEXT_CURVE_DOWN_PATHS,
};

const TEXT_CURVE_UP_ADJUSTMENTS: &[GuideDef] = &[GuideDef {
  name: "adj",
  formula: "val 45977",
}];
const TEXT_CURVE_UP_GUIDES: &[GuideDef] = &[
  GuideDef {
    name: "a",
    formula: "pin 0 adj 56338",
  },
  GuideDef {
    name: "dy",
    formula: "*/ a h 100000",
  },
  GuideDef {
    name: "gd1",
    formula: "*/ dy 3 4",
  },
  GuideDef {
    name: "gd2",
    formula: "*/ dy 5 4",
  },
  GuideDef {
    name: "gd3",
    formula: "*/ dy 3 8",
  },
  GuideDef {
    name: "gd4",
    formula: "*/ dy 1 8",
  },
  GuideDef {
    name: "gd5",
    formula: "+- h 0 gd3",
  },
  GuideDef {
    name: "gd6",
    formula: "+- gd4 h 0",
  },
  GuideDef {
    name: "y0",
    formula: "+- t dy 0",
  },
  GuideDef {
    name: "y1",
    formula: "+- t gd1 0",
  },
  GuideDef {
    name: "y2",
    formula: "+- t gd2 0",
  },
  GuideDef {
    name: "y3",
    formula: "+- t gd3 0",
  },
  GuideDef {
    name: "y4",
    formula: "+- t gd4 0",
  },
  GuideDef {
    name: "y5",
    formula: "+- t gd5 0",
  },
  GuideDef {
    name: "y6",
    formula: "+- t gd6 0",
  },
  GuideDef {
    name: "x1",
    formula: "+- l wd3 0",
  },
  GuideDef {
    name: "x2",
    formula: "+- r 0 wd3",
  },
];
const TEXT_CURVE_UP_PATH_0_COMMANDS: &[PathCommandDef] = &[
  PathCommandDef::MoveTo(PointDef { x: "l", y: "y0" }),
  PathCommandDef::CubicTo(&[
    PointDef { x: "x1", y: "y2" },
    PointDef { x: "x2", y: "y1" },
    PointDef { x: "r", y: "t" },
  ]),
];
const TEXT_CURVE_UP_PATH_1_COMMANDS: &[PathCommandDef] = &[
  PathCommandDef::MoveTo(PointDef { x: "l", y: "y5" }),
  PathCommandDef::CubicTo(&[
    PointDef { x: "x1", y: "y6" },
    PointDef { x: "x2", y: "y6" },
    PointDef { x: "r", y: "y5" },
  ]),
];
const TEXT_CURVE_UP_PATHS: &[PathDef] = &[
  PathDef {
    width: None,
    height: None,
    fill: None,
    stroke: None,
    extrusion_allowed: None,
    commands: TEXT_CURVE_UP_PATH_0_COMMANDS,
  },
  PathDef {
    width: None,
    height: None,
    fill: None,
    stroke: None,
    extrusion_allowed: None,
    commands: TEXT_CURVE_UP_PATH_1_COMMANDS,
  },
];
const TEXT_CURVE_UP: Definition = Definition {
  adjustments: TEXT_CURVE_UP_ADJUSTMENTS,
  guides: TEXT_CURVE_UP_GUIDES,
  paths: TEXT_CURVE_UP_PATHS,
};

const TEXT_DEFLATE_ADJUSTMENTS: &[GuideDef] = &[GuideDef {
  name: "adj",
  formula: "val 18750",
}];
const TEXT_DEFLATE_GUIDES: &[GuideDef] = &[
  GuideDef {
    name: "a",
    formula: "pin 0 adj 37500",
  },
  GuideDef {
    name: "dy",
    formula: "*/ a ss 100000",
  },
  GuideDef {
    name: "gd0",
    formula: "*/ dy 4 3",
  },
  GuideDef {
    name: "gd1",
    formula: "+- h 0 gd0",
  },
  GuideDef {
    name: "adjY",
    formula: "+- t dy 0",
  },
  GuideDef {
    name: "y0",
    formula: "+- t gd0 0",
  },
  GuideDef {
    name: "y1",
    formula: "+- t gd1 0",
  },
  GuideDef {
    name: "x0",
    formula: "+- l wd3 0",
  },
  GuideDef {
    name: "x1",
    formula: "+- r 0 wd3",
  },
];
const TEXT_DEFLATE_PATH_0_COMMANDS: &[PathCommandDef] = &[
  PathCommandDef::MoveTo(PointDef { x: "l", y: "t" }),
  PathCommandDef::CubicTo(&[
    PointDef { x: "x0", y: "y0" },
    PointDef { x: "x1", y: "y0" },
    PointDef { x: "r", y: "t" },
  ]),
];
const TEXT_DEFLATE_PATH_1_COMMANDS: &[PathCommandDef] = &[
  PathCommandDef::MoveTo(PointDef { x: "l", y: "b" }),
  PathCommandDef::CubicTo(&[
    PointDef { x: "x0", y: "y1" },
    PointDef { x: "x1", y: "y1" },
    PointDef { x: "r", y: "b" },
  ]),
];
const TEXT_DEFLATE_PATHS: &[PathDef] = &[
  PathDef {
    width: None,
    height: None,
    fill: None,
    stroke: None,
    extrusion_allowed: None,
    commands: TEXT_DEFLATE_PATH_0_COMMANDS,
  },
  PathDef {
    width: None,
    height: None,
    fill: None,
    stroke: None,
    extrusion_allowed: None,
    commands: TEXT_DEFLATE_PATH_1_COMMANDS,
  },
];
const TEXT_DEFLATE: Definition = Definition {
  adjustments: TEXT_DEFLATE_ADJUSTMENTS,
  guides: TEXT_DEFLATE_GUIDES,
  paths: TEXT_DEFLATE_PATHS,
};

const TEXT_DEFLATE_BOTTOM_ADJUSTMENTS: &[GuideDef] = &[GuideDef {
  name: "adj",
  formula: "val 50000",
}];
const TEXT_DEFLATE_BOTTOM_GUIDES: &[GuideDef] = &[
  GuideDef {
    name: "a",
    formula: "pin 6250 adj 100000",
  },
  GuideDef {
    name: "dy",
    formula: "*/ a ss 100000",
  },
  GuideDef {
    name: "dy2",
    formula: "+- h 0 dy",
  },
  GuideDef {
    name: "y1",
    formula: "+- t dy 0",
  },
  GuideDef {
    name: "cp",
    formula: "+- y1 0 dy2",
  },
];
const TEXT_DEFLATE_BOTTOM_PATH_0_COMMANDS: &[PathCommandDef] = &[
  PathCommandDef::MoveTo(PointDef { x: "l", y: "t" }),
  PathCommandDef::LineTo(PointDef { x: "r", y: "t" }),
];
const TEXT_DEFLATE_BOTTOM_PATH_1_COMMANDS: &[PathCommandDef] = &[
  PathCommandDef::MoveTo(PointDef { x: "l", y: "b" }),
  PathCommandDef::QuadraticTo(&[PointDef { x: "hc", y: "cp" }, PointDef { x: "r", y: "b" }]),
];
const TEXT_DEFLATE_BOTTOM_PATHS: &[PathDef] = &[
  PathDef {
    width: None,
    height: None,
    fill: None,
    stroke: None,
    extrusion_allowed: None,
    commands: TEXT_DEFLATE_BOTTOM_PATH_0_COMMANDS,
  },
  PathDef {
    width: None,
    height: None,
    fill: None,
    stroke: None,
    extrusion_allowed: None,
    commands: TEXT_DEFLATE_BOTTOM_PATH_1_COMMANDS,
  },
];
const TEXT_DEFLATE_BOTTOM: Definition = Definition {
  adjustments: TEXT_DEFLATE_BOTTOM_ADJUSTMENTS,
  guides: TEXT_DEFLATE_BOTTOM_GUIDES,
  paths: TEXT_DEFLATE_BOTTOM_PATHS,
};

const TEXT_DEFLATE_INFLATE_ADJUSTMENTS: &[GuideDef] = &[GuideDef {
  name: "adj",
  formula: "val 35000",
}];
const TEXT_DEFLATE_INFLATE_GUIDES: &[GuideDef] = &[
  GuideDef {
    name: "a",
    formula: "pin 5000 adj 95000",
  },
  GuideDef {
    name: "dy",
    formula: "*/ a h 100000",
  },
  GuideDef {
    name: "del",
    formula: "*/ h 5 100",
  },
  GuideDef {
    name: "dh1",
    formula: "*/ h 45 100",
  },
  GuideDef {
    name: "dh2",
    formula: "*/ h 55 100",
  },
  GuideDef {
    name: "yh",
    formula: "+- dy 0 del",
  },
  GuideDef {
    name: "yl",
    formula: "+- dy del 0",
  },
  GuideDef {
    name: "y3",
    formula: "+- yh yh dh1",
  },
  GuideDef {
    name: "y4",
    formula: "+- yl yl dh2",
  },
];
const TEXT_DEFLATE_INFLATE_PATH_0_COMMANDS: &[PathCommandDef] = &[
  PathCommandDef::MoveTo(PointDef { x: "l", y: "t" }),
  PathCommandDef::LineTo(PointDef { x: "r", y: "t" }),
];
const TEXT_DEFLATE_INFLATE_PATH_1_COMMANDS: &[PathCommandDef] = &[
  PathCommandDef::MoveTo(PointDef { x: "l", y: "dh1" }),
  PathCommandDef::QuadraticTo(&[PointDef { x: "hc", y: "y3" }, PointDef { x: "r", y: "dh1" }]),
];
const TEXT_DEFLATE_INFLATE_PATH_2_COMMANDS: &[PathCommandDef] = &[
  PathCommandDef::MoveTo(PointDef { x: "l", y: "dh2" }),
  PathCommandDef::QuadraticTo(&[PointDef { x: "hc", y: "y4" }, PointDef { x: "r", y: "dh2" }]),
];
const TEXT_DEFLATE_INFLATE_PATH_3_COMMANDS: &[PathCommandDef] = &[
  PathCommandDef::MoveTo(PointDef { x: "l", y: "b" }),
  PathCommandDef::LineTo(PointDef { x: "r", y: "b" }),
];
const TEXT_DEFLATE_INFLATE_PATHS: &[PathDef] = &[
  PathDef {
    width: None,
    height: None,
    fill: None,
    stroke: None,
    extrusion_allowed: None,
    commands: TEXT_DEFLATE_INFLATE_PATH_0_COMMANDS,
  },
  PathDef {
    width: None,
    height: None,
    fill: None,
    stroke: None,
    extrusion_allowed: None,
    commands: TEXT_DEFLATE_INFLATE_PATH_1_COMMANDS,
  },
  PathDef {
    width: None,
    height: None,
    fill: None,
    stroke: None,
    extrusion_allowed: None,
    commands: TEXT_DEFLATE_INFLATE_PATH_2_COMMANDS,
  },
  PathDef {
    width: None,
    height: None,
    fill: None,
    stroke: None,
    extrusion_allowed: None,
    commands: TEXT_DEFLATE_INFLATE_PATH_3_COMMANDS,
  },
];
const TEXT_DEFLATE_INFLATE: Definition = Definition {
  adjustments: TEXT_DEFLATE_INFLATE_ADJUSTMENTS,
  guides: TEXT_DEFLATE_INFLATE_GUIDES,
  paths: TEXT_DEFLATE_INFLATE_PATHS,
};

const TEXT_DEFLATE_INFLATE_DEFLATE_ADJUSTMENTS: &[GuideDef] = &[GuideDef {
  name: "adj",
  formula: "val 25000",
}];
const TEXT_DEFLATE_INFLATE_DEFLATE_GUIDES: &[GuideDef] = &[
  GuideDef {
    name: "a",
    formula: "pin 3000 adj 47000",
  },
  GuideDef {
    name: "dy",
    formula: "*/ a h 100000",
  },
  GuideDef {
    name: "del",
    formula: "*/ h 3 100",
  },
  GuideDef {
    name: "ey1",
    formula: "*/ h 30 100",
  },
  GuideDef {
    name: "ey2",
    formula: "*/ h 36 100",
  },
  GuideDef {
    name: "ey3",
    formula: "*/ h 63 100",
  },
  GuideDef {
    name: "ey4",
    formula: "*/ h 70 100",
  },
  GuideDef {
    name: "by",
    formula: "+- b 0 dy",
  },
  GuideDef {
    name: "yh1",
    formula: "+- dy 0 del",
  },
  GuideDef {
    name: "yl1",
    formula: "+- dy del 0",
  },
  GuideDef {
    name: "yh2",
    formula: "+- by 0 del",
  },
  GuideDef {
    name: "yl2",
    formula: "+- by del 0",
  },
  GuideDef {
    name: "y1",
    formula: "+- yh1 yh1 ey1",
  },
  GuideDef {
    name: "y2",
    formula: "+- yl1 yl1 ey2",
  },
  GuideDef {
    name: "y3",
    formula: "+- yh2 yh2 ey3",
  },
  GuideDef {
    name: "y4",
    formula: "+- yl2 yl2 ey4",
  },
];
const TEXT_DEFLATE_INFLATE_DEFLATE_PATH_0_COMMANDS: &[PathCommandDef] = &[
  PathCommandDef::MoveTo(PointDef { x: "l", y: "t" }),
  PathCommandDef::LineTo(PointDef { x: "r", y: "t" }),
];
const TEXT_DEFLATE_INFLATE_DEFLATE_PATH_1_COMMANDS: &[PathCommandDef] = &[
  PathCommandDef::MoveTo(PointDef { x: "l", y: "ey1" }),
  PathCommandDef::QuadraticTo(&[PointDef { x: "hc", y: "y1" }, PointDef { x: "r", y: "ey1" }]),
];
const TEXT_DEFLATE_INFLATE_DEFLATE_PATH_2_COMMANDS: &[PathCommandDef] = &[
  PathCommandDef::MoveTo(PointDef { x: "l", y: "ey2" }),
  PathCommandDef::QuadraticTo(&[PointDef { x: "hc", y: "y2" }, PointDef { x: "r", y: "ey2" }]),
];
const TEXT_DEFLATE_INFLATE_DEFLATE_PATH_3_COMMANDS: &[PathCommandDef] = &[
  PathCommandDef::MoveTo(PointDef { x: "l", y: "ey3" }),
  PathCommandDef::QuadraticTo(&[PointDef { x: "hc", y: "y3" }, PointDef { x: "r", y: "ey3" }]),
];
const TEXT_DEFLATE_INFLATE_DEFLATE_PATH_4_COMMANDS: &[PathCommandDef] = &[
  PathCommandDef::MoveTo(PointDef { x: "l", y: "ey4" }),
  PathCommandDef::QuadraticTo(&[PointDef { x: "hc", y: "y4" }, PointDef { x: "r", y: "ey4" }]),
];
const TEXT_DEFLATE_INFLATE_DEFLATE_PATH_5_COMMANDS: &[PathCommandDef] = &[
  PathCommandDef::MoveTo(PointDef { x: "l", y: "b" }),
  PathCommandDef::LineTo(PointDef { x: "r", y: "b" }),
];
const TEXT_DEFLATE_INFLATE_DEFLATE_PATHS: &[PathDef] = &[
  PathDef {
    width: None,
    height: None,
    fill: None,
    stroke: None,
    extrusion_allowed: None,
    commands: TEXT_DEFLATE_INFLATE_DEFLATE_PATH_0_COMMANDS,
  },
  PathDef {
    width: None,
    height: None,
    fill: None,
    stroke: None,
    extrusion_allowed: None,
    commands: TEXT_DEFLATE_INFLATE_DEFLATE_PATH_1_COMMANDS,
  },
  PathDef {
    width: None,
    height: None,
    fill: None,
    stroke: None,
    extrusion_allowed: None,
    commands: TEXT_DEFLATE_INFLATE_DEFLATE_PATH_2_COMMANDS,
  },
  PathDef {
    width: None,
    height: None,
    fill: None,
    stroke: None,
    extrusion_allowed: None,
    commands: TEXT_DEFLATE_INFLATE_DEFLATE_PATH_3_COMMANDS,
  },
  PathDef {
    width: None,
    height: None,
    fill: None,
    stroke: None,
    extrusion_allowed: None,
    commands: TEXT_DEFLATE_INFLATE_DEFLATE_PATH_4_COMMANDS,
  },
  PathDef {
    width: None,
    height: None,
    fill: None,
    stroke: None,
    extrusion_allowed: None,
    commands: TEXT_DEFLATE_INFLATE_DEFLATE_PATH_5_COMMANDS,
  },
];
const TEXT_DEFLATE_INFLATE_DEFLATE: Definition = Definition {
  adjustments: TEXT_DEFLATE_INFLATE_DEFLATE_ADJUSTMENTS,
  guides: TEXT_DEFLATE_INFLATE_DEFLATE_GUIDES,
  paths: TEXT_DEFLATE_INFLATE_DEFLATE_PATHS,
};

const TEXT_DEFLATE_TOP_ADJUSTMENTS: &[GuideDef] = &[GuideDef {
  name: "adj",
  formula: "val 50000",
}];
const TEXT_DEFLATE_TOP_GUIDES: &[GuideDef] = &[
  GuideDef {
    name: "a",
    formula: "pin 0 adj 93750",
  },
  GuideDef {
    name: "dy",
    formula: "*/ a h 100000",
  },
  GuideDef {
    name: "y1",
    formula: "+- t dy 0",
  },
  GuideDef {
    name: "cp",
    formula: "+- y1 dy 0",
  },
];
const TEXT_DEFLATE_TOP_PATH_0_COMMANDS: &[PathCommandDef] = &[
  PathCommandDef::MoveTo(PointDef { x: "l", y: "t" }),
  PathCommandDef::QuadraticTo(&[PointDef { x: "hc", y: "cp" }, PointDef { x: "r", y: "t" }]),
];
const TEXT_DEFLATE_TOP_PATH_1_COMMANDS: &[PathCommandDef] = &[
  PathCommandDef::MoveTo(PointDef { x: "l", y: "b" }),
  PathCommandDef::LineTo(PointDef { x: "r", y: "b" }),
];
const TEXT_DEFLATE_TOP_PATHS: &[PathDef] = &[
  PathDef {
    width: None,
    height: None,
    fill: None,
    stroke: None,
    extrusion_allowed: None,
    commands: TEXT_DEFLATE_TOP_PATH_0_COMMANDS,
  },
  PathDef {
    width: None,
    height: None,
    fill: None,
    stroke: None,
    extrusion_allowed: None,
    commands: TEXT_DEFLATE_TOP_PATH_1_COMMANDS,
  },
];
const TEXT_DEFLATE_TOP: Definition = Definition {
  adjustments: TEXT_DEFLATE_TOP_ADJUSTMENTS,
  guides: TEXT_DEFLATE_TOP_GUIDES,
  paths: TEXT_DEFLATE_TOP_PATHS,
};

const TEXT_DOUBLE_WAVE1_ADJUSTMENTS: &[GuideDef] = &[
  GuideDef {
    name: "adj1",
    formula: "val 6250",
  },
  GuideDef {
    name: "adj2",
    formula: "val 0",
  },
];
const TEXT_DOUBLE_WAVE1_GUIDES: &[GuideDef] = &[
  GuideDef {
    name: "a1",
    formula: "pin 0 adj1 12500",
  },
  GuideDef {
    name: "a2",
    formula: "pin -10000 adj2 10000",
  },
  GuideDef {
    name: "y1",
    formula: "*/ h a1 100000",
  },
  GuideDef {
    name: "dy2",
    formula: "*/ y1 10 3",
  },
  GuideDef {
    name: "y2",
    formula: "+- y1 0 dy2",
  },
  GuideDef {
    name: "y3",
    formula: "+- y1 dy2 0",
  },
  GuideDef {
    name: "y4",
    formula: "+- b 0 y1",
  },
  GuideDef {
    name: "y5",
    formula: "+- y4 0 dy2",
  },
  GuideDef {
    name: "y6",
    formula: "+- y4 dy2 0",
  },
  GuideDef {
    name: "of",
    formula: "*/ w a2 100000",
  },
  GuideDef {
    name: "of2",
    formula: "*/ w a2 50000",
  },
  GuideDef {
    name: "x1",
    formula: "abs of",
  },
  GuideDef {
    name: "dx2",
    formula: "?: of2 0 of2",
  },
  GuideDef {
    name: "x2",
    formula: "+- l 0 dx2",
  },
  GuideDef {
    name: "dx8",
    formula: "?: of2 of2 0",
  },
  GuideDef {
    name: "x8",
    formula: "+- r 0 dx8",
  },
  GuideDef {
    name: "dx3",
    formula: "+/ dx2 x8 6",
  },
  GuideDef {
    name: "x3",
    formula: "+- x2 dx3 0",
  },
  GuideDef {
    name: "dx4",
    formula: "+/ dx2 x8 3",
  },
  GuideDef {
    name: "x4",
    formula: "+- x2 dx4 0",
  },
  GuideDef {
    name: "x5",
    formula: "+/ x2 x8 2",
  },
  GuideDef {
    name: "x6",
    formula: "+- x5 dx3 0",
  },
  GuideDef {
    name: "x7",
    formula: "+/ x6 x8 2",
  },
  GuideDef {
    name: "x9",
    formula: "+- l dx8 0",
  },
  GuideDef {
    name: "x15",
    formula: "+- r dx2 0",
  },
  GuideDef {
    name: "x10",
    formula: "+- x9 dx3 0",
  },
  GuideDef {
    name: "x11",
    formula: "+- x9 dx4 0",
  },
  GuideDef {
    name: "x12",
    formula: "+/ x9 x15 2",
  },
  GuideDef {
    name: "x13",
    formula: "+- x12 dx3 0",
  },
  GuideDef {
    name: "x14",
    formula: "+/ x13 x15 2",
  },
  GuideDef {
    name: "x16",
    formula: "+- r 0 x1",
  },
  GuideDef {
    name: "xAdj",
    formula: "+- hc of 0",
  },
];
const TEXT_DOUBLE_WAVE1_PATH_0_COMMANDS: &[PathCommandDef] = &[
  PathCommandDef::MoveTo(PointDef { x: "x2", y: "y1" }),
  PathCommandDef::CubicTo(&[
    PointDef { x: "x3", y: "y2" },
    PointDef { x: "x4", y: "y3" },
    PointDef { x: "x5", y: "y1" },
  ]),
  PathCommandDef::CubicTo(&[
    PointDef { x: "x6", y: "y2" },
    PointDef { x: "x7", y: "y3" },
    PointDef { x: "x8", y: "y1" },
  ]),
];
const TEXT_DOUBLE_WAVE1_PATH_1_COMMANDS: &[PathCommandDef] = &[
  PathCommandDef::MoveTo(PointDef { x: "x9", y: "y4" }),
  PathCommandDef::CubicTo(&[
    PointDef { x: "x10", y: "y5" },
    PointDef { x: "x11", y: "y6" },
    PointDef { x: "x12", y: "y4" },
  ]),
  PathCommandDef::CubicTo(&[
    PointDef { x: "x13", y: "y5" },
    PointDef { x: "x14", y: "y6" },
    PointDef { x: "x15", y: "y4" },
  ]),
];
const TEXT_DOUBLE_WAVE1_PATHS: &[PathDef] = &[
  PathDef {
    width: None,
    height: None,
    fill: None,
    stroke: None,
    extrusion_allowed: None,
    commands: TEXT_DOUBLE_WAVE1_PATH_0_COMMANDS,
  },
  PathDef {
    width: None,
    height: None,
    fill: None,
    stroke: None,
    extrusion_allowed: None,
    commands: TEXT_DOUBLE_WAVE1_PATH_1_COMMANDS,
  },
];
const TEXT_DOUBLE_WAVE1: Definition = Definition {
  adjustments: TEXT_DOUBLE_WAVE1_ADJUSTMENTS,
  guides: TEXT_DOUBLE_WAVE1_GUIDES,
  paths: TEXT_DOUBLE_WAVE1_PATHS,
};

const TEXT_FADE_DOWN_ADJUSTMENTS: &[GuideDef] = &[GuideDef {
  name: "adj",
  formula: "val 33333",
}];
const TEXT_FADE_DOWN_GUIDES: &[GuideDef] = &[
  GuideDef {
    name: "a",
    formula: "pin 0 adj 49999",
  },
  GuideDef {
    name: "dx",
    formula: "*/ a w 100000",
  },
  GuideDef {
    name: "x1",
    formula: "+- l dx 0",
  },
  GuideDef {
    name: "x2",
    formula: "+- r 0 dx",
  },
];
const TEXT_FADE_DOWN_PATH_0_COMMANDS: &[PathCommandDef] = &[
  PathCommandDef::MoveTo(PointDef { x: "l", y: "t" }),
  PathCommandDef::LineTo(PointDef { x: "r", y: "t" }),
];
const TEXT_FADE_DOWN_PATH_1_COMMANDS: &[PathCommandDef] = &[
  PathCommandDef::MoveTo(PointDef { x: "x1", y: "b" }),
  PathCommandDef::LineTo(PointDef { x: "x2", y: "b" }),
];
const TEXT_FADE_DOWN_PATHS: &[PathDef] = &[
  PathDef {
    width: None,
    height: None,
    fill: None,
    stroke: None,
    extrusion_allowed: None,
    commands: TEXT_FADE_DOWN_PATH_0_COMMANDS,
  },
  PathDef {
    width: None,
    height: None,
    fill: None,
    stroke: None,
    extrusion_allowed: None,
    commands: TEXT_FADE_DOWN_PATH_1_COMMANDS,
  },
];
const TEXT_FADE_DOWN: Definition = Definition {
  adjustments: TEXT_FADE_DOWN_ADJUSTMENTS,
  guides: TEXT_FADE_DOWN_GUIDES,
  paths: TEXT_FADE_DOWN_PATHS,
};

const TEXT_FADE_LEFT_ADJUSTMENTS: &[GuideDef] = &[GuideDef {
  name: "adj",
  formula: "val 33333",
}];
const TEXT_FADE_LEFT_GUIDES: &[GuideDef] = &[
  GuideDef {
    name: "a",
    formula: "pin 0 adj 49999",
  },
  GuideDef {
    name: "dy",
    formula: "*/ a h 100000",
  },
  GuideDef {
    name: "y1",
    formula: "+- t dy 0",
  },
  GuideDef {
    name: "y2",
    formula: "+- b 0 dy",
  },
];
const TEXT_FADE_LEFT_PATH_0_COMMANDS: &[PathCommandDef] = &[
  PathCommandDef::MoveTo(PointDef { x: "l", y: "y1" }),
  PathCommandDef::LineTo(PointDef { x: "r", y: "t" }),
];
const TEXT_FADE_LEFT_PATH_1_COMMANDS: &[PathCommandDef] = &[
  PathCommandDef::MoveTo(PointDef { x: "l", y: "y2" }),
  PathCommandDef::LineTo(PointDef { x: "r", y: "b" }),
];
const TEXT_FADE_LEFT_PATHS: &[PathDef] = &[
  PathDef {
    width: None,
    height: None,
    fill: None,
    stroke: None,
    extrusion_allowed: None,
    commands: TEXT_FADE_LEFT_PATH_0_COMMANDS,
  },
  PathDef {
    width: None,
    height: None,
    fill: None,
    stroke: None,
    extrusion_allowed: None,
    commands: TEXT_FADE_LEFT_PATH_1_COMMANDS,
  },
];
const TEXT_FADE_LEFT: Definition = Definition {
  adjustments: TEXT_FADE_LEFT_ADJUSTMENTS,
  guides: TEXT_FADE_LEFT_GUIDES,
  paths: TEXT_FADE_LEFT_PATHS,
};

const TEXT_FADE_RIGHT_ADJUSTMENTS: &[GuideDef] = &[GuideDef {
  name: "adj",
  formula: "val 33333",
}];
const TEXT_FADE_RIGHT_GUIDES: &[GuideDef] = &[
  GuideDef {
    name: "a",
    formula: "pin 0 adj 49999",
  },
  GuideDef {
    name: "dy",
    formula: "*/ a h 100000",
  },
  GuideDef {
    name: "y1",
    formula: "+- t dy 0",
  },
  GuideDef {
    name: "y2",
    formula: "+- b 0 dy",
  },
];
const TEXT_FADE_RIGHT_PATH_0_COMMANDS: &[PathCommandDef] = &[
  PathCommandDef::MoveTo(PointDef { x: "l", y: "t" }),
  PathCommandDef::LineTo(PointDef { x: "r", y: "y1" }),
];
const TEXT_FADE_RIGHT_PATH_1_COMMANDS: &[PathCommandDef] = &[
  PathCommandDef::MoveTo(PointDef { x: "l", y: "b" }),
  PathCommandDef::LineTo(PointDef { x: "r", y: "y2" }),
];
const TEXT_FADE_RIGHT_PATHS: &[PathDef] = &[
  PathDef {
    width: None,
    height: None,
    fill: None,
    stroke: None,
    extrusion_allowed: None,
    commands: TEXT_FADE_RIGHT_PATH_0_COMMANDS,
  },
  PathDef {
    width: None,
    height: None,
    fill: None,
    stroke: None,
    extrusion_allowed: None,
    commands: TEXT_FADE_RIGHT_PATH_1_COMMANDS,
  },
];
const TEXT_FADE_RIGHT: Definition = Definition {
  adjustments: TEXT_FADE_RIGHT_ADJUSTMENTS,
  guides: TEXT_FADE_RIGHT_GUIDES,
  paths: TEXT_FADE_RIGHT_PATHS,
};

const TEXT_FADE_UP_ADJUSTMENTS: &[GuideDef] = &[GuideDef {
  name: "adj",
  formula: "val 33333",
}];
const TEXT_FADE_UP_GUIDES: &[GuideDef] = &[
  GuideDef {
    name: "a",
    formula: "pin 0 adj 49999",
  },
  GuideDef {
    name: "dx",
    formula: "*/ a w 100000",
  },
  GuideDef {
    name: "x1",
    formula: "+- l dx 0",
  },
  GuideDef {
    name: "x2",
    formula: "+- r 0 dx",
  },
];
const TEXT_FADE_UP_PATH_0_COMMANDS: &[PathCommandDef] = &[
  PathCommandDef::MoveTo(PointDef { x: "x1", y: "t" }),
  PathCommandDef::LineTo(PointDef { x: "x2", y: "t" }),
];
const TEXT_FADE_UP_PATH_1_COMMANDS: &[PathCommandDef] = &[
  PathCommandDef::MoveTo(PointDef { x: "l", y: "b" }),
  PathCommandDef::LineTo(PointDef { x: "r", y: "b" }),
];
const TEXT_FADE_UP_PATHS: &[PathDef] = &[
  PathDef {
    width: None,
    height: None,
    fill: None,
    stroke: None,
    extrusion_allowed: None,
    commands: TEXT_FADE_UP_PATH_0_COMMANDS,
  },
  PathDef {
    width: None,
    height: None,
    fill: None,
    stroke: None,
    extrusion_allowed: None,
    commands: TEXT_FADE_UP_PATH_1_COMMANDS,
  },
];
const TEXT_FADE_UP: Definition = Definition {
  adjustments: TEXT_FADE_UP_ADJUSTMENTS,
  guides: TEXT_FADE_UP_GUIDES,
  paths: TEXT_FADE_UP_PATHS,
};

const TEXT_INFLATE_ADJUSTMENTS: &[GuideDef] = &[GuideDef {
  name: "adj",
  formula: "val 18750",
}];
const TEXT_INFLATE_GUIDES: &[GuideDef] = &[
  GuideDef {
    name: "a",
    formula: "pin 0 adj 20000",
  },
  GuideDef {
    name: "dy",
    formula: "*/ a h 100000",
  },
  GuideDef {
    name: "gd",
    formula: "*/ dy 1 3",
  },
  GuideDef {
    name: "gd0",
    formula: "+- 0 0 gd",
  },
  GuideDef {
    name: "gd1",
    formula: "+- h 0 gd0",
  },
  GuideDef {
    name: "ty",
    formula: "+- t dy 0",
  },
  GuideDef {
    name: "by",
    formula: "+- b 0 dy",
  },
  GuideDef {
    name: "y0",
    formula: "+- t gd0 0",
  },
  GuideDef {
    name: "y1",
    formula: "+- t gd1 0",
  },
  GuideDef {
    name: "x0",
    formula: "+- l wd3 0",
  },
  GuideDef {
    name: "x1",
    formula: "+- r 0 wd3",
  },
];
const TEXT_INFLATE_PATH_0_COMMANDS: &[PathCommandDef] = &[
  PathCommandDef::MoveTo(PointDef { x: "l", y: "ty" }),
  PathCommandDef::CubicTo(&[
    PointDef { x: "x0", y: "y0" },
    PointDef { x: "x1", y: "y0" },
    PointDef { x: "r", y: "ty" },
  ]),
];
const TEXT_INFLATE_PATH_1_COMMANDS: &[PathCommandDef] = &[
  PathCommandDef::MoveTo(PointDef { x: "l", y: "by" }),
  PathCommandDef::CubicTo(&[
    PointDef { x: "x0", y: "y1" },
    PointDef { x: "x1", y: "y1" },
    PointDef { x: "r", y: "by" },
  ]),
];
const TEXT_INFLATE_PATHS: &[PathDef] = &[
  PathDef {
    width: None,
    height: None,
    fill: None,
    stroke: None,
    extrusion_allowed: None,
    commands: TEXT_INFLATE_PATH_0_COMMANDS,
  },
  PathDef {
    width: None,
    height: None,
    fill: None,
    stroke: None,
    extrusion_allowed: None,
    commands: TEXT_INFLATE_PATH_1_COMMANDS,
  },
];
const TEXT_INFLATE: Definition = Definition {
  adjustments: TEXT_INFLATE_ADJUSTMENTS,
  guides: TEXT_INFLATE_GUIDES,
  paths: TEXT_INFLATE_PATHS,
};

const TEXT_INFLATE_BOTTOM_ADJUSTMENTS: &[GuideDef] = &[GuideDef {
  name: "adj",
  formula: "val 60000",
}];
const TEXT_INFLATE_BOTTOM_GUIDES: &[GuideDef] = &[
  GuideDef {
    name: "a",
    formula: "pin 60000 adj 100000",
  },
  GuideDef {
    name: "dy",
    formula: "*/ a h 100000",
  },
  GuideDef {
    name: "ty",
    formula: "+- t dy 0",
  },
];
const TEXT_INFLATE_BOTTOM_PATH_0_COMMANDS: &[PathCommandDef] = &[
  PathCommandDef::MoveTo(PointDef { x: "l", y: "t" }),
  PathCommandDef::LineTo(PointDef { x: "r", y: "t" }),
];
const TEXT_INFLATE_BOTTOM_PATH_1_COMMANDS: &[PathCommandDef] = &[
  PathCommandDef::MoveTo(PointDef { x: "l", y: "ty" }),
  PathCommandDef::QuadraticTo(&[PointDef { x: "hc", y: "b" }, PointDef { x: "r", y: "ty" }]),
];
const TEXT_INFLATE_BOTTOM_PATHS: &[PathDef] = &[
  PathDef {
    width: None,
    height: None,
    fill: None,
    stroke: None,
    extrusion_allowed: None,
    commands: TEXT_INFLATE_BOTTOM_PATH_0_COMMANDS,
  },
  PathDef {
    width: None,
    height: None,
    fill: None,
    stroke: None,
    extrusion_allowed: None,
    commands: TEXT_INFLATE_BOTTOM_PATH_1_COMMANDS,
  },
];
const TEXT_INFLATE_BOTTOM: Definition = Definition {
  adjustments: TEXT_INFLATE_BOTTOM_ADJUSTMENTS,
  guides: TEXT_INFLATE_BOTTOM_GUIDES,
  paths: TEXT_INFLATE_BOTTOM_PATHS,
};

const TEXT_INFLATE_TOP_ADJUSTMENTS: &[GuideDef] = &[GuideDef {
  name: "adj",
  formula: "val 40000",
}];
const TEXT_INFLATE_TOP_GUIDES: &[GuideDef] = &[
  GuideDef {
    name: "a",
    formula: "pin 0 adj 50000",
  },
  GuideDef {
    name: "dy",
    formula: "*/ a h 100000",
  },
  GuideDef {
    name: "ty",
    formula: "+- t dy 0",
  },
];
const TEXT_INFLATE_TOP_PATH_0_COMMANDS: &[PathCommandDef] = &[
  PathCommandDef::MoveTo(PointDef { x: "l", y: "ty" }),
  PathCommandDef::QuadraticTo(&[PointDef { x: "hc", y: "t" }, PointDef { x: "r", y: "ty" }]),
];
const TEXT_INFLATE_TOP_PATH_1_COMMANDS: &[PathCommandDef] = &[
  PathCommandDef::MoveTo(PointDef { x: "l", y: "b" }),
  PathCommandDef::LineTo(PointDef { x: "r", y: "b" }),
];
const TEXT_INFLATE_TOP_PATHS: &[PathDef] = &[
  PathDef {
    width: None,
    height: None,
    fill: None,
    stroke: None,
    extrusion_allowed: None,
    commands: TEXT_INFLATE_TOP_PATH_0_COMMANDS,
  },
  PathDef {
    width: None,
    height: None,
    fill: None,
    stroke: None,
    extrusion_allowed: None,
    commands: TEXT_INFLATE_TOP_PATH_1_COMMANDS,
  },
];
const TEXT_INFLATE_TOP: Definition = Definition {
  adjustments: TEXT_INFLATE_TOP_ADJUSTMENTS,
  guides: TEXT_INFLATE_TOP_GUIDES,
  paths: TEXT_INFLATE_TOP_PATHS,
};

const TEXT_PLAIN_ADJUSTMENTS: &[GuideDef] = &[GuideDef {
  name: "adj",
  formula: "val 50000",
}];
const TEXT_PLAIN_GUIDES: &[GuideDef] = &[
  GuideDef {
    name: "a",
    formula: "pin 30000 adj 70000",
  },
  GuideDef {
    name: "mid",
    formula: "*/ a w 100000",
  },
  GuideDef {
    name: "midDir",
    formula: "+- mid 0 hc",
  },
  GuideDef {
    name: "dl",
    formula: "+- mid 0 l",
  },
  GuideDef {
    name: "dr",
    formula: "+- r 0 mid",
  },
  GuideDef {
    name: "dl2",
    formula: "*/ dl 2 1",
  },
  GuideDef {
    name: "dr2",
    formula: "*/ dr 2 1",
  },
  GuideDef {
    name: "dx",
    formula: "?: midDir dr2 dl2",
  },
  GuideDef {
    name: "xr",
    formula: "+- l dx 0",
  },
  GuideDef {
    name: "xl",
    formula: "+- r 0 dx",
  },
  GuideDef {
    name: "tlx",
    formula: "?: midDir l xl",
  },
  GuideDef {
    name: "trx",
    formula: "?: midDir xr r",
  },
  GuideDef {
    name: "blx",
    formula: "?: midDir xl l",
  },
  GuideDef {
    name: "brx",
    formula: "?: midDir r xr",
  },
];
const TEXT_PLAIN_PATH_0_COMMANDS: &[PathCommandDef] = &[
  PathCommandDef::MoveTo(PointDef { x: "tlx", y: "t" }),
  PathCommandDef::LineTo(PointDef { x: "trx", y: "t" }),
];
const TEXT_PLAIN_PATH_1_COMMANDS: &[PathCommandDef] = &[
  PathCommandDef::MoveTo(PointDef { x: "blx", y: "b" }),
  PathCommandDef::LineTo(PointDef { x: "brx", y: "b" }),
];
const TEXT_PLAIN_PATHS: &[PathDef] = &[
  PathDef {
    width: None,
    height: None,
    fill: None,
    stroke: None,
    extrusion_allowed: None,
    commands: TEXT_PLAIN_PATH_0_COMMANDS,
  },
  PathDef {
    width: None,
    height: None,
    fill: None,
    stroke: None,
    extrusion_allowed: None,
    commands: TEXT_PLAIN_PATH_1_COMMANDS,
  },
];
const TEXT_PLAIN: Definition = Definition {
  adjustments: TEXT_PLAIN_ADJUSTMENTS,
  guides: TEXT_PLAIN_GUIDES,
  paths: TEXT_PLAIN_PATHS,
};

const TEXT_RING_INSIDE_ADJUSTMENTS: &[GuideDef] = &[GuideDef {
  name: "adj",
  formula: "val 60000",
}];
const TEXT_RING_INSIDE_GUIDES: &[GuideDef] = &[
  GuideDef {
    name: "a",
    formula: "pin 50000 adj 99000",
  },
  GuideDef {
    name: "dy",
    formula: "*/ a h 100000",
  },
  GuideDef {
    name: "y",
    formula: "+- t dy 0",
  },
  GuideDef {
    name: "r",
    formula: "*/ dy 1 2",
  },
  GuideDef {
    name: "y1",
    formula: "+- t r 0",
  },
  GuideDef {
    name: "y2",
    formula: "+- b 0 r",
  },
];
const TEXT_RING_INSIDE_PATH_0_COMMANDS: &[PathCommandDef] = &[
  PathCommandDef::MoveTo(PointDef { x: "l", y: "y1" }),
  PathCommandDef::ArcTo {
    width_radius: "wd2",
    height_radius: "r",
    start_angle: "10800000",
    sweep_angle: "21599999",
  },
];
const TEXT_RING_INSIDE_PATH_1_COMMANDS: &[PathCommandDef] = &[
  PathCommandDef::MoveTo(PointDef { x: "l", y: "y2" }),
  PathCommandDef::ArcTo {
    width_radius: "wd2",
    height_radius: "r",
    start_angle: "10800000",
    sweep_angle: "21599999",
  },
];
const TEXT_RING_INSIDE_PATHS: &[PathDef] = &[
  PathDef {
    width: None,
    height: None,
    fill: None,
    stroke: None,
    extrusion_allowed: None,
    commands: TEXT_RING_INSIDE_PATH_0_COMMANDS,
  },
  PathDef {
    width: None,
    height: None,
    fill: None,
    stroke: None,
    extrusion_allowed: None,
    commands: TEXT_RING_INSIDE_PATH_1_COMMANDS,
  },
];
const TEXT_RING_INSIDE: Definition = Definition {
  adjustments: TEXT_RING_INSIDE_ADJUSTMENTS,
  guides: TEXT_RING_INSIDE_GUIDES,
  paths: TEXT_RING_INSIDE_PATHS,
};

const TEXT_RING_OUTSIDE_ADJUSTMENTS: &[GuideDef] = &[GuideDef {
  name: "adj",
  formula: "val 60000",
}];
const TEXT_RING_OUTSIDE_GUIDES: &[GuideDef] = &[
  GuideDef {
    name: "a",
    formula: "pin 50000 adj 99000",
  },
  GuideDef {
    name: "dy",
    formula: "*/ a h 100000",
  },
  GuideDef {
    name: "y",
    formula: "+- t dy 0",
  },
  GuideDef {
    name: "r",
    formula: "*/ dy 1 2",
  },
  GuideDef {
    name: "y1",
    formula: "+- t r 0",
  },
  GuideDef {
    name: "y2",
    formula: "+- b 0 r",
  },
];
const TEXT_RING_OUTSIDE_PATH_0_COMMANDS: &[PathCommandDef] = &[
  PathCommandDef::MoveTo(PointDef { x: "l", y: "y1" }),
  PathCommandDef::ArcTo {
    width_radius: "wd2",
    height_radius: "r",
    start_angle: "10800000",
    sweep_angle: "-21599999",
  },
];
const TEXT_RING_OUTSIDE_PATH_1_COMMANDS: &[PathCommandDef] = &[
  PathCommandDef::MoveTo(PointDef { x: "l", y: "y2" }),
  PathCommandDef::ArcTo {
    width_radius: "wd2",
    height_radius: "r",
    start_angle: "10800000",
    sweep_angle: "-21599999",
  },
];
const TEXT_RING_OUTSIDE_PATHS: &[PathDef] = &[
  PathDef {
    width: None,
    height: None,
    fill: None,
    stroke: None,
    extrusion_allowed: None,
    commands: TEXT_RING_OUTSIDE_PATH_0_COMMANDS,
  },
  PathDef {
    width: None,
    height: None,
    fill: None,
    stroke: None,
    extrusion_allowed: None,
    commands: TEXT_RING_OUTSIDE_PATH_1_COMMANDS,
  },
];
const TEXT_RING_OUTSIDE: Definition = Definition {
  adjustments: TEXT_RING_OUTSIDE_ADJUSTMENTS,
  guides: TEXT_RING_OUTSIDE_GUIDES,
  paths: TEXT_RING_OUTSIDE_PATHS,
};

const TEXT_SLANT_DOWN_ADJUSTMENTS: &[GuideDef] = &[GuideDef {
  name: "adj",
  formula: "val 44445",
}];
const TEXT_SLANT_DOWN_GUIDES: &[GuideDef] = &[
  GuideDef {
    name: "a",
    formula: "pin 28569 adj 100000",
  },
  GuideDef {
    name: "dy",
    formula: "*/ a h 100000",
  },
  GuideDef {
    name: "y1",
    formula: "+- t dy 0",
  },
  GuideDef {
    name: "y2",
    formula: "+- b 0 dy",
  },
];
const TEXT_SLANT_DOWN_PATH_0_COMMANDS: &[PathCommandDef] = &[
  PathCommandDef::MoveTo(PointDef { x: "l", y: "t" }),
  PathCommandDef::LineTo(PointDef { x: "r", y: "y2" }),
];
const TEXT_SLANT_DOWN_PATH_1_COMMANDS: &[PathCommandDef] = &[
  PathCommandDef::MoveTo(PointDef { x: "l", y: "y1" }),
  PathCommandDef::LineTo(PointDef { x: "r", y: "b" }),
];
const TEXT_SLANT_DOWN_PATHS: &[PathDef] = &[
  PathDef {
    width: None,
    height: None,
    fill: None,
    stroke: None,
    extrusion_allowed: None,
    commands: TEXT_SLANT_DOWN_PATH_0_COMMANDS,
  },
  PathDef {
    width: None,
    height: None,
    fill: None,
    stroke: None,
    extrusion_allowed: None,
    commands: TEXT_SLANT_DOWN_PATH_1_COMMANDS,
  },
];
const TEXT_SLANT_DOWN: Definition = Definition {
  adjustments: TEXT_SLANT_DOWN_ADJUSTMENTS,
  guides: TEXT_SLANT_DOWN_GUIDES,
  paths: TEXT_SLANT_DOWN_PATHS,
};

const TEXT_SLANT_UP_ADJUSTMENTS: &[GuideDef] = &[GuideDef {
  name: "adj",
  formula: "val 55555",
}];
const TEXT_SLANT_UP_GUIDES: &[GuideDef] = &[
  GuideDef {
    name: "a",
    formula: "pin 0 adj 71431",
  },
  GuideDef {
    name: "dy",
    formula: "*/ a h 100000",
  },
  GuideDef {
    name: "y1",
    formula: "+- t dy 0",
  },
  GuideDef {
    name: "y2",
    formula: "+- b 0 dy",
  },
];
const TEXT_SLANT_UP_PATH_0_COMMANDS: &[PathCommandDef] = &[
  PathCommandDef::MoveTo(PointDef { x: "l", y: "y1" }),
  PathCommandDef::LineTo(PointDef { x: "r", y: "t" }),
];
const TEXT_SLANT_UP_PATH_1_COMMANDS: &[PathCommandDef] = &[
  PathCommandDef::MoveTo(PointDef { x: "l", y: "b" }),
  PathCommandDef::LineTo(PointDef { x: "r", y: "y2" }),
];
const TEXT_SLANT_UP_PATHS: &[PathDef] = &[
  PathDef {
    width: None,
    height: None,
    fill: None,
    stroke: None,
    extrusion_allowed: None,
    commands: TEXT_SLANT_UP_PATH_0_COMMANDS,
  },
  PathDef {
    width: None,
    height: None,
    fill: None,
    stroke: None,
    extrusion_allowed: None,
    commands: TEXT_SLANT_UP_PATH_1_COMMANDS,
  },
];
const TEXT_SLANT_UP: Definition = Definition {
  adjustments: TEXT_SLANT_UP_ADJUSTMENTS,
  guides: TEXT_SLANT_UP_GUIDES,
  paths: TEXT_SLANT_UP_PATHS,
};

const TEXT_STOP_ADJUSTMENTS: &[GuideDef] = &[GuideDef {
  name: "adj",
  formula: "val 25000",
}];
const TEXT_STOP_GUIDES: &[GuideDef] = &[
  GuideDef {
    name: "a",
    formula: "pin 14286 adj 50000",
  },
  GuideDef {
    name: "dx",
    formula: "*/ w 1 3",
  },
  GuideDef {
    name: "dy",
    formula: "*/ a h 100000",
  },
  GuideDef {
    name: "x1",
    formula: "+- l dx 0",
  },
  GuideDef {
    name: "x2",
    formula: "+- r 0 dx",
  },
  GuideDef {
    name: "y1",
    formula: "+- t dy 0",
  },
  GuideDef {
    name: "y2",
    formula: "+- b 0 dy",
  },
];
const TEXT_STOP_PATH_0_COMMANDS: &[PathCommandDef] = &[
  PathCommandDef::MoveTo(PointDef { x: "l", y: "y1" }),
  PathCommandDef::LineTo(PointDef { x: "x1", y: "t" }),
  PathCommandDef::LineTo(PointDef { x: "x2", y: "t" }),
  PathCommandDef::LineTo(PointDef { x: "r", y: "y1" }),
];
const TEXT_STOP_PATH_1_COMMANDS: &[PathCommandDef] = &[
  PathCommandDef::MoveTo(PointDef { x: "l", y: "y2" }),
  PathCommandDef::LineTo(PointDef { x: "x1", y: "b" }),
  PathCommandDef::LineTo(PointDef { x: "x2", y: "b" }),
  PathCommandDef::LineTo(PointDef { x: "r", y: "y2" }),
];
const TEXT_STOP_PATHS: &[PathDef] = &[
  PathDef {
    width: None,
    height: None,
    fill: None,
    stroke: None,
    extrusion_allowed: None,
    commands: TEXT_STOP_PATH_0_COMMANDS,
  },
  PathDef {
    width: None,
    height: None,
    fill: None,
    stroke: None,
    extrusion_allowed: None,
    commands: TEXT_STOP_PATH_1_COMMANDS,
  },
];
const TEXT_STOP: Definition = Definition {
  adjustments: TEXT_STOP_ADJUSTMENTS,
  guides: TEXT_STOP_GUIDES,
  paths: TEXT_STOP_PATHS,
};

const TEXT_TRIANGLE_ADJUSTMENTS: &[GuideDef] = &[GuideDef {
  name: "adj",
  formula: "val 50000",
}];
const TEXT_TRIANGLE_GUIDES: &[GuideDef] = &[
  GuideDef {
    name: "a",
    formula: "pin 0 adj 100000",
  },
  GuideDef {
    name: "y",
    formula: "*/ a h 100000",
  },
];
const TEXT_TRIANGLE_PATH_0_COMMANDS: &[PathCommandDef] = &[
  PathCommandDef::MoveTo(PointDef { x: "l", y: "y" }),
  PathCommandDef::LineTo(PointDef { x: "hc", y: "t" }),
  PathCommandDef::LineTo(PointDef { x: "r", y: "y" }),
];
const TEXT_TRIANGLE_PATH_1_COMMANDS: &[PathCommandDef] = &[
  PathCommandDef::MoveTo(PointDef { x: "l", y: "b" }),
  PathCommandDef::LineTo(PointDef { x: "r", y: "b" }),
];
const TEXT_TRIANGLE_PATHS: &[PathDef] = &[
  PathDef {
    width: None,
    height: None,
    fill: None,
    stroke: None,
    extrusion_allowed: None,
    commands: TEXT_TRIANGLE_PATH_0_COMMANDS,
  },
  PathDef {
    width: None,
    height: None,
    fill: None,
    stroke: None,
    extrusion_allowed: None,
    commands: TEXT_TRIANGLE_PATH_1_COMMANDS,
  },
];
const TEXT_TRIANGLE: Definition = Definition {
  adjustments: TEXT_TRIANGLE_ADJUSTMENTS,
  guides: TEXT_TRIANGLE_GUIDES,
  paths: TEXT_TRIANGLE_PATHS,
};

const TEXT_TRIANGLE_INVERTED_ADJUSTMENTS: &[GuideDef] = &[GuideDef {
  name: "adj",
  formula: "val 50000",
}];
const TEXT_TRIANGLE_INVERTED_GUIDES: &[GuideDef] = &[
  GuideDef {
    name: "a",
    formula: "pin 0 adj 100000",
  },
  GuideDef {
    name: "y",
    formula: "*/ a h 100000",
  },
];
const TEXT_TRIANGLE_INVERTED_PATH_0_COMMANDS: &[PathCommandDef] = &[
  PathCommandDef::MoveTo(PointDef { x: "l", y: "t" }),
  PathCommandDef::LineTo(PointDef { x: "r", y: "t" }),
];
const TEXT_TRIANGLE_INVERTED_PATH_1_COMMANDS: &[PathCommandDef] = &[
  PathCommandDef::MoveTo(PointDef { x: "l", y: "y" }),
  PathCommandDef::LineTo(PointDef { x: "hc", y: "b" }),
  PathCommandDef::LineTo(PointDef { x: "r", y: "y" }),
];
const TEXT_TRIANGLE_INVERTED_PATHS: &[PathDef] = &[
  PathDef {
    width: None,
    height: None,
    fill: None,
    stroke: None,
    extrusion_allowed: None,
    commands: TEXT_TRIANGLE_INVERTED_PATH_0_COMMANDS,
  },
  PathDef {
    width: None,
    height: None,
    fill: None,
    stroke: None,
    extrusion_allowed: None,
    commands: TEXT_TRIANGLE_INVERTED_PATH_1_COMMANDS,
  },
];
const TEXT_TRIANGLE_INVERTED: Definition = Definition {
  adjustments: TEXT_TRIANGLE_INVERTED_ADJUSTMENTS,
  guides: TEXT_TRIANGLE_INVERTED_GUIDES,
  paths: TEXT_TRIANGLE_INVERTED_PATHS,
};

const TEXT_WAVE1_ADJUSTMENTS: &[GuideDef] = &[
  GuideDef {
    name: "adj1",
    formula: "val 12500",
  },
  GuideDef {
    name: "adj2",
    formula: "val 0",
  },
];
const TEXT_WAVE1_GUIDES: &[GuideDef] = &[
  GuideDef {
    name: "a1",
    formula: "pin 0 adj1 20000",
  },
  GuideDef {
    name: "a2",
    formula: "pin -10000 adj2 10000",
  },
  GuideDef {
    name: "y1",
    formula: "*/ h a1 100000",
  },
  GuideDef {
    name: "dy2",
    formula: "*/ y1 10 3",
  },
  GuideDef {
    name: "y2",
    formula: "+- y1 0 dy2",
  },
  GuideDef {
    name: "y3",
    formula: "+- y1 dy2 0",
  },
  GuideDef {
    name: "y4",
    formula: "+- b 0 y1",
  },
  GuideDef {
    name: "y5",
    formula: "+- y4 0 dy2",
  },
  GuideDef {
    name: "y6",
    formula: "+- y4 dy2 0",
  },
  GuideDef {
    name: "of",
    formula: "*/ w a2 100000",
  },
  GuideDef {
    name: "of2",
    formula: "*/ w a2 50000",
  },
  GuideDef {
    name: "x1",
    formula: "abs of",
  },
  GuideDef {
    name: "dx2",
    formula: "?: of2 0 of2",
  },
  GuideDef {
    name: "x2",
    formula: "+- l 0 dx2",
  },
  GuideDef {
    name: "dx5",
    formula: "?: of2 of2 0",
  },
  GuideDef {
    name: "x5",
    formula: "+- r 0 dx5",
  },
  GuideDef {
    name: "dx3",
    formula: "+/ dx2 x5 3",
  },
  GuideDef {
    name: "x3",
    formula: "+- x2 dx3 0",
  },
  GuideDef {
    name: "x4",
    formula: "+/ x3 x5 2",
  },
  GuideDef {
    name: "x6",
    formula: "+- l dx5 0",
  },
  GuideDef {
    name: "x10",
    formula: "+- r dx2 0",
  },
  GuideDef {
    name: "x7",
    formula: "+- x6 dx3 0",
  },
  GuideDef {
    name: "x8",
    formula: "+/ x7 x10 2",
  },
  GuideDef {
    name: "x9",
    formula: "+- r 0 x1",
  },
  GuideDef {
    name: "xAdj",
    formula: "+- hc of 0",
  },
];
const TEXT_WAVE1_PATH_0_COMMANDS: &[PathCommandDef] = &[
  PathCommandDef::MoveTo(PointDef { x: "x2", y: "y1" }),
  PathCommandDef::CubicTo(&[
    PointDef { x: "x3", y: "y2" },
    PointDef { x: "x4", y: "y3" },
    PointDef { x: "x5", y: "y1" },
  ]),
];
const TEXT_WAVE1_PATH_1_COMMANDS: &[PathCommandDef] = &[
  PathCommandDef::MoveTo(PointDef { x: "x6", y: "y4" }),
  PathCommandDef::CubicTo(&[
    PointDef { x: "x7", y: "y5" },
    PointDef { x: "x8", y: "y6" },
    PointDef { x: "x10", y: "y4" },
  ]),
];
const TEXT_WAVE1_PATHS: &[PathDef] = &[
  PathDef {
    width: None,
    height: None,
    fill: None,
    stroke: None,
    extrusion_allowed: None,
    commands: TEXT_WAVE1_PATH_0_COMMANDS,
  },
  PathDef {
    width: None,
    height: None,
    fill: None,
    stroke: None,
    extrusion_allowed: None,
    commands: TEXT_WAVE1_PATH_1_COMMANDS,
  },
];
const TEXT_WAVE1: Definition = Definition {
  adjustments: TEXT_WAVE1_ADJUSTMENTS,
  guides: TEXT_WAVE1_GUIDES,
  paths: TEXT_WAVE1_PATHS,
};

const TEXT_WAVE2_ADJUSTMENTS: &[GuideDef] = &[
  GuideDef {
    name: "adj1",
    formula: "val 12500",
  },
  GuideDef {
    name: "adj2",
    formula: "val 0",
  },
];
const TEXT_WAVE2_GUIDES: &[GuideDef] = &[
  GuideDef {
    name: "a1",
    formula: "pin 0 adj1 20000",
  },
  GuideDef {
    name: "a2",
    formula: "pin -10000 adj2 10000",
  },
  GuideDef {
    name: "y1",
    formula: "*/ h a1 100000",
  },
  GuideDef {
    name: "dy2",
    formula: "*/ y1 10 3",
  },
  GuideDef {
    name: "y2",
    formula: "+- y1 0 dy2",
  },
  GuideDef {
    name: "y3",
    formula: "+- y1 dy2 0",
  },
  GuideDef {
    name: "y4",
    formula: "+- b 0 y1",
  },
  GuideDef {
    name: "y5",
    formula: "+- y4 0 dy2",
  },
  GuideDef {
    name: "y6",
    formula: "+- y4 dy2 0",
  },
  GuideDef {
    name: "of",
    formula: "*/ w a2 100000",
  },
  GuideDef {
    name: "of2",
    formula: "*/ w a2 50000",
  },
  GuideDef {
    name: "x1",
    formula: "abs of",
  },
  GuideDef {
    name: "dx2",
    formula: "?: of2 0 of2",
  },
  GuideDef {
    name: "x2",
    formula: "+- l 0 dx2",
  },
  GuideDef {
    name: "dx5",
    formula: "?: of2 of2 0",
  },
  GuideDef {
    name: "x5",
    formula: "+- r 0 dx5",
  },
  GuideDef {
    name: "dx3",
    formula: "+/ dx2 x5 3",
  },
  GuideDef {
    name: "x3",
    formula: "+- x2 dx3 0",
  },
  GuideDef {
    name: "x4",
    formula: "+/ x3 x5 2",
  },
  GuideDef {
    name: "x6",
    formula: "+- l dx5 0",
  },
  GuideDef {
    name: "x10",
    formula: "+- r dx2 0",
  },
  GuideDef {
    name: "x7",
    formula: "+- x6 dx3 0",
  },
  GuideDef {
    name: "x8",
    formula: "+/ x7 x10 2",
  },
  GuideDef {
    name: "x9",
    formula: "+- r 0 x1",
  },
  GuideDef {
    name: "xAdj",
    formula: "+- hc of 0",
  },
];
const TEXT_WAVE2_PATH_0_COMMANDS: &[PathCommandDef] = &[
  PathCommandDef::MoveTo(PointDef { x: "x2", y: "y1" }),
  PathCommandDef::CubicTo(&[
    PointDef { x: "x3", y: "y3" },
    PointDef { x: "x4", y: "y2" },
    PointDef { x: "x5", y: "y1" },
  ]),
];
const TEXT_WAVE2_PATH_1_COMMANDS: &[PathCommandDef] = &[
  PathCommandDef::MoveTo(PointDef { x: "x6", y: "y4" }),
  PathCommandDef::CubicTo(&[
    PointDef { x: "x7", y: "y6" },
    PointDef { x: "x8", y: "y5" },
    PointDef { x: "x10", y: "y4" },
  ]),
];
const TEXT_WAVE2_PATHS: &[PathDef] = &[
  PathDef {
    width: None,
    height: None,
    fill: None,
    stroke: None,
    extrusion_allowed: None,
    commands: TEXT_WAVE2_PATH_0_COMMANDS,
  },
  PathDef {
    width: None,
    height: None,
    fill: None,
    stroke: None,
    extrusion_allowed: None,
    commands: TEXT_WAVE2_PATH_1_COMMANDS,
  },
];
const TEXT_WAVE2: Definition = Definition {
  adjustments: TEXT_WAVE2_ADJUSTMENTS,
  guides: TEXT_WAVE2_GUIDES,
  paths: TEXT_WAVE2_PATHS,
};

const TEXT_WAVE4_ADJUSTMENTS: &[GuideDef] = &[
  GuideDef {
    name: "adj1",
    formula: "val 6250",
  },
  GuideDef {
    name: "adj2",
    formula: "val 0",
  },
];
const TEXT_WAVE4_GUIDES: &[GuideDef] = &[
  GuideDef {
    name: "a1",
    formula: "pin 0 adj1 12500",
  },
  GuideDef {
    name: "a2",
    formula: "pin -10000 adj2 10000",
  },
  GuideDef {
    name: "y1",
    formula: "*/ h a1 100000",
  },
  GuideDef {
    name: "dy2",
    formula: "*/ y1 10 3",
  },
  GuideDef {
    name: "y2",
    formula: "+- y1 0 dy2",
  },
  GuideDef {
    name: "y3",
    formula: "+- y1 dy2 0",
  },
  GuideDef {
    name: "y4",
    formula: "+- b 0 y1",
  },
  GuideDef {
    name: "y5",
    formula: "+- y4 0 dy2",
  },
  GuideDef {
    name: "y6",
    formula: "+- y4 dy2 0",
  },
  GuideDef {
    name: "of",
    formula: "*/ w a2 100000",
  },
  GuideDef {
    name: "of2",
    formula: "*/ w a2 50000",
  },
  GuideDef {
    name: "x1",
    formula: "abs of",
  },
  GuideDef {
    name: "dx2",
    formula: "?: of2 0 of2",
  },
  GuideDef {
    name: "x2",
    formula: "+- l 0 dx2",
  },
  GuideDef {
    name: "dx8",
    formula: "?: of2 of2 0",
  },
  GuideDef {
    name: "x8",
    formula: "+- r 0 dx8",
  },
  GuideDef {
    name: "dx3",
    formula: "+/ dx2 x8 6",
  },
  GuideDef {
    name: "x3",
    formula: "+- x2 dx3 0",
  },
  GuideDef {
    name: "dx4",
    formula: "+/ dx2 x8 3",
  },
  GuideDef {
    name: "x4",
    formula: "+- x2 dx4 0",
  },
  GuideDef {
    name: "x5",
    formula: "+/ x2 x8 2",
  },
  GuideDef {
    name: "x6",
    formula: "+- x5 dx3 0",
  },
  GuideDef {
    name: "x7",
    formula: "+/ x6 x8 2",
  },
  GuideDef {
    name: "x9",
    formula: "+- l dx8 0",
  },
  GuideDef {
    name: "x15",
    formula: "+- r dx2 0",
  },
  GuideDef {
    name: "x10",
    formula: "+- x9 dx3 0",
  },
  GuideDef {
    name: "x11",
    formula: "+- x9 dx4 0",
  },
  GuideDef {
    name: "x12",
    formula: "+/ x9 x15 2",
  },
  GuideDef {
    name: "x13",
    formula: "+- x12 dx3 0",
  },
  GuideDef {
    name: "x14",
    formula: "+/ x13 x15 2",
  },
  GuideDef {
    name: "x16",
    formula: "+- r 0 x1",
  },
  GuideDef {
    name: "xAdj",
    formula: "+- hc of 0",
  },
];
const TEXT_WAVE4_PATH_0_COMMANDS: &[PathCommandDef] = &[
  PathCommandDef::MoveTo(PointDef { x: "x2", y: "y1" }),
  PathCommandDef::CubicTo(&[
    PointDef { x: "x3", y: "y3" },
    PointDef { x: "x4", y: "y2" },
    PointDef { x: "x5", y: "y1" },
  ]),
  PathCommandDef::CubicTo(&[
    PointDef { x: "x6", y: "y3" },
    PointDef { x: "x7", y: "y2" },
    PointDef { x: "x8", y: "y1" },
  ]),
];
const TEXT_WAVE4_PATH_1_COMMANDS: &[PathCommandDef] = &[
  PathCommandDef::MoveTo(PointDef { x: "x9", y: "y4" }),
  PathCommandDef::CubicTo(&[
    PointDef { x: "x10", y: "y6" },
    PointDef { x: "x11", y: "y5" },
    PointDef { x: "x12", y: "y4" },
  ]),
  PathCommandDef::CubicTo(&[
    PointDef { x: "x13", y: "y6" },
    PointDef { x: "x14", y: "y5" },
    PointDef { x: "x15", y: "y4" },
  ]),
];
const TEXT_WAVE4_PATHS: &[PathDef] = &[
  PathDef {
    width: None,
    height: None,
    fill: None,
    stroke: None,
    extrusion_allowed: None,
    commands: TEXT_WAVE4_PATH_0_COMMANDS,
  },
  PathDef {
    width: None,
    height: None,
    fill: None,
    stroke: None,
    extrusion_allowed: None,
    commands: TEXT_WAVE4_PATH_1_COMMANDS,
  },
];
const TEXT_WAVE4: Definition = Definition {
  adjustments: TEXT_WAVE4_ADJUSTMENTS,
  guides: TEXT_WAVE4_GUIDES,
  paths: TEXT_WAVE4_PATHS,
};

pub(super) const DEFINITION_COUNT: usize = 40;
pub(super) const PATH_COUNT: usize = 88;

pub(super) fn definition(preset: a::TextShapeValues) -> Option<&'static Definition> {
  match preset {
    a::TextShapeValues::TextNoShape => None,
    a::TextShapeValues::TextArchDown => Some(&TEXT_ARCH_DOWN),
    a::TextShapeValues::TextArchDownPour => Some(&TEXT_ARCH_DOWN_POUR),
    a::TextShapeValues::TextArchUp => Some(&TEXT_ARCH_UP),
    a::TextShapeValues::TextArchUpPour => Some(&TEXT_ARCH_UP_POUR),
    a::TextShapeValues::TextButton => Some(&TEXT_BUTTON),
    a::TextShapeValues::TextButtonPour => Some(&TEXT_BUTTON_POUR),
    a::TextShapeValues::TextCanDown => Some(&TEXT_CAN_DOWN),
    a::TextShapeValues::TextCanUp => Some(&TEXT_CAN_UP),
    a::TextShapeValues::TextCascadeDown => Some(&TEXT_CASCADE_DOWN),
    a::TextShapeValues::TextCascadeUp => Some(&TEXT_CASCADE_UP),
    a::TextShapeValues::TextChevron => Some(&TEXT_CHEVRON),
    a::TextShapeValues::TextChevronInverted => Some(&TEXT_CHEVRON_INVERTED),
    a::TextShapeValues::TextCircle => Some(&TEXT_CIRCLE),
    a::TextShapeValues::TextCirclePour => Some(&TEXT_CIRCLE_POUR),
    a::TextShapeValues::TextCurveDown => Some(&TEXT_CURVE_DOWN),
    a::TextShapeValues::TextCurveUp => Some(&TEXT_CURVE_UP),
    a::TextShapeValues::TextDeflate => Some(&TEXT_DEFLATE),
    a::TextShapeValues::TextDeflateBottom => Some(&TEXT_DEFLATE_BOTTOM),
    a::TextShapeValues::TextDeflateInflate => Some(&TEXT_DEFLATE_INFLATE),
    a::TextShapeValues::TextDeflateInflateDeflate => Some(&TEXT_DEFLATE_INFLATE_DEFLATE),
    a::TextShapeValues::TextDeflateTop => Some(&TEXT_DEFLATE_TOP),
    a::TextShapeValues::TextDoubleWave1 => Some(&TEXT_DOUBLE_WAVE1),
    a::TextShapeValues::TextFadeDown => Some(&TEXT_FADE_DOWN),
    a::TextShapeValues::TextFadeLeft => Some(&TEXT_FADE_LEFT),
    a::TextShapeValues::TextFadeRight => Some(&TEXT_FADE_RIGHT),
    a::TextShapeValues::TextFadeUp => Some(&TEXT_FADE_UP),
    a::TextShapeValues::TextInflate => Some(&TEXT_INFLATE),
    a::TextShapeValues::TextInflateBottom => Some(&TEXT_INFLATE_BOTTOM),
    a::TextShapeValues::TextInflateTop => Some(&TEXT_INFLATE_TOP),
    a::TextShapeValues::TextPlain => Some(&TEXT_PLAIN),
    a::TextShapeValues::TextRingInside => Some(&TEXT_RING_INSIDE),
    a::TextShapeValues::TextRingOutside => Some(&TEXT_RING_OUTSIDE),
    a::TextShapeValues::TextSlantDown => Some(&TEXT_SLANT_DOWN),
    a::TextShapeValues::TextSlantUp => Some(&TEXT_SLANT_UP),
    a::TextShapeValues::TextStop => Some(&TEXT_STOP),
    a::TextShapeValues::TextTriangle => Some(&TEXT_TRIANGLE),
    a::TextShapeValues::TextTriangleInverted => Some(&TEXT_TRIANGLE_INVERTED),
    a::TextShapeValues::TextWave1 => Some(&TEXT_WAVE1),
    a::TextShapeValues::TextWave2 => Some(&TEXT_WAVE2),
    a::TextShapeValues::TextWave4 => Some(&TEXT_WAVE4),
  }
}
