use std::sync::Arc;

use crate::localization::{OfficeResourceLocale, OfficeStringCatalog};

use super::{TextStyle, WORD_ZH_STYLE_REF_ERROR_LINE_HEIGHT_PER_FONT_SIZE};

/// Text generated by Word while updating a field.
///
/// These strings are application resources rather than persisted document
/// content. ECMA-376 defines the field value but does not define missing-target
/// diagnostics, and MS-OI29500 §2.1.490 explicitly makes PAGEREF's relative
/// labels dependent on the current application UI as well as document text.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(super) enum FieldMessage<'a> {
  UndefinedBookmark,
  ReferenceSourceNotFound,
  BookmarkNameNotSpecified,
  MissingStyle(&'a str),
  EmptyTableOfContents,
  PageRefRelative { bookmark_is_above: bool },
  PageRefOnPage(&'a str),
}

pub(super) fn localized_field_message(
  message: FieldMessage<'_>,
  ui_language: Option<&str>,
) -> String {
  let strings = OfficeStringCatalog::for_ui_language(ui_language);
  match message {
    FieldMessage::UndefinedBookmark => strings.field_undefined_bookmark().to_string(),
    FieldMessage::ReferenceSourceNotFound => strings.field_reference_source_not_found().to_string(),
    FieldMessage::BookmarkNameNotSpecified => {
      strings.field_bookmark_name_not_specified().to_string()
    }
    FieldMessage::MissingStyle(style_name) => strings.field_missing_style(style_name),
    FieldMessage::EmptyTableOfContents => strings.field_empty_table_of_contents().to_string(),
    FieldMessage::PageRefRelative { bookmark_is_above } => if bookmark_is_above {
      strings.field_above()
    } else {
      strings.field_below()
    }
    .to_string(),
    FieldMessage::PageRefOnPage(page_number) => strings.field_on_page(page_number),
  }
}

pub(super) fn apply_generated_field_message_style(
  style: &mut TextStyle,
  message: FieldMessage<'_>,
  ui_language: Option<&str>,
) {
  style.wordprocessingml_generated_field_diagnostic = matches!(
    message,
    FieldMessage::UndefinedBookmark
      | FieldMessage::ReferenceSourceNotFound
      | FieldMessage::BookmarkNameNotSpecified
  );
  if OfficeStringCatalog::for_ui_language(ui_language).resource_locale()
    != OfficeResourceLocale::SimplifiedChinese
  {
    return;
  }
  let east_asia_language = ui_language
    .and_then(crate::localization::canonical_locale)
    .map(|language| Arc::<str>::from(language.to_string()));
  // Word's Simplified Chinese application-resource runs carry the East Asian
  // font-binding state as a unit. ECMA-376 Part 1 §17.3.2.26 and
  // [MS-OI29500] §2.1.88 then route General Punctuation such as U+201C/U+201D
  // through the East Asian face while Basic Latin remains in the ASCII slot.
  // Materialize that complete state here: these strings are generated by the
  // application and therefore have no serialized w:rFonts/@w:hint to inherit.
  style.wordprocessingml_font_slots = true;
  style.wordprocessingml_font_hint = Some(ooxmlsdk_fonts::WordprocessingFontTypeHint::EastAsia);

  match message {
    FieldMessage::UndefinedBookmark
    | FieldMessage::ReferenceSourceNotFound
    | FieldMessage::BookmarkNameNotSpecified => {
      // Word emits Simplified Chinese field diagnostics through the East
      // Asian slot. Keep the field's Latin face for punctuation while using
      // the legacy Office SimSun resource face for Han glyphs.
      style.east_asia_font_family = Some(Arc::<str>::from("SimSun"));
      style.east_asia_language = east_asia_language.clone();
      // Direct effects and bold from a stale cached result do not carry
      // across Word's generated replacement. Fill color and Latin face do.
      style.outline_color = None;
      style.outline_opacity = 1.0;
      style.outline_width_pt = 0.0;
      if let Some(options) = style.pdf_glyph_outline_options.as_deref() {
        let mut options = options.clone();
        options.outline_fill = None;
        options.outline_stroke = None;
        style.pdf_glyph_outline_options = Some(Arc::new(options));
      }

      match message {
        FieldMessage::UndefinedBookmark => {
          // Word's missing-bookmark resource is bold unless the effective
          // WordprocessingML cascade explicitly disables w:b. A resolved
          // default `false` is not equivalent to authored `w:b=false`.
          let bold = style.wordprocessingml_field_bold_override != Some(false);
          style.bold = bold;
          style.complex_bold = Some(bold);
        }
        FieldMessage::ReferenceSourceNotFound | FieldMessage::BookmarkNameNotSpecified => {
          // REF and NOTEREF use a bold Arial/SimSun resource pair.
          style.font_family = Some(Arc::<str>::from("Arial"));
          style.bold = true;
          style.complex_bold = Some(true);
          style.underline = false;
        }
        _ => unreachable!("matched generated reference diagnostic"),
      }
    }
    FieldMessage::MissingStyle(_) => {
      // STYLEREF uses the current Office UI face for Chinese. The font-slot
      // table above keeps its embedded Basic Latin style name and punctuation
      // in the field's Latin face, while its curly quotation marks follow the
      // East Asian hint as General Punctuation.
      style.east_asia_font_family = Some(super::office_default_font_family_for_resource_locale(
        crate::localization::OfficeResourceLocale::SimplifiedChinese,
      ));
      style.east_asia_language = east_asia_language;
      style.bold = true;
      style.complex_bold = Some(true);
      style.line_height_override_pt =
        Some(style.font_size_pt * WORD_ZH_STYLE_REF_ERROR_LINE_HEIGHT_PER_FONT_SIZE);
    }
    FieldMessage::EmptyTableOfContents
    | FieldMessage::PageRefRelative { .. }
    | FieldMessage::PageRefOnPage(_) => {}
  }
}

pub(super) fn apply_bidi_outline_missing_context_style(style: &mut TextStyle) {
  // Word materializes the missing numbering context as an application-
  // generated placeholder rather than persisted field text. Its built-in
  // resource is bold, while an explicitly authored w:b=false on the field
  // remains authoritative just as it does for other generated diagnostics.
  style.wordprocessingml_generated_field_diagnostic = true;
  let bold = style.wordprocessingml_field_bold_override != Some(false);
  style.bold = bold;
  style.complex_bold = Some(bold);
}

#[cfg(test)]
mod tests {
  use super::*;

  #[test]
  fn field_diagnostics_follow_ui_language_not_document_language() {
    assert_eq!(
      localized_field_message(FieldMessage::UndefinedBookmark, Some("zh-CN")),
      "错误!未定义书签。"
    );
    assert_eq!(
      localized_field_message(FieldMessage::UndefinedBookmark, Some("nl-NL")),
      "Error! Bookmark not defined."
    );
  }

  #[test]
  fn undefined_bookmark_bold_default_respects_an_explicit_word_override() {
    let mut default_style = TextStyle::default();
    apply_generated_field_message_style(
      &mut default_style,
      FieldMessage::UndefinedBookmark,
      Some("zh-CN"),
    );
    assert!(default_style.bold);

    let mut explicitly_plain = TextStyle {
      wordprocessingml_field_bold_override: Some(false),
      ..TextStyle::default()
    };
    apply_generated_field_message_style(
      &mut explicitly_plain,
      FieldMessage::UndefinedBookmark,
      Some("zh-CN"),
    );
    assert!(!explicitly_plain.bold);
  }

  #[test]
  fn bidi_outline_placeholder_bold_default_respects_an_explicit_word_override() {
    let mut default_style = TextStyle::default();
    apply_bidi_outline_missing_context_style(&mut default_style);
    assert!(default_style.bold);
    assert!(default_style.wordprocessingml_generated_field_diagnostic);

    let mut explicitly_plain = TextStyle {
      wordprocessingml_field_bold_override: Some(false),
      ..TextStyle::default()
    };
    apply_bidi_outline_missing_context_style(&mut explicitly_plain);
    assert!(!explicitly_plain.bold);
    assert_eq!(explicitly_plain.complex_bold, Some(false));
  }

  #[test]
  fn all_generated_field_messages_share_one_locale_classifier() {
    assert_eq!(
      localized_field_message(
        FieldMessage::PageRefRelative {
          bookmark_is_above: true,
        },
        Some("zh_Hans_SG"),
      ),
      "上方"
    );
    assert_eq!(
      localized_field_message(FieldMessage::EmptyTableOfContents, Some("zh-Hant-HK")),
      "錯誤! 找不到目錄項目。"
    );
  }

  #[test]
  fn simplified_chinese_field_resources_bind_general_punctuation_to_east_asia() {
    let text = localized_field_message(FieldMessage::MissingStyle("Heading 1"), Some("zh-CN"));
    let mut style = TextStyle::default();
    apply_generated_field_message_style(
      &mut style,
      FieldMessage::MissingStyle("Heading 1"),
      Some("zh-CN"),
    );

    assert!(style.wordprocessingml_font_slots);
    assert_eq!(
      style.wordprocessingml_font_hint,
      Some(ooxmlsdk_fonts::WordprocessingFontTypeHint::EastAsia)
    );

    let runs = ooxmlsdk_fonts::script_direction_runs_with_options(
      &text,
      ooxmlsdk_fonts::FontSize(style.font_size_pt),
      ooxmlsdk_fonts::ScriptScanOptions {
        wordprocessingml_font_slots: style.wordprocessingml_font_slots,
        wordprocessingml_font_hint: style.wordprocessingml_font_hint,
        wordprocessingml_east_asia_language_is_chinese: true,
        ..ooxmlsdk_fonts::ScriptScanOptions::default()
      },
    );
    let slot_for = |needle: char| {
      runs
        .iter()
        .find(|run| text[run.text_range.clone()].contains(needle))
        .and_then(|run| run.wordprocessingml_font_slot)
        .expect("generated field character has a WordprocessingML font slot")
    };

    assert_eq!(
      slot_for('“'),
      ooxmlsdk_fonts::WordprocessingFontSlot::EastAsia
    );
    assert_eq!(
      slot_for('”'),
      ooxmlsdk_fonts::WordprocessingFontSlot::EastAsia
    );
    assert_eq!(slot_for('!'), ooxmlsdk_fonts::WordprocessingFontSlot::Ascii);
    assert_eq!(slot_for('H'), ooxmlsdk_fonts::WordprocessingFontSlot::Ascii);
  }
}
