use std::sync::Arc;

use super::{TextStyle, WORD_ZH_STYLE_REF_ERROR_LINE_HEIGHT_PER_FONT_SIZE};

/// Text generated by Word while updating a field.
///
/// These strings are application resources rather than persisted document
/// content. ECMA-376 defines the field value but does not define missing-target
/// diagnostics, and MS-OI29500 §2.1.490 explicitly makes PAGEREF's relative
/// labels dependent on the current application UI as well as document text.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(super) enum FieldMessage<'a> {
  UndefinedBookmark,
  ReferenceSourceNotFound,
  BookmarkNameNotSpecified,
  MissingStyle(&'a str),
  EmptyTableOfContents,
  PageRefRelative { bookmark_is_above: bool },
  PageRefOnPage(&'a str),
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
enum FieldLanguage {
  SimplifiedChinese,
  TraditionalChinese,
  EnglishFallback,
}

pub(super) fn localized_field_message(
  message: FieldMessage<'_>,
  ui_language: Option<&str>,
) -> String {
  match (message, field_language(ui_language)) {
    (FieldMessage::UndefinedBookmark, FieldLanguage::SimplifiedChinese) => {
      "错误!未定义书签。".to_string()
    }
    (FieldMessage::UndefinedBookmark, FieldLanguage::TraditionalChinese) => {
      "錯誤！ 書籤未定義。".to_string()
    }
    (FieldMessage::UndefinedBookmark, FieldLanguage::EnglishFallback) => {
      "Error! Bookmark not defined.".to_string()
    }
    (FieldMessage::ReferenceSourceNotFound, FieldLanguage::SimplifiedChinese) => {
      "错误!未找到引用源。".to_string()
    }
    (FieldMessage::ReferenceSourceNotFound, FieldLanguage::TraditionalChinese) => {
      "錯誤! 找不到參照來源。".to_string()
    }
    (FieldMessage::ReferenceSourceNotFound, FieldLanguage::EnglishFallback) => {
      "Error! Reference source not found.".to_string()
    }
    (FieldMessage::BookmarkNameNotSpecified, FieldLanguage::SimplifiedChinese) => {
      "错误!未指定书签。".to_string()
    }
    (FieldMessage::BookmarkNameNotSpecified, FieldLanguage::TraditionalChinese) => {
      "錯誤! 未提供書籤名稱。".to_string()
    }
    (FieldMessage::BookmarkNameNotSpecified, FieldLanguage::EnglishFallback) => {
      "Error! No bookmark name given.".to_string()
    }
    (FieldMessage::MissingStyle(style_name), FieldLanguage::SimplifiedChinese) => {
      format!("错误!使用“开始”选项卡将 {style_name} 应用于要在此处显示的文字。")
    }
    (FieldMessage::MissingStyle(style_name), FieldLanguage::TraditionalChinese) => {
      format!("錯誤!請使用 [常用] 索引標籤將 {style_name} 套用到您想要在此顯示的文字。")
    }
    (FieldMessage::MissingStyle(style_name), FieldLanguage::EnglishFallback) => {
      format!(
        "Error! Use the Home tab to apply {style_name} to the text that you want to appear here."
      )
    }
    (FieldMessage::EmptyTableOfContents, FieldLanguage::SimplifiedChinese) => {
      "错误!未找到目录项。".to_string()
    }
    (FieldMessage::EmptyTableOfContents, FieldLanguage::TraditionalChinese) => {
      "錯誤! 找不到目錄項目。".to_string()
    }
    (FieldMessage::EmptyTableOfContents, FieldLanguage::EnglishFallback) => {
      "No table of contents entries found.".to_string()
    }
    (
      FieldMessage::PageRefRelative {
        bookmark_is_above: true,
      },
      FieldLanguage::SimplifiedChinese,
    ) => "上方".to_string(),
    (
      FieldMessage::PageRefRelative {
        bookmark_is_above: false,
      },
      FieldLanguage::SimplifiedChinese,
    ) => "下方".to_string(),
    (
      FieldMessage::PageRefRelative {
        bookmark_is_above: true,
      },
      FieldLanguage::TraditionalChinese,
    ) => "上面".to_string(),
    (
      FieldMessage::PageRefRelative {
        bookmark_is_above: false,
      },
      FieldLanguage::TraditionalChinese,
    ) => "下面".to_string(),
    (
      FieldMessage::PageRefRelative {
        bookmark_is_above: true,
      },
      FieldLanguage::EnglishFallback,
    ) => "above".to_string(),
    (
      FieldMessage::PageRefRelative {
        bookmark_is_above: false,
      },
      FieldLanguage::EnglishFallback,
    ) => "below".to_string(),
    (FieldMessage::PageRefOnPage(page_number), FieldLanguage::SimplifiedChinese) => {
      format!("第 {page_number} 页")
    }
    (FieldMessage::PageRefOnPage(page_number), FieldLanguage::TraditionalChinese) => {
      format!("第 {page_number} 頁")
    }
    (FieldMessage::PageRefOnPage(page_number), FieldLanguage::EnglishFallback) => {
      format!("on page {page_number}")
    }
  }
}

pub(super) fn apply_generated_field_message_style(
  style: &mut TextStyle,
  message: FieldMessage<'_>,
  ui_language: Option<&str>,
) {
  style.wordprocessingml_generated_field_diagnostic = matches!(
    message,
    FieldMessage::UndefinedBookmark
      | FieldMessage::ReferenceSourceNotFound
      | FieldMessage::BookmarkNameNotSpecified
  );
  if field_language(ui_language) != FieldLanguage::SimplifiedChinese {
    return;
  }

  match message {
    FieldMessage::UndefinedBookmark
    | FieldMessage::ReferenceSourceNotFound
    | FieldMessage::BookmarkNameNotSpecified => {
      // Word emits Simplified Chinese field diagnostics through the East
      // Asian slot. Keep the field's Latin face for punctuation while using
      // the legacy Office SimSun resource face for Han glyphs.
      style.east_asia_font_family = Some(Arc::<str>::from("SimSun"));
      style.east_asia_language = Some(Arc::<str>::from("zh-CN"));
      // Direct effects and bold from a stale cached result do not carry
      // across Word's generated replacement. Fill color and Latin face do.
      style.outline_color = None;
      style.outline_opacity = 1.0;
      style.outline_width_pt = 0.0;
      if let Some(options) = style.pdf_glyph_outline_options.as_deref() {
        let mut options = options.clone();
        options.outline_fill = None;
        options.outline_stroke = None;
        style.pdf_glyph_outline_options = Some(Arc::new(options));
      }

      match message {
        FieldMessage::UndefinedBookmark => {
          // Word's missing-bookmark resource is bold unless the effective
          // WordprocessingML cascade explicitly disables w:b. A resolved
          // default `false` is not equivalent to authored `w:b=false`.
          let bold = style.wordprocessingml_field_bold_override != Some(false);
          style.bold = bold;
          style.complex_bold = Some(bold);
        }
        FieldMessage::ReferenceSourceNotFound | FieldMessage::BookmarkNameNotSpecified => {
          // REF and NOTEREF use a bold Arial/SimSun resource pair.
          style.font_family = Some(Arc::<str>::from("Arial"));
          style.bold = true;
          style.complex_bold = Some(true);
          style.underline = false;
        }
        _ => unreachable!("matched generated reference diagnostic"),
      }
    }
    FieldMessage::MissingStyle(_) => {
      // STYLEREF uses the current Office UI face for Chinese and preserves the
      // field's Latin face for the embedded style name and punctuation.
      style.east_asia_font_family = Some(super::office_default_font_family(Some("zh-CN")));
      style.east_asia_language = Some(Arc::<str>::from("zh-CN"));
      style.bold = true;
      style.complex_bold = Some(true);
      style.line_height_override_pt =
        Some(style.font_size_pt * WORD_ZH_STYLE_REF_ERROR_LINE_HEIGHT_PER_FONT_SIZE);
    }
    FieldMessage::EmptyTableOfContents
    | FieldMessage::PageRefRelative { .. }
    | FieldMessage::PageRefOnPage(_) => {}
  }
}

fn field_language(ui_language: Option<&str>) -> FieldLanguage {
  let language = ui_language
    .unwrap_or("en-US")
    .replace('_', "-")
    .to_ascii_lowercase();
  if language == "zh-cn" || language == "zh-sg" || language.starts_with("zh-hans") {
    FieldLanguage::SimplifiedChinese
  } else if language == "zh-tw"
    || language == "zh-hk"
    || language == "zh-mo"
    || language.starts_with("zh-hant")
  {
    FieldLanguage::TraditionalChinese
  } else {
    FieldLanguage::EnglishFallback
  }
}

#[cfg(test)]
mod tests {
  use super::*;

  #[test]
  fn field_diagnostics_follow_ui_language_not_document_language() {
    assert_eq!(
      localized_field_message(FieldMessage::UndefinedBookmark, Some("zh-CN")),
      "错误!未定义书签。"
    );
    assert_eq!(
      localized_field_message(FieldMessage::UndefinedBookmark, Some("nl-NL")),
      "Error! Bookmark not defined."
    );
  }

  #[test]
  fn undefined_bookmark_bold_default_respects_an_explicit_word_override() {
    let mut default_style = TextStyle::default();
    apply_generated_field_message_style(
      &mut default_style,
      FieldMessage::UndefinedBookmark,
      Some("zh-CN"),
    );
    assert!(default_style.bold);

    let mut explicitly_plain = TextStyle {
      wordprocessingml_field_bold_override: Some(false),
      ..TextStyle::default()
    };
    apply_generated_field_message_style(
      &mut explicitly_plain,
      FieldMessage::UndefinedBookmark,
      Some("zh-CN"),
    );
    assert!(!explicitly_plain.bold);
  }

  #[test]
  fn all_generated_field_messages_share_one_locale_classifier() {
    assert_eq!(
      localized_field_message(
        FieldMessage::PageRefRelative {
          bookmark_is_above: true,
        },
        Some("zh_Hans_SG"),
      ),
      "上方"
    );
    assert_eq!(
      localized_field_message(FieldMessage::EmptyTableOfContents, Some("zh-Hant-HK")),
      "錯誤! 找不到目錄項目。"
    );
  }
}
