use std::sync::Arc;

use crate::localization::{OfficeResourceLocale, OfficeStringCatalog};

use super::{TextStyle, WORD_ZH_STYLE_REF_ERROR_LINE_HEIGHT_PER_FONT_SIZE};

/// Text generated by Word while updating a field.
///
/// These strings are application resources rather than persisted document
/// content. ECMA-376 defines the field value but does not define missing-target
/// diagnostics, and MS-OI29500 §2.1.490 explicitly makes PAGEREF's relative
/// labels dependent on the current application UI as well as document text.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(super) enum FieldMessage<'a> {
  UndefinedBookmark,
  ReferenceSourceNotFound,
  BookmarkNameNotSpecified,
  MissingStyle(&'a str),
  EmptyTableOfContents,
  PageRefRelative { bookmark_is_above: bool },
  PageRefOnPage(&'a str),
}

pub(super) fn localized_field_message(
  message: FieldMessage<'_>,
  ui_language: Option<&str>,
) -> String {
  // Per-message Office resources confirmed in existing fixed output. Keep
  // unsupported messages on the catalog fallback until their wording is
  // established, instead of treating this as a complete UI language pack.
  let reference_message = ui_language
    .and_then(crate::localization::canonical_locale)
    .and_then(|locale| match (locale.id.language.as_str(), message) {
      ("de", FieldMessage::UndefinedBookmark) => Some("Fehler! Textmarke nicht definiert."),
      ("de", FieldMessage::ReferenceSourceNotFound) => {
        Some("Fehler! Verweisquelle konnte nicht gefunden werden.")
      }
      ("fr", FieldMessage::ReferenceSourceNotFound) => {
        Some("Erreur! Source du renvoi introuvable.")
      }
      ("ja", FieldMessage::UndefinedBookmark) => Some("エラー! ブックマークが定義されていません。"),
      ("ja", FieldMessage::ReferenceSourceNotFound) => Some("エラー! 参照元が見つかりません。"),
      ("ja", FieldMessage::EmptyTableOfContents) => Some("目次項目が見つかりません。"),
      ("fr", FieldMessage::EmptyTableOfContents) => {
        Some("Aucune entrée de table des matières n'a été trouvée.")
      }
      _ => None,
    });
  if let Some(text) = reference_message {
    return text.to_owned();
  }
  let strings = OfficeStringCatalog::for_ui_language(ui_language);
  match message {
    FieldMessage::UndefinedBookmark
      if strings.resource_locale() == OfficeResourceLocale::TraditionalChinese =>
    {
      // Word's Traditional Chinese PAGEREF resource includes 尚 and uses
      // Basic Latin punctuation (tdf64531.docx fixed output).
      "錯誤! 尚未定義書籤。".to_string()
    }
    FieldMessage::UndefinedBookmark => strings.field_undefined_bookmark().to_string(),
    FieldMessage::ReferenceSourceNotFound => strings.field_reference_source_not_found().to_string(),
    FieldMessage::BookmarkNameNotSpecified => {
      strings.field_bookmark_name_not_specified().to_string()
    }
    FieldMessage::MissingStyle(style_name) if is_korean_ui_language(ui_language) => {
      format!("오류! 여기에 표시할 텍스트에 {style_name} 을(를) 적용하려면 홈 탭을 사용하세요.")
    }
    FieldMessage::MissingStyle(style_name) => strings.field_missing_style(style_name),
    FieldMessage::EmptyTableOfContents => {
      // Word's en-US resource uses an all-caps fixed-format diagnostic for a
      // clean empty TOC. Other UI resources, including the ko-KR fallback,
      // retain sentence case (the paired redline-ends-before-toc control).
      if ui_language
        .and_then(crate::localization::canonical_locale)
        .is_some_and(|locale| locale.to_string().eq_ignore_ascii_case("en-US"))
      {
        "NO TABLE OF CONTENTS ENTRIES FOUND.".to_string()
      } else {
        strings.field_empty_table_of_contents().to_string()
      }
    }
    FieldMessage::PageRefRelative { bookmark_is_above } => if bookmark_is_above {
      strings.field_above()
    } else {
      strings.field_below()
    }
    .to_string(),
    FieldMessage::PageRefOnPage(page_number) => strings.field_on_page(page_number),
  }
}

#[derive(Clone, Copy)]
pub(super) enum BibliographyDiagnostic {
  EmptySources,
  MissingCitationSource,
}

pub(super) fn localized_bibliography_diagnostic(
  message: BibliographyDiagnostic,
  ui_language: Option<&str>,
) -> Option<&'static str> {
  let language = ui_language.and_then(crate::localization::canonical_locale)?;
  if language.id.language.as_str() != "ja" {
    return None;
  }
  // Distinct Office resources in 99_Fields.docx; neither is the invalid-tag
  // CITATION diagnostic. Keep other locales on their existing cache paths.
  Some(match message {
    BibliographyDiagnostic::EmptySources => "作業中の文書には元データがありません。",
    BibliographyDiagnostic::MissingCitationSource => "資料文献が指定されていません。",
  })
}

pub(super) fn localized_address_block_placeholder(ui_language: Option<&str>) -> &'static str {
  // The unresolved mail-merge placeholder is an application UI resource.
  // ADDRESSBLOCK's \l switch controls recipient-address formatting instead.
  // Both established Chinese resources retain the fixed-output trailing blank.
  match OfficeStringCatalog::for_ui_language(ui_language).resource_locale() {
    OfficeResourceLocale::SimplifiedChinese => "«地址块» ",
    OfficeResourceLocale::TraditionalChinese => "«地址區塊» ",
    _ => "«AddressBlock» ",
  }
}

pub(super) fn localized_greeting_line_placeholder(ui_language: Option<&str>) -> &'static str {
  // These are application placeholders, independent of GREETINGLINE's \l
  // switch for formatting actual recipient data. Only established Office
  // resources are supplied here; other UI locales keep the English fallback.
  match ui_language
    .and_then(crate::localization::canonical_locale)
    .map(|locale| locale.id.language.to_string())
    .as_deref()
  {
    Some("ja") => "«あいさつ文»",
    Some("es") => "«Línea de saludo»",
    _ => "«GreetingLine»",
  }
}

fn is_korean_ui_language(ui_language: Option<&str>) -> bool {
  ui_language
    .and_then(crate::localization::canonical_locale)
    .is_some_and(|locale| locale.id.language.as_str() == "ko")
}

pub(super) fn korean_ui_english_heading_reference(
  style_name: &str,
  ui_language: Option<&str>,
) -> bool {
  // STYLEREF numeric levels are locale-independent. A named built-in heading
  // uses Word's localized UI name instead; an authored custom style can still
  // use the English name, and is handled separately by the caller.
  is_korean_ui_language(ui_language)
    && super::normalized_style_ref_lookup_key(style_name)
      .strip_prefix("heading")
      .is_some_and(|level| matches!(level.as_bytes(), [b'1'..=b'9']))
}

pub(super) fn apply_japanese_diagnostic_font_slots(
  style: &mut TextStyle,
  ui_language: Option<&str>,
) -> bool {
  let Some(language) = ui_language
    .and_then(crate::localization::canonical_locale)
    .filter(|locale| locale.id.language.as_str() == "ja")
  else {
    return false;
  };
  // Existing Office output binds Japanese generated field resources to MS
  // Mincho, including their katakana prolonged sound mark and punctuation.
  // This state belongs to the generated run, not authored Japanese text.
  style.wordprocessingml_font_slots = true;
  style.wordprocessingml_font_hint = Some(ooxmlsdk_fonts::WordprocessingFontTypeHint::EastAsia);
  style.east_asia_font_family = Some(Arc::<str>::from("MS Mincho"));
  style.east_asia_language = Some(Arc::<str>::from(language.to_string()));
  style.east_asia_fallback_font_family = None;
  style.east_asia_font_family_class = None;
  style.east_asia_font_charset = None;
  style.east_asia_font_pitch = None;
  true
}

pub(super) fn apply_generated_field_message_style(
  style: &mut TextStyle,
  message: FieldMessage<'_>,
  ui_language: Option<&str>,
) {
  style.wordprocessingml_generated_field_diagnostic = matches!(
    message,
    FieldMessage::UndefinedBookmark
      | FieldMessage::ReferenceSourceNotFound
      | FieldMessage::BookmarkNameNotSpecified
  );
  if matches!(message, FieldMessage::EmptyTableOfContents) {
    // Writer emits the empty-TOC diagnostic through its generated field error
    // run. Keep it bold independently of the application resource locale.
    style.bold = true;
    style.complex_bold = Some(true);
    if ui_language
      .and_then(crate::localization::canonical_locale)
      .is_some_and(|locale| locale.to_string().eq_ignore_ascii_case("en-US"))
    {
      // The en-US Word resource uses Arial for this generated diagnostic,
      // even when the cached TOC paragraph carries another complex-script
      // face (tdf155736_PageNumbers_footer.docx).
      let family = Arc::<str>::from("Arial");
      style.font_family = Some(family.clone());
      style.high_ansi_font_family = Some(family.clone());
      style.east_asia_font_family = Some(family.clone());
      style.complex_font_family = Some(family.clone());
      style.symbol_font_family = Some(family);
      style.font_size_pt = 12.0;
      style.complex_font_size_pt = Some(12.0);
      style.fallback_font_family = None;
      style.high_ansi_fallback_font_family = None;
      style.east_asia_fallback_font_family = None;
      style.complex_fallback_font_family = None;
    }
  }
  if matches!(
    message,
    FieldMessage::UndefinedBookmark
      | FieldMessage::ReferenceSourceNotFound
      | FieldMessage::BookmarkNameNotSpecified
  ) {
    // Word's generated bookmark diagnostics use a bold application-resource
    // run in every UI locale. An authored field-level w:b=false remains an
    // explicit opt-out.
    let bold = style.wordprocessingml_field_bold_override != Some(false);
    style.bold = bold;
    style.complex_bold = Some(bold);
  }
  if matches!(
    message,
    FieldMessage::UndefinedBookmark
      | FieldMessage::ReferenceSourceNotFound
      | FieldMessage::EmptyTableOfContents
  ) && apply_japanese_diagnostic_font_slots(style, ui_language)
  {
    if matches!(message, FieldMessage::ReferenceSourceNotFound) {
      // The missing-REF resource uses Arial for its ASCII exclamation mark
      // (tdf171299_tableInField.docx). The undefined-bookmark resource keeps
      // the field's Latin face (Calibri in fdo78910.docx).
      style.font_family = Some(Arc::<str>::from("Arial"));
      style.fallback_font_family = None;
    }
    return;
  }
  let resource_locale = OfficeStringCatalog::for_ui_language(ui_language).resource_locale();
  if resource_locale == OfficeResourceLocale::TraditionalChinese
    && matches!(message, FieldMessage::UndefinedBookmark)
  {
    // The established Traditional Chinese bookmark resource uses PMingLiU
    // for Han text and keeps the field's Latin face for its ASCII ! and space.
    // Keep the locale-independent explicit bold override applied above.
    style.wordprocessingml_font_slots = true;
    style.wordprocessingml_font_hint = Some(ooxmlsdk_fonts::WordprocessingFontTypeHint::EastAsia);
    style.east_asia_font_family = Some(Arc::<str>::from("PMingLiU"));
    style.east_asia_language = ui_language
      .and_then(crate::localization::canonical_locale)
      .map(|language| Arc::<str>::from(language.to_string()));
    style.east_asia_fallback_font_family = None;
    style.east_asia_font_family_class = None;
    style.east_asia_font_charset = None;
    style.east_asia_font_pitch = None;
    return;
  }
  if resource_locale != OfficeResourceLocale::SimplifiedChinese {
    return;
  }
  let east_asia_language = ui_language
    .and_then(crate::localization::canonical_locale)
    .map(|language| Arc::<str>::from(language.to_string()));
  // Word's Simplified Chinese application-resource runs carry the East Asian
  // font-binding state as a unit. ECMA-376 Part 1 §17.3.2.26 and
  // [MS-OI29500] §2.1.88 then route General Punctuation such as U+201C/U+201D
  // through the East Asian face while Basic Latin remains in the ASCII slot.
  // Materialize that complete state here: these strings are generated by the
  // application and therefore have no serialized w:rFonts/@w:hint to inherit.
  style.wordprocessingml_font_slots = true;
  style.wordprocessingml_font_hint = Some(ooxmlsdk_fonts::WordprocessingFontTypeHint::EastAsia);

  match message {
    FieldMessage::UndefinedBookmark
    | FieldMessage::ReferenceSourceNotFound
    | FieldMessage::BookmarkNameNotSpecified => {
      // Word emits Simplified Chinese field diagnostics through the East
      // Asian slot. Keep the field's Latin face for punctuation while using
      // the legacy Office SimSun resource face for Han glyphs.
      style.east_asia_font_family = Some(Arc::<str>::from("SimSun"));
      style.east_asia_language = east_asia_language.clone();
      // Direct effects and bold from a stale cached result do not carry
      // across Word's generated replacement. Fill color and Latin face do.
      style.outline_color = None;
      style.outline_opacity = 1.0;
      style.outline_width_pt = 0.0;
      if let Some(options) = style.pdf_glyph_outline_options.as_deref() {
        let mut options = options.clone();
        options.outline_fill = None;
        options.outline_stroke = None;
        style.pdf_glyph_outline_options = Some(Arc::new(options));
      }

      match message {
        FieldMessage::UndefinedBookmark => {
          // The locale-independent generated diagnostic style was applied
          // above; this branch only supplies its Simplified-Chinese slots.
        }
        FieldMessage::ReferenceSourceNotFound | FieldMessage::BookmarkNameNotSpecified => {
          // REF and NOTEREF use a bold Arial/SimSun resource pair.
          style.font_family = Some(Arc::<str>::from("Arial"));
          style.underline = false;
        }
        _ => unreachable!("matched generated reference diagnostic"),
      }
    }
    FieldMessage::MissingStyle(_) => {
      // STYLEREF uses the current Office UI face for Chinese. The font-slot
      // table above keeps its embedded Basic Latin style name and punctuation
      // in the field's Latin face, while its curly quotation marks follow the
      // East Asian hint as General Punctuation.
      style.east_asia_font_family = Some(super::office_default_font_family_for_resource_locale(
        crate::localization::OfficeResourceLocale::SimplifiedChinese,
      ));
      style.east_asia_language = east_asia_language;
      style.bold = true;
      style.complex_bold = Some(true);
      style.line_height_override_pt =
        Some(style.font_size_pt * WORD_ZH_STYLE_REF_ERROR_LINE_HEIGHT_PER_FONT_SIZE);
    }
    FieldMessage::EmptyTableOfContents => {}
    FieldMessage::PageRefRelative { .. } | FieldMessage::PageRefOnPage(_) => {}
  }
}

pub(super) fn apply_bidi_outline_missing_context_style(style: &mut TextStyle) {
  // Word materializes the missing numbering context as an application-
  // generated placeholder rather than persisted field text. Its built-in
  // resource is bold, while an explicitly authored w:b=false on the field
  // remains authoritative just as it does for other generated diagnostics.
  style.wordprocessingml_generated_field_diagnostic = true;
  let bold = style.wordprocessingml_field_bold_override != Some(false);
  style.bold = bold;
  style.complex_bold = Some(bold);
}

#[cfg(test)]
mod tests {
  use super::*;

  #[test]
  fn bookmark_diagnostics_preserve_office_ui_language_and_field_kind() {
    for (language, bookmark, reference) in [
      (
        "DE_de",
        "Fehler! Textmarke nicht definiert.",
        "Fehler! Verweisquelle konnte nicht gefunden werden.",
      ),
      (
        "ja-JP",
        "エラー! ブックマークが定義されていません。",
        "エラー! 参照元が見つかりません。",
      ),
    ] {
      assert_eq!(
        localized_field_message(FieldMessage::UndefinedBookmark, Some(language)),
        bookmark
      );
      assert_eq!(
        localized_field_message(FieldMessage::ReferenceSourceNotFound, Some(language)),
        reference
      );
    }
    assert_eq!(
      localized_field_message(FieldMessage::BookmarkNameNotSpecified, Some("ja-JP")),
      "Error! No bookmark name given.",
    );
    assert_eq!(
      localized_field_message(FieldMessage::ReferenceSourceNotFound, Some("en-US")),
      "Error! Reference source not found.",
    );
  }

  #[test]
  fn traditional_chinese_bookmark_resource_preserves_other_messages_and_font_slots() {
    for language in ["zh-TW", "zh_Hant_HK", "zh-MO"] {
      assert_eq!(
        localized_field_message(FieldMessage::UndefinedBookmark, Some(language)),
        "錯誤! 尚未定義書籤。",
      );
    }
    assert_eq!(
      localized_field_message(FieldMessage::UndefinedBookmark, Some("zh-Hans-TW")),
      "错误!未定义书签。",
    );
    for (message, expected) in [
      (
        FieldMessage::ReferenceSourceNotFound,
        "錯誤! 找不到參照來源。",
      ),
      (
        FieldMessage::BookmarkNameNotSpecified,
        "錯誤! 未提供書籤名稱。",
      ),
      (FieldMessage::EmptyTableOfContents, "錯誤! 找不到目錄項目。"),
    ] {
      assert_eq!(localized_field_message(message, Some("zh-TW")), expected);
    }

    for bold_override in [None, Some(false), Some(true)] {
      let mut style = TextStyle {
        font_family: Some(Arc::from("Lucida Sans Unicode")),
        high_ansi_font_family: Some(Arc::from("Times New Roman")),
        complex_font_family: Some(Arc::from("Tahoma")),
        east_asia_font_family: Some(Arc::from("Microsoft JhengHei")),
        east_asia_fallback_font_family: Some(Arc::from("Noto Sans CJK TC")),
        wordprocessingml_field_bold_override: bold_override,
        ..TextStyle::default()
      };
      apply_generated_field_message_style(
        &mut style,
        FieldMessage::UndefinedBookmark,
        Some("zh-TW"),
      );
      assert_eq!(style.font_family.as_deref(), Some("Lucida Sans Unicode"));
      assert_eq!(
        style.high_ansi_font_family.as_deref(),
        Some("Times New Roman")
      );
      assert_eq!(style.complex_font_family.as_deref(), Some("Tahoma"));
      assert_eq!(style.east_asia_font_family.as_deref(), Some("PMingLiU"));
      assert_eq!(style.east_asia_language.as_deref(), Some("zh-TW"));
      assert_eq!(style.east_asia_fallback_font_family, None);
      assert_eq!(style.bold, bold_override != Some(false));
      assert_eq!(style.complex_bold, Some(bold_override != Some(false)));
      let text = localized_field_message(FieldMessage::UndefinedBookmark, Some("zh-TW"));
      let runs = ooxmlsdk_fonts::script_direction_runs_with_options(
        &text,
        ooxmlsdk_fonts::FontSize(style.font_size_pt),
        ooxmlsdk_fonts::ScriptScanOptions {
          wordprocessingml_font_slots: style.wordprocessingml_font_slots,
          wordprocessingml_font_hint: style.wordprocessingml_font_hint,
          wordprocessingml_east_asia_language_is_chinese: true,
          ..ooxmlsdk_fonts::ScriptScanOptions::default()
        },
      );
      for run in runs {
        for character in text[run.text_range].chars() {
          let expected = if character.is_ascii() {
            ooxmlsdk_fonts::WordprocessingFontSlot::Ascii
          } else {
            ooxmlsdk_fonts::WordprocessingFontSlot::EastAsia
          };
          assert_eq!(
            run.wordprocessingml_font_slot,
            Some(expected),
            "{character}"
          );
        }
      }
    }

    for (language, message) in [
      (Some("en-US"), FieldMessage::UndefinedBookmark),
      (Some("zh-TW"), FieldMessage::ReferenceSourceNotFound),
      (Some("zh-TW"), FieldMessage::BookmarkNameNotSpecified),
    ] {
      let mut style = TextStyle {
        font_family: Some(Arc::from("Lucida Sans Unicode")),
        east_asia_font_family: Some(Arc::from("Microsoft JhengHei")),
        ..TextStyle::default()
      };
      apply_generated_field_message_style(&mut style, message, language);
      assert_eq!(style.font_family.as_deref(), Some("Lucida Sans Unicode"));
      assert_eq!(
        style.east_asia_font_family.as_deref(),
        Some("Microsoft JhengHei")
      );
    }
  }

  #[test]
  fn korean_missing_style_resource_preserves_the_requested_style_name() {
    assert_eq!(
      localized_field_message(FieldMessage::MissingStyle("Heading 2"), Some("KO_kr")),
      "오류! 여기에 표시할 텍스트에 Heading 2 을(를) 적용하려면 홈 탭을 사용하세요."
    );
    for level in 1..=9 {
      assert!(korean_ui_english_heading_reference(
        &format!("Heading {level}"),
        Some("ko-KR")
      ));
      assert!(!korean_ui_english_heading_reference(
        &level.to_string(),
        Some("ko-KR")
      ));
    }
    assert!(!korean_ui_english_heading_reference(
      "Heading 10",
      Some("ko-KR")
    ));
    assert!(!korean_ui_english_heading_reference(
      "Heading 1",
      Some("en-US")
    ));
  }

  #[test]
  fn field_diagnostics_follow_ui_language_not_document_language() {
    assert_eq!(
      localized_field_message(FieldMessage::UndefinedBookmark, Some("zh-CN")),
      "错误!未定义书签。"
    );
    assert_eq!(
      localized_field_message(FieldMessage::UndefinedBookmark, Some("nl-NL")),
      "Error! Bookmark not defined."
    );
  }

  #[test]
  fn undefined_bookmark_bold_default_respects_an_explicit_word_override() {
    let mut default_style = TextStyle::default();
    apply_generated_field_message_style(
      &mut default_style,
      FieldMessage::UndefinedBookmark,
      Some("zh-CN"),
    );
    assert!(default_style.bold);

    let mut explicitly_plain = TextStyle {
      wordprocessingml_field_bold_override: Some(false),
      ..TextStyle::default()
    };
    apply_generated_field_message_style(
      &mut explicitly_plain,
      FieldMessage::UndefinedBookmark,
      Some("zh-CN"),
    );
    assert!(!explicitly_plain.bold);
  }

  #[test]
  fn bidi_outline_placeholder_bold_default_respects_an_explicit_word_override() {
    let mut default_style = TextStyle::default();
    apply_bidi_outline_missing_context_style(&mut default_style);
    assert!(default_style.bold);
    assert!(default_style.wordprocessingml_generated_field_diagnostic);

    let mut explicitly_plain = TextStyle {
      wordprocessingml_field_bold_override: Some(false),
      ..TextStyle::default()
    };
    apply_bidi_outline_missing_context_style(&mut explicitly_plain);
    assert!(!explicitly_plain.bold);
    assert_eq!(explicitly_plain.complex_bold, Some(false));
  }

  #[test]
  fn all_generated_field_messages_share_one_locale_classifier() {
    assert_eq!(
      localized_field_message(
        FieldMessage::PageRefRelative {
          bookmark_is_above: true,
        },
        Some("zh_Hans_SG"),
      ),
      "上方"
    );
    assert_eq!(
      localized_field_message(FieldMessage::EmptyTableOfContents, Some("zh-Hant-HK")),
      "錯誤! 找不到目錄項目。"
    );
  }

  #[test]
  fn japanese_diagnostics_bind_east_asia_without_overwriting_other_font_slots() {
    for (message, ascii) in [
      (FieldMessage::UndefinedBookmark, "Courier New"),
      (FieldMessage::ReferenceSourceNotFound, "Arial"),
      (FieldMessage::EmptyTableOfContents, "Courier New"),
    ] {
      let mut style = TextStyle {
        font_family: Some(Arc::from("Courier New")),
        high_ansi_font_family: Some(Arc::from("Times New Roman")),
        east_asia_font_family: Some(Arc::from("Microsoft YaHei")),
        east_asia_fallback_font_family: Some(Arc::from("Noto Sans CJK JP")),
        complex_font_family: Some(Arc::from("Tahoma")),
        wordprocessingml_field_bold_override: Some(false),
        ..TextStyle::default()
      };
      apply_generated_field_message_style(&mut style, message, Some("JA_jp"));
      assert_eq!(style.font_family.as_deref(), Some(ascii));
      assert_eq!(
        style.high_ansi_font_family.as_deref(),
        Some("Times New Roman")
      );
      assert_eq!(style.east_asia_font_family.as_deref(), Some("MS Mincho"));
      assert_eq!(style.complex_font_family.as_deref(), Some("Tahoma"));
      assert_eq!(style.east_asia_language.as_deref(), Some("ja-JP"));
      assert_eq!(style.east_asia_fallback_font_family, None);
      assert_eq!(
        style.bold,
        matches!(message, FieldMessage::EmptyTableOfContents)
      );

      let text = localized_field_message(message, Some("ja-JP"));
      let runs = ooxmlsdk_fonts::script_direction_runs_with_options(
        &text,
        ooxmlsdk_fonts::FontSize(style.font_size_pt),
        ooxmlsdk_fonts::ScriptScanOptions {
          wordprocessingml_font_slots: style.wordprocessingml_font_slots,
          wordprocessingml_font_hint: style.wordprocessingml_font_hint,
          ..ooxmlsdk_fonts::ScriptScanOptions::default()
        },
      );
      for run in runs {
        for character in text[run.text_range].chars() {
          let expected = if character.is_ascii() {
            ooxmlsdk_fonts::WordprocessingFontSlot::Ascii
          } else {
            ooxmlsdk_fonts::WordprocessingFontSlot::EastAsia
          };
          assert_eq!(
            run.wordprocessingml_font_slot,
            Some(expected),
            "{character}"
          );
        }
      }
    }
  }

  #[test]
  fn japanese_diagnostic_font_binding_requires_an_established_resource() {
    let original = TextStyle {
      font_family: Some(Arc::from("Courier New")),
      east_asia_font_family: Some(Arc::from("Yu Gothic")),
      ..TextStyle::default()
    };
    for language in [None, Some("en-US"), Some("fr-CA")] {
      let mut style = original.clone();
      assert!(!apply_japanese_diagnostic_font_slots(&mut style, language));
      assert_eq!(style, original);
    }
    for message in [
      FieldMessage::BookmarkNameNotSpecified,
      FieldMessage::MissingStyle("Heading 1"),
      FieldMessage::PageRefRelative {
        bookmark_is_above: true,
      },
    ] {
      let mut style = original.clone();
      apply_generated_field_message_style(&mut style, message, Some("ja-JP"));
      assert_eq!(style.font_family, original.font_family);
      assert_eq!(style.east_asia_font_family, original.east_asia_font_family);
      assert_eq!(
        style.wordprocessingml_font_hint,
        original.wordprocessingml_font_hint
      );
    }
  }

  #[test]
  fn simplified_chinese_field_resources_bind_general_punctuation_to_east_asia() {
    let text = localized_field_message(FieldMessage::MissingStyle("Heading 1"), Some("zh-CN"));
    let mut style = TextStyle::default();
    apply_generated_field_message_style(
      &mut style,
      FieldMessage::MissingStyle("Heading 1"),
      Some("zh-CN"),
    );

    assert!(style.wordprocessingml_font_slots);
    assert_eq!(
      style.wordprocessingml_font_hint,
      Some(ooxmlsdk_fonts::WordprocessingFontTypeHint::EastAsia)
    );

    let runs = ooxmlsdk_fonts::script_direction_runs_with_options(
      &text,
      ooxmlsdk_fonts::FontSize(style.font_size_pt),
      ooxmlsdk_fonts::ScriptScanOptions {
        wordprocessingml_font_slots: style.wordprocessingml_font_slots,
        wordprocessingml_font_hint: style.wordprocessingml_font_hint,
        wordprocessingml_east_asia_language_is_chinese: true,
        ..ooxmlsdk_fonts::ScriptScanOptions::default()
      },
    );
    let slot_for = |needle: char| {
      runs
        .iter()
        .find(|run| text[run.text_range.clone()].contains(needle))
        .and_then(|run| run.wordprocessingml_font_slot)
        .expect("generated field character has a WordprocessingML font slot")
    };

    assert_eq!(
      slot_for('“'),
      ooxmlsdk_fonts::WordprocessingFontSlot::EastAsia
    );
    assert_eq!(
      slot_for('”'),
      ooxmlsdk_fonts::WordprocessingFontSlot::EastAsia
    );
    assert_eq!(slot_for('!'), ooxmlsdk_fonts::WordprocessingFontSlot::Ascii);
    assert_eq!(slot_for('H'), ooxmlsdk_fonts::WordprocessingFontSlot::Ascii);
  }
}
