//
// -----------------------------------------------------------------------------
//  THIS FILE WAS @generated AUTOMATICALLY. DO NOT MODIFY THIS FILE MANUALLY.
// -----------------------------------------------------------------------------
//

#[repr(u16)]
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub enum XmlKnownNamespace {
  A,
  A14,
  A15,
  A16,
  A1611,
  A3danim,
  Aanim,
  Ac,
  Aclsh,
  Adec,
  Ahyp,
  Aif,
  Aink,
  Alf,
  Am3d,
  Aoe,
  Ap,
  Ask,
  Asl,
  Asvg,
  Ax,
  B,
  C,
  C14,
  C15,
  C16,
  C16ac,
  C16r3,
  Cdip,
  Cdr,
  Cdr14,
  Clbl,
  Com14,
  Comp,
  Cp,
  Cppr,
  Cr,
  Cs,
  Ct,
  Cx,
  Dc,
  Dcterms,
  Dgm,
  Dgm14,
  Dgm1611,
  Dgm1612,
  Ds,
  Dsp,
  Emma,
  Inkml,
  Lc,
  Lp,
  M,
  Ma,
  Mc,
  Md,
  Msink,
  Mso,
  Mso14,
  Ntns,
  O,
  Oac,
  Oel,
  Op,
  P,
  P14,
  P15,
  P16,
  P1710,
  P173,
  P184,
  P188,
  P1912,
  P202,
  P216,
  P223,
  P228,
  P232,
  PRoam,
  Packaging,
  Pav,
  Pc,
  Pc2,
  Pc226,
  Pic,
  Pic14,
  Pj15,
  Pvml,
  R,
  Sl,
  Sle,
  T,
  Thm15,
  Tsle,
  V,
  Vt,
  W,
  W10,
  W14,
  W15,
  W16cex,
  W16cid,
  W16cur,
  W16du,
  W16sdtdh,
  W16sdtfl,
  W16se,
  We,
  Wetp,
  Wne,
  Woe,
  Wp,
  Wp14,
  Wp15,
  Wpc,
  Wpg,
  Wps,
  X,
  X12ac,
  X14,
  X14ac,
  X15,
  X15ac,
  X16,
  X16r2,
  X16r3,
  Xcalcf,
  Xda,
  Xdr,
  Xdr14,
  Xfpb,
  XlPr,
  Xlecs,
  Xlecs2,
  Xlmsforms,
  Xlpar,
  Xlpcalc,
  Xlpda,
  Xlpds,
  Xlrd,
  Xlrd2,
  Xlrdwi,
  Xlrvr,
  Xlrvrel,
  Xltc,
  Xltc2,
  Xlwcv,
  Xml,
  Xne,
  Xnsv,
  Xpdl,
  Xprd,
  Xr,
  Xr10,
  Xr16,
  Xr2,
  Xr3,
  Xr5,
  Xr6,
  Xr9,
  Xsd,
  Xvml,
  Xxdsv,
  Xxl21,
  Xxlnp,
  Xxpim,
  Xxpvi,
}
impl Default for XmlKnownNamespace {
  #[inline]
  fn default() -> Self {
    Self::A
  }
}
impl XmlKnownNamespace {
  #[inline]
  pub const fn prefix(self) -> &'static str {
    match self {
      Self::A => "a",
      Self::A14 => "a14",
      Self::A15 => "a15",
      Self::A16 => "a16",
      Self::A1611 => "a1611",
      Self::A3danim => "a3danim",
      Self::Aanim => "aanim",
      Self::Ac => "ac",
      Self::Aclsh => "aclsh",
      Self::Adec => "adec",
      Self::Ahyp => "ahyp",
      Self::Aif => "aif",
      Self::Aink => "aink",
      Self::Alf => "alf",
      Self::Am3d => "am3d",
      Self::Aoe => "aoe",
      Self::Ap => "ap",
      Self::Ask => "ask",
      Self::Asl => "asl",
      Self::Asvg => "asvg",
      Self::Ax => "ax",
      Self::B => "b",
      Self::C => "c",
      Self::C14 => "c14",
      Self::C15 => "c15",
      Self::C16 => "c16",
      Self::C16ac => "c16ac",
      Self::C16r3 => "c16r3",
      Self::Cdip => "cdip",
      Self::Cdr => "cdr",
      Self::Cdr14 => "cdr14",
      Self::Clbl => "clbl",
      Self::Com14 => "com14",
      Self::Comp => "comp",
      Self::Cp => "cp",
      Self::Cppr => "cppr",
      Self::Cr => "cr",
      Self::Cs => "cs",
      Self::Ct => "ct",
      Self::Cx => "cx",
      Self::Dc => "dc",
      Self::Dcterms => "dcterms",
      Self::Dgm => "dgm",
      Self::Dgm14 => "dgm14",
      Self::Dgm1611 => "dgm1611",
      Self::Dgm1612 => "dgm1612",
      Self::Ds => "ds",
      Self::Dsp => "dsp",
      Self::Emma => "emma",
      Self::Inkml => "inkml",
      Self::Lc => "lc",
      Self::Lp => "lp",
      Self::M => "m",
      Self::Ma => "ma",
      Self::Mc => "mc",
      Self::Md => "md",
      Self::Msink => "msink",
      Self::Mso => "mso",
      Self::Mso14 => "mso14",
      Self::Ntns => "ntns",
      Self::O => "o",
      Self::Oac => "oac",
      Self::Oel => "oel",
      Self::Op => "op",
      Self::P => "p",
      Self::P14 => "p14",
      Self::P15 => "p15",
      Self::P16 => "p16",
      Self::P1710 => "p1710",
      Self::P173 => "p173",
      Self::P184 => "p184",
      Self::P188 => "p188",
      Self::P1912 => "p1912",
      Self::P202 => "p202",
      Self::P216 => "p216",
      Self::P223 => "p223",
      Self::P228 => "p228",
      Self::P232 => "p232",
      Self::PRoam => "pRoam",
      Self::Packaging => "packaging",
      Self::Pav => "pav",
      Self::Pc => "pc",
      Self::Pc2 => "pc2",
      Self::Pc226 => "pc226",
      Self::Pic => "pic",
      Self::Pic14 => "pic14",
      Self::Pj15 => "pj15",
      Self::Pvml => "pvml",
      Self::R => "r",
      Self::Sl => "sl",
      Self::Sle => "sle",
      Self::T => "t",
      Self::Thm15 => "thm15",
      Self::Tsle => "tsle",
      Self::V => "v",
      Self::Vt => "vt",
      Self::W => "w",
      Self::W10 => "w10",
      Self::W14 => "w14",
      Self::W15 => "w15",
      Self::W16cex => "w16cex",
      Self::W16cid => "w16cid",
      Self::W16cur => "w16cur",
      Self::W16du => "w16du",
      Self::W16sdtdh => "w16sdtdh",
      Self::W16sdtfl => "w16sdtfl",
      Self::W16se => "w16se",
      Self::We => "we",
      Self::Wetp => "wetp",
      Self::Wne => "wne",
      Self::Woe => "woe",
      Self::Wp => "wp",
      Self::Wp14 => "wp14",
      Self::Wp15 => "wp15",
      Self::Wpc => "wpc",
      Self::Wpg => "wpg",
      Self::Wps => "wps",
      Self::X => "x",
      Self::X12ac => "x12ac",
      Self::X14 => "x14",
      Self::X14ac => "x14ac",
      Self::X15 => "x15",
      Self::X15ac => "x15ac",
      Self::X16 => "x16",
      Self::X16r2 => "x16r2",
      Self::X16r3 => "x16r3",
      Self::Xcalcf => "xcalcf",
      Self::Xda => "xda",
      Self::Xdr => "xdr",
      Self::Xdr14 => "xdr14",
      Self::Xfpb => "xfpb",
      Self::XlPr => "xlPr",
      Self::Xlecs => "xlecs",
      Self::Xlecs2 => "xlecs2",
      Self::Xlmsforms => "xlmsforms",
      Self::Xlpar => "xlpar",
      Self::Xlpcalc => "xlpcalc",
      Self::Xlpda => "xlpda",
      Self::Xlpds => "xlpds",
      Self::Xlrd => "xlrd",
      Self::Xlrd2 => "xlrd2",
      Self::Xlrdwi => "xlrdwi",
      Self::Xlrvr => "xlrvr",
      Self::Xlrvrel => "xlrvrel",
      Self::Xltc => "xltc",
      Self::Xltc2 => "xltc2",
      Self::Xlwcv => "xlwcv",
      Self::Xml => "xml",
      Self::Xne => "xne",
      Self::Xnsv => "xnsv",
      Self::Xpdl => "xpdl",
      Self::Xprd => "xprd",
      Self::Xr => "xr",
      Self::Xr10 => "xr10",
      Self::Xr16 => "xr16",
      Self::Xr2 => "xr2",
      Self::Xr3 => "xr3",
      Self::Xr5 => "xr5",
      Self::Xr6 => "xr6",
      Self::Xr9 => "xr9",
      Self::Xsd => "xsd",
      Self::Xvml => "xvml",
      Self::Xxdsv => "xxdsv",
      Self::Xxl21 => "xxl21",
      Self::Xxlnp => "xxlnp",
      Self::Xxpim => "xxpim",
      Self::Xxpvi => "xxpvi",
    }
  }
  #[inline]
  pub const fn uri(self) -> &'static str {
    match self {
      Self::A => "http://schemas.openxmlformats.org/drawingml/2006/main",
      Self::A14 => "http://schemas.microsoft.com/office/drawing/2010/main",
      Self::A15 => "http://schemas.microsoft.com/office/drawing/2012/main",
      Self::A16 => "http://schemas.microsoft.com/office/drawing/2014/main",
      Self::A1611 => "http://schemas.microsoft.com/office/drawing/2016/11/main",
      Self::A3danim => "http://schemas.microsoft.com/office/drawing/2018/animation/model3d",
      Self::Aanim => "http://schemas.microsoft.com/office/drawing/2018/animation",
      Self::Ac => "http://schemas.openxmlformats.org/officeDocument/2006/characteristics",
      Self::Aclsh => "http://schemas.microsoft.com/office/drawing/2020/classificationShape",
      Self::Adec => "http://schemas.microsoft.com/office/drawing/2017/decorative",
      Self::Ahyp => "http://schemas.microsoft.com/office/drawing/2018/hyperlinkcolor",
      Self::Aif => "http://schemas.microsoft.com/office/drawing/2022/imageformula",
      Self::Aink => "http://schemas.microsoft.com/office/drawing/2016/ink",
      Self::Alf => "http://schemas.microsoft.com/office/drawing/2021/livefeed",
      Self::Am3d => "http://schemas.microsoft.com/office/drawing/2017/model3d",
      Self::Aoe => "http://schemas.microsoft.com/office/drawing/2021/oembed",
      Self::Ap => "http://schemas.openxmlformats.org/officeDocument/2006/extended-properties",
      Self::Ask => "http://schemas.microsoft.com/office/drawing/2018/sketchyshapes",
      Self::Asl => "http://schemas.microsoft.com/office/drawing/2021/scriptlink",
      Self::Asvg => "http://schemas.microsoft.com/office/drawing/2016/SVG/main",
      Self::Ax => "http://schemas.microsoft.com/office/2006/activeX",
      Self::B => "http://schemas.openxmlformats.org/officeDocument/2006/bibliography",
      Self::C => "http://schemas.openxmlformats.org/drawingml/2006/chart",
      Self::C14 => "http://schemas.microsoft.com/office/drawing/2007/8/2/chart",
      Self::C15 => "http://schemas.microsoft.com/office/drawing/2012/chart",
      Self::C16 => "http://schemas.microsoft.com/office/drawing/2014/chart",
      Self::C16ac => "http://schemas.microsoft.com/office/drawing/2014/chart/ac",
      Self::C16r3 => "http://schemas.microsoft.com/office/drawing/2017/03/chart",
      Self::Cdip => "http://schemas.microsoft.com/office/2006/customDocumentInformationPanel",
      Self::Cdr => "http://schemas.openxmlformats.org/drawingml/2006/chartDrawing",
      Self::Cdr14 => "http://schemas.microsoft.com/office/drawing/2010/chartDrawing",
      Self::Clbl => "http://schemas.microsoft.com/office/2020/mipLabelMetadata",
      Self::Com14 => "http://schemas.microsoft.com/office/drawing/2010/compatibility",
      Self::Comp => "http://schemas.openxmlformats.org/drawingml/2006/compatibility",
      Self::Cp => "http://schemas.openxmlformats.org/package/2006/metadata/core-properties",
      Self::Cppr => "http://schemas.microsoft.com/office/2006/coverPageProps",
      Self::Cr => "http://schemas.microsoft.com/office/comments/2020/reactions",
      Self::Cs => "http://schemas.microsoft.com/office/drawing/2012/chartStyle",
      Self::Ct => "http://schemas.microsoft.com/office/2006/metadata/contentType",
      Self::Cx => "http://schemas.microsoft.com/office/drawing/2014/chartex",
      Self::Dc => "http://purl.org/dc/elements/1.1/",
      Self::Dcterms => "http://purl.org/dc/terms/",
      Self::Dgm => "http://schemas.openxmlformats.org/drawingml/2006/diagram",
      Self::Dgm14 => "http://schemas.microsoft.com/office/drawing/2010/diagram",
      Self::Dgm1611 => "http://schemas.microsoft.com/office/drawing/2016/11/diagram",
      Self::Dgm1612 => "http://schemas.microsoft.com/office/drawing/2016/12/diagram",
      Self::Ds => "http://schemas.openxmlformats.org/officeDocument/2006/customXml",
      Self::Dsp => "http://schemas.microsoft.com/office/drawing/2008/diagram",
      Self::Emma => "http://www.w3.org/2003/04/emma",
      Self::Inkml => "http://www.w3.org/2003/InkML",
      Self::Lc => "http://schemas.openxmlformats.org/drawingml/2006/lockedCanvas",
      Self::Lp => "http://schemas.microsoft.com/office/2006/metadata/longProperties",
      Self::M => "http://schemas.openxmlformats.org/officeDocument/2006/math",
      Self::Ma => "http://schemas.microsoft.com/office/2006/metadata/properties/metaAttributes",
      Self::Mc => "http://schemas.openxmlformats.org/markup-compatibility/2006",
      Self::Md => "http://schemas.microsoft.com/office/office/2011/9/metroDictionary",
      Self::Msink => "http://schemas.microsoft.com/ink/2010/main",
      Self::Mso => "http://schemas.microsoft.com/office/2006/01/customui",
      Self::Mso14 => "http://schemas.microsoft.com/office/2009/07/customui",
      Self::Ntns => "http://schemas.microsoft.com/office/2006/metadata/customXsn",
      Self::O => "urn:schemas-microsoft-com:office:office",
      Self::Oac => "http://schemas.microsoft.com/office/drawing/2013/main/command",
      Self::Oel => "http://schemas.microsoft.com/office/2019/extlst",
      Self::Op => "http://schemas.openxmlformats.org/officeDocument/2006/custom-properties",
      Self::P => "http://schemas.openxmlformats.org/presentationml/2006/main",
      Self::P14 => "http://schemas.microsoft.com/office/powerpoint/2010/main",
      Self::P15 => "http://schemas.microsoft.com/office/powerpoint/2012/main",
      Self::P16 => "http://schemas.microsoft.com/office/powerpoint/2015/main",
      Self::P1710 => "http://schemas.microsoft.com/office/powerpoint/2017/10/main",
      Self::P173 => "http://schemas.microsoft.com/office/powerpoint/2017/3/main",
      Self::P184 => "http://schemas.microsoft.com/office/powerpoint/2018/4/main",
      Self::P188 => "http://schemas.microsoft.com/office/powerpoint/2018/8/main",
      Self::P1912 => "http://schemas.microsoft.com/office/powerpoint/2019/12/main",
      Self::P202 => "http://schemas.microsoft.com/office/powerpoint/2020/02/main",
      Self::P216 => "http://schemas.microsoft.com/office/powerpoint/2021/06/main",
      Self::P223 => "http://schemas.microsoft.com/office/powerpoint/2022/03/main",
      Self::P228 => "http://schemas.microsoft.com/office/powerpoint/2022/08/main",
      Self::P232 => "http://schemas.microsoft.com/office/powerpoint/2023/02/main",
      Self::PRoam => "http://schemas.microsoft.com/office/powerpoint/2012/roamingSettings",
      Self::Packaging => "http://schemas.microsoft.com/office/internal/2007/ofapi/packaging",
      Self::Pav => "http://schemas.microsoft.com/office/2007/6/19/audiovideo",
      Self::Pc => "http://schemas.microsoft.com/office/powerpoint/2013/main/command",
      Self::Pc2 => "http://schemas.microsoft.com/office/powerpoint/2019/9/main/command",
      Self::Pc226 => "http://schemas.microsoft.com/office/powerpoint/2022/06/main/command",
      Self::Pic => "http://schemas.openxmlformats.org/drawingml/2006/picture",
      Self::Pic14 => "http://schemas.microsoft.com/office/drawing/2010/picture",
      Self::Pj15 => "http://schemas.microsoft.com/projectml/2012/main",
      Self::Pvml => "urn:schemas-microsoft-com:office:powerpoint",
      Self::R => "http://schemas.openxmlformats.org/officeDocument/2006/relationships",
      Self::Sl => "http://schemas.openxmlformats.org/schemaLibrary/2006/main",
      Self::Sle => "http://schemas.microsoft.com/office/drawing/2010/slicer",
      Self::T => "http://schemas.microsoft.com/office/tasks/2019/documenttasks",
      Self::Thm15 => "http://schemas.microsoft.com/office/thememl/2012/main",
      Self::Tsle => "http://schemas.microsoft.com/office/drawing/2012/timeslicer",
      Self::V => "urn:schemas-microsoft-com:vml",
      Self::Vt => "http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes",
      Self::W => "http://schemas.openxmlformats.org/wordprocessingml/2006/main",
      Self::W10 => "urn:schemas-microsoft-com:office:word",
      Self::W14 => "http://schemas.microsoft.com/office/word/2010/wordml",
      Self::W15 => "http://schemas.microsoft.com/office/word/2012/wordml",
      Self::W16cex => "http://schemas.microsoft.com/office/word/2018/wordml/cex",
      Self::W16cid => "http://schemas.microsoft.com/office/word/2016/wordml/cid",
      Self::W16cur => "http://schemas.microsoft.com/office/word/2018/wordml",
      Self::W16du => "http://schemas.microsoft.com/office/word/2023/wordml/word16du",
      Self::W16sdtdh => "http://schemas.microsoft.com/office/word/2020/wordml/sdtdatahash",
      Self::W16sdtfl => "http://schemas.microsoft.com/office/word/2024/wordml/sdtformatlock",
      Self::W16se => "http://schemas.microsoft.com/office/word/2015/wordml/symex",
      Self::We => "http://schemas.microsoft.com/office/webextensions/webextension/2010/11",
      Self::Wetp => "http://schemas.microsoft.com/office/webextensions/taskpanes/2010/11",
      Self::Wne => "http://schemas.microsoft.com/office/word/2006/wordml",
      Self::Woe => "http://schemas.microsoft.com/office/word/2020/oembed",
      Self::Wp => "http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing",
      Self::Wp14 => "http://schemas.microsoft.com/office/word/2010/wordprocessingDrawing",
      Self::Wp15 => "http://schemas.microsoft.com/office/word/2012/wordprocessingDrawing",
      Self::Wpc => "http://schemas.microsoft.com/office/word/2010/wordprocessingCanvas",
      Self::Wpg => "http://schemas.microsoft.com/office/word/2010/wordprocessingGroup",
      Self::Wps => "http://schemas.microsoft.com/office/word/2010/wordprocessingShape",
      Self::X => "http://schemas.openxmlformats.org/spreadsheetml/2006/main",
      Self::X12ac => "http://schemas.microsoft.com/office/spreadsheetml/2011/1/ac",
      Self::X14 => "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main",
      Self::X14ac => "http://schemas.microsoft.com/office/spreadsheetml/2009/9/ac",
      Self::X15 => "http://schemas.microsoft.com/office/spreadsheetml/2010/11/main",
      Self::X15ac => "http://schemas.microsoft.com/office/spreadsheetml/2010/11/ac",
      Self::X16 => "http://schemas.microsoft.com/office/spreadsheetml/2014/11/main",
      Self::X16r2 => "http://schemas.microsoft.com/office/spreadsheetml/2015/02/main",
      Self::X16r3 => "http://schemas.microsoft.com/office/spreadsheetml/2018/08/main",
      Self::Xcalcf => "http://schemas.microsoft.com/office/spreadsheetml/2018/calcfeatures",
      Self::Xda => "http://schemas.microsoft.com/office/spreadsheetml/2017/dynamicarray",
      Self::Xdr => "http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing",
      Self::Xdr14 => "http://schemas.microsoft.com/office/excel/2010/spreadsheetDrawing",
      Self::Xfpb => "http://schemas.microsoft.com/office/spreadsheetml/2022/featurepropertybag",
      Self::XlPr => "http://schemas.microsoft.com/office/spreadsheetml/2016/01/main",
      Self::Xlecs => "http://schemas.microsoft.com/office/spreadsheetml/2023/externalCodeService",
      Self::Xlecs2 => "http://schemas.microsoft.com/office/spreadsheetml/2025/externalCodeService2",
      Self::Xlmsforms => "http://schemas.microsoft.com/office/spreadsheetml/2023/msForms",
      Self::Xlpar => "http://schemas.microsoft.com/office/spreadsheetml/2024/pivotAutoRefresh",
      Self::Xlpcalc => {
        "http://schemas.microsoft.com/office/spreadsheetml/2023/pivot2023Calculation"
      }
      Self::Xlpda => "http://schemas.microsoft.com/office/spreadsheetml/2024/pivotDynamicArrays",
      Self::Xlpds => "http://schemas.microsoft.com/office/spreadsheetml/2025/pivotDataSource",
      Self::Xlrd => "http://schemas.microsoft.com/office/spreadsheetml/2017/richdata",
      Self::Xlrd2 => "http://schemas.microsoft.com/office/spreadsheetml/2017/richdata2",
      Self::Xlrdwi => "http://schemas.microsoft.com/office/spreadsheetml/2020/richdatawebimage",
      Self::Xlrvr => "http://schemas.microsoft.com/office/spreadsheetml/2020/richvaluerefresh",
      Self::Xlrvrel => "http://schemas.microsoft.com/office/spreadsheetml/2022/richvaluerel",
      Self::Xltc => "http://schemas.microsoft.com/office/spreadsheetml/2018/threadedcomments",
      Self::Xltc2 => "http://schemas.microsoft.com/office/spreadsheetml/2020/threadedcomments2",
      Self::Xlwcv => {
        "http://schemas.microsoft.com/office/spreadsheetml/2024/workbookCompatibilityVersion"
      }
      Self::Xml => "http://www.w3.org/XML/1998/namespace",
      Self::Xne => "http://schemas.microsoft.com/office/excel/2006/main",
      Self::Xnsv => "http://schemas.microsoft.com/office/spreadsheetml/2019/namedsheetviews",
      Self::Xpdl => "http://schemas.microsoft.com/office/spreadsheetml/2016/pivotdefaultlayout",
      Self::Xprd => "http://schemas.microsoft.com/office/spreadsheetml/2022/pivotRichData",
      Self::Xr => "http://schemas.microsoft.com/office/spreadsheetml/2014/revision",
      Self::Xr10 => "http://schemas.microsoft.com/office/spreadsheetml/2016/revision10",
      Self::Xr16 => "http://schemas.microsoft.com/office/spreadsheetml/2017/revision16",
      Self::Xr2 => "http://schemas.microsoft.com/office/spreadsheetml/2015/revision2",
      Self::Xr3 => "http://schemas.microsoft.com/office/spreadsheetml/2016/revision3",
      Self::Xr5 => "http://schemas.microsoft.com/office/spreadsheetml/2016/revision5",
      Self::Xr6 => "http://schemas.microsoft.com/office/spreadsheetml/2016/revision6",
      Self::Xr9 => "http://schemas.microsoft.com/office/spreadsheetml/2016/revision9",
      Self::Xsd => "http://www.w3.org/2001/XMLSchema",
      Self::Xvml => "urn:schemas-microsoft-com:office:excel",
      Self::Xxdsv => "http://schemas.microsoft.com/office/spreadsheetml/2023/dataSourceVersioning",
      Self::Xxl21 => "http://schemas.microsoft.com/office/spreadsheetml/2021/extlinks2021",
      Self::Xxlnp => "http://schemas.microsoft.com/office/spreadsheetml/2019/extlinksprops",
      Self::Xxpim => "http://schemas.microsoft.com/office/spreadsheetml/2020/pivotNov2020",
      Self::Xxpvi => "http://schemas.microsoft.com/office/spreadsheetml/2022/pivotVersionInfo",
    }
  }
}
#[derive(Clone, Copy, Debug, Default, Eq, Hash, PartialEq)]
pub struct XmlKnownNamespaceDecl {
  pub namespace: XmlKnownNamespace,
  pub flags: u8,
}
impl XmlKnownNamespaceDecl {
  pub const DEFAULT_NAMESPACE: u8 = 1;
  #[inline]
  pub const fn new(namespace: XmlKnownNamespace) -> Self {
    Self {
      namespace,
      flags: 0,
    }
  }
  #[inline]
  pub const fn new_default(namespace: XmlKnownNamespace) -> Self {
    Self {
      namespace,
      flags: Self::DEFAULT_NAMESPACE,
    }
  }
  #[inline]
  pub const fn is_default(self) -> bool {
    self.flags & Self::DEFAULT_NAMESPACE != 0
  }
}
pub(crate) fn prefix_by_uri(uri: &str) -> Option<&'static str> {
  match uri {
    "http://schemas.openxmlformats.org/drawingml/2006/main" => Some("a"),
    "http://schemas.microsoft.com/office/drawing/2010/main" => Some("a14"),
    "http://schemas.microsoft.com/office/drawing/2012/main" => Some("a15"),
    "http://schemas.microsoft.com/office/drawing/2014/main" => Some("a16"),
    "http://schemas.microsoft.com/office/drawing/2016/11/main" => Some("a1611"),
    "http://schemas.microsoft.com/office/drawing/2018/animation/model3d" => Some("a3danim"),
    "http://schemas.microsoft.com/office/drawing/2018/animation" => Some("aanim"),
    "http://schemas.openxmlformats.org/officeDocument/2006/characteristics" => Some("ac"),
    "http://schemas.microsoft.com/office/drawing/2020/classificationShape" => Some("aclsh"),
    "http://schemas.microsoft.com/office/drawing/2017/decorative" => Some("adec"),
    "http://schemas.microsoft.com/office/drawing/2018/hyperlinkcolor" => Some("ahyp"),
    "http://schemas.microsoft.com/office/drawing/2022/imageformula" => Some("aif"),
    "http://schemas.microsoft.com/office/drawing/2016/ink" => Some("aink"),
    "http://schemas.microsoft.com/office/drawing/2021/livefeed" => Some("alf"),
    "http://schemas.microsoft.com/office/drawing/2017/model3d" => Some("am3d"),
    "http://schemas.microsoft.com/office/drawing/2021/oembed" => Some("aoe"),
    "http://schemas.openxmlformats.org/officeDocument/2006/extended-properties" => Some("ap"),
    "http://schemas.microsoft.com/office/drawing/2018/sketchyshapes" => Some("ask"),
    "http://schemas.microsoft.com/office/drawing/2021/scriptlink" => Some("asl"),
    "http://schemas.microsoft.com/office/drawing/2016/SVG/main" => Some("asvg"),
    "http://schemas.microsoft.com/office/2006/activeX" => Some("ax"),
    "http://schemas.openxmlformats.org/officeDocument/2006/bibliography" => Some("b"),
    "http://schemas.openxmlformats.org/drawingml/2006/chart" => Some("c"),
    "http://schemas.microsoft.com/office/drawing/2007/8/2/chart" => Some("c14"),
    "http://schemas.microsoft.com/office/drawing/2012/chart" => Some("c15"),
    "http://schemas.microsoft.com/office/drawing/2014/chart" => Some("c16"),
    "http://schemas.microsoft.com/office/drawing/2014/chart/ac" => Some("c16ac"),
    "http://schemas.microsoft.com/office/drawing/2017/03/chart" => Some("c16r3"),
    "http://schemas.microsoft.com/office/2006/customDocumentInformationPanel" => Some("cdip"),
    "http://schemas.openxmlformats.org/drawingml/2006/chartDrawing" => Some("cdr"),
    "http://schemas.microsoft.com/office/drawing/2010/chartDrawing" => Some("cdr14"),
    "http://schemas.microsoft.com/office/2020/mipLabelMetadata" => Some("clbl"),
    "http://schemas.microsoft.com/office/drawing/2010/compatibility" => Some("com14"),
    "http://schemas.openxmlformats.org/drawingml/2006/compatibility" => Some("comp"),
    "http://schemas.openxmlformats.org/package/2006/metadata/core-properties" => Some("cp"),
    "http://schemas.microsoft.com/office/2006/coverPageProps" => Some("cppr"),
    "http://schemas.microsoft.com/office/comments/2020/reactions" => Some("cr"),
    "http://schemas.microsoft.com/office/drawing/2012/chartStyle" => Some("cs"),
    "http://schemas.microsoft.com/office/2006/metadata/contentType" => Some("ct"),
    "http://schemas.microsoft.com/office/drawing/2014/chartex" => Some("cx"),
    "http://purl.org/dc/elements/1.1/" => Some("dc"),
    "http://purl.org/dc/terms/" => Some("dcterms"),
    "http://schemas.openxmlformats.org/drawingml/2006/diagram" => Some("dgm"),
    "http://schemas.microsoft.com/office/drawing/2010/diagram" => Some("dgm14"),
    "http://schemas.microsoft.com/office/drawing/2016/11/diagram" => Some("dgm1611"),
    "http://schemas.microsoft.com/office/drawing/2016/12/diagram" => Some("dgm1612"),
    "http://schemas.openxmlformats.org/officeDocument/2006/customXml" => Some("ds"),
    "http://schemas.microsoft.com/office/drawing/2008/diagram" => Some("dsp"),
    "http://www.w3.org/2003/04/emma" => Some("emma"),
    "http://www.w3.org/2003/InkML" => Some("inkml"),
    "http://schemas.openxmlformats.org/drawingml/2006/lockedCanvas" => Some("lc"),
    "http://schemas.microsoft.com/office/2006/metadata/longProperties" => Some("lp"),
    "http://schemas.openxmlformats.org/officeDocument/2006/math" => Some("m"),
    "http://schemas.microsoft.com/office/2006/metadata/properties/metaAttributes" => Some("ma"),
    "http://schemas.openxmlformats.org/markup-compatibility/2006" => Some("mc"),
    "http://schemas.microsoft.com/office/office/2011/9/metroDictionary" => Some("md"),
    "http://schemas.microsoft.com/ink/2010/main" => Some("msink"),
    "http://schemas.microsoft.com/office/2006/01/customui" => Some("mso"),
    "http://schemas.microsoft.com/office/2009/07/customui" => Some("mso14"),
    "http://schemas.microsoft.com/office/2006/metadata/customXsn" => Some("ntns"),
    "urn:schemas-microsoft-com:office:office" => Some("o"),
    "http://schemas.microsoft.com/office/drawing/2013/main/command" => Some("oac"),
    "http://schemas.microsoft.com/office/2019/extlst" => Some("oel"),
    "http://schemas.openxmlformats.org/officeDocument/2006/custom-properties" => Some("op"),
    "http://schemas.openxmlformats.org/presentationml/2006/main" => Some("p"),
    "http://schemas.microsoft.com/office/powerpoint/2010/main" => Some("p14"),
    "http://schemas.microsoft.com/office/powerpoint/2012/main" => Some("p15"),
    "http://schemas.microsoft.com/office/powerpoint/2015/main" => Some("p16"),
    "http://schemas.microsoft.com/office/powerpoint/2017/10/main" => Some("p1710"),
    "http://schemas.microsoft.com/office/powerpoint/2017/3/main" => Some("p173"),
    "http://schemas.microsoft.com/office/powerpoint/2018/4/main" => Some("p184"),
    "http://schemas.microsoft.com/office/powerpoint/2018/8/main" => Some("p188"),
    "http://schemas.microsoft.com/office/powerpoint/2019/12/main" => Some("p1912"),
    "http://schemas.microsoft.com/office/powerpoint/2020/02/main" => Some("p202"),
    "http://schemas.microsoft.com/office/powerpoint/2021/06/main" => Some("p216"),
    "http://schemas.microsoft.com/office/powerpoint/2022/03/main" => Some("p223"),
    "http://schemas.microsoft.com/office/powerpoint/2022/08/main" => Some("p228"),
    "http://schemas.microsoft.com/office/powerpoint/2023/02/main" => Some("p232"),
    "http://schemas.microsoft.com/office/powerpoint/2012/roamingSettings" => Some("pRoam"),
    "http://schemas.microsoft.com/office/internal/2007/ofapi/packaging" => Some("packaging"),
    "http://schemas.microsoft.com/office/2007/6/19/audiovideo" => Some("pav"),
    "http://schemas.microsoft.com/office/powerpoint/2013/main/command" => Some("pc"),
    "http://schemas.microsoft.com/office/powerpoint/2019/9/main/command" => Some("pc2"),
    "http://schemas.microsoft.com/office/powerpoint/2022/06/main/command" => Some("pc226"),
    "http://schemas.openxmlformats.org/drawingml/2006/picture" => Some("pic"),
    "http://schemas.microsoft.com/office/drawing/2010/picture" => Some("pic14"),
    "http://schemas.microsoft.com/projectml/2012/main" => Some("pj15"),
    "urn:schemas-microsoft-com:office:powerpoint" => Some("pvml"),
    "http://schemas.openxmlformats.org/officeDocument/2006/relationships" => Some("r"),
    "http://schemas.openxmlformats.org/schemaLibrary/2006/main" => Some("sl"),
    "http://schemas.microsoft.com/office/drawing/2010/slicer" => Some("sle"),
    "http://schemas.microsoft.com/office/tasks/2019/documenttasks" => Some("t"),
    "http://schemas.microsoft.com/office/thememl/2012/main" => Some("thm15"),
    "http://schemas.microsoft.com/office/drawing/2012/timeslicer" => Some("tsle"),
    "urn:schemas-microsoft-com:vml" => Some("v"),
    "http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes" => Some("vt"),
    "http://schemas.openxmlformats.org/wordprocessingml/2006/main" => Some("w"),
    "urn:schemas-microsoft-com:office:word" => Some("w10"),
    "http://schemas.microsoft.com/office/word/2010/wordml" => Some("w14"),
    "http://schemas.microsoft.com/office/word/2012/wordml" => Some("w15"),
    "http://schemas.microsoft.com/office/word/2018/wordml/cex" => Some("w16cex"),
    "http://schemas.microsoft.com/office/word/2016/wordml/cid" => Some("w16cid"),
    "http://schemas.microsoft.com/office/word/2018/wordml" => Some("w16cur"),
    "http://schemas.microsoft.com/office/word/2023/wordml/word16du" => Some("w16du"),
    "http://schemas.microsoft.com/office/word/2020/wordml/sdtdatahash" => Some("w16sdtdh"),
    "http://schemas.microsoft.com/office/word/2024/wordml/sdtformatlock" => Some("w16sdtfl"),
    "http://schemas.microsoft.com/office/word/2015/wordml/symex" => Some("w16se"),
    "http://schemas.microsoft.com/office/webextensions/webextension/2010/11" => Some("we"),
    "http://schemas.microsoft.com/office/webextensions/taskpanes/2010/11" => Some("wetp"),
    "http://schemas.microsoft.com/office/word/2006/wordml" => Some("wne"),
    "http://schemas.microsoft.com/office/word/2020/oembed" => Some("woe"),
    "http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing" => Some("wp"),
    "http://schemas.microsoft.com/office/word/2010/wordprocessingDrawing" => Some("wp14"),
    "http://schemas.microsoft.com/office/word/2012/wordprocessingDrawing" => Some("wp15"),
    "http://schemas.microsoft.com/office/word/2010/wordprocessingCanvas" => Some("wpc"),
    "http://schemas.microsoft.com/office/word/2010/wordprocessingGroup" => Some("wpg"),
    "http://schemas.microsoft.com/office/word/2010/wordprocessingShape" => Some("wps"),
    "http://schemas.openxmlformats.org/spreadsheetml/2006/main" => Some("x"),
    "http://schemas.microsoft.com/office/spreadsheetml/2011/1/ac" => Some("x12ac"),
    "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main" => Some("x14"),
    "http://schemas.microsoft.com/office/spreadsheetml/2009/9/ac" => Some("x14ac"),
    "http://schemas.microsoft.com/office/spreadsheetml/2010/11/main" => Some("x15"),
    "http://schemas.microsoft.com/office/spreadsheetml/2010/11/ac" => Some("x15ac"),
    "http://schemas.microsoft.com/office/spreadsheetml/2014/11/main" => Some("x16"),
    "http://schemas.microsoft.com/office/spreadsheetml/2015/02/main" => Some("x16r2"),
    "http://schemas.microsoft.com/office/spreadsheetml/2018/08/main" => Some("x16r3"),
    "http://schemas.microsoft.com/office/spreadsheetml/2018/calcfeatures" => Some("xcalcf"),
    "http://schemas.microsoft.com/office/spreadsheetml/2017/dynamicarray" => Some("xda"),
    "http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing" => Some("xdr"),
    "http://schemas.microsoft.com/office/excel/2010/spreadsheetDrawing" => Some("xdr14"),
    "http://schemas.microsoft.com/office/spreadsheetml/2022/featurepropertybag" => Some("xfpb"),
    "http://schemas.microsoft.com/office/spreadsheetml/2016/01/main" => Some("xlPr"),
    "http://schemas.microsoft.com/office/spreadsheetml/2023/externalCodeService" => Some("xlecs"),
    "http://schemas.microsoft.com/office/spreadsheetml/2025/externalCodeService2" => Some("xlecs2"),
    "http://schemas.microsoft.com/office/spreadsheetml/2023/msForms" => Some("xlmsforms"),
    "http://schemas.microsoft.com/office/spreadsheetml/2024/pivotAutoRefresh" => Some("xlpar"),
    "http://schemas.microsoft.com/office/spreadsheetml/2023/pivot2023Calculation" => {
      Some("xlpcalc")
    }
    "http://schemas.microsoft.com/office/spreadsheetml/2024/pivotDynamicArrays" => Some("xlpda"),
    "http://schemas.microsoft.com/office/spreadsheetml/2025/pivotDataSource" => Some("xlpds"),
    "http://schemas.microsoft.com/office/spreadsheetml/2017/richdata" => Some("xlrd"),
    "http://schemas.microsoft.com/office/spreadsheetml/2017/richdata2" => Some("xlrd2"),
    "http://schemas.microsoft.com/office/spreadsheetml/2020/richdatawebimage" => Some("xlrdwi"),
    "http://schemas.microsoft.com/office/spreadsheetml/2020/richvaluerefresh" => Some("xlrvr"),
    "http://schemas.microsoft.com/office/spreadsheetml/2022/richvaluerel" => Some("xlrvrel"),
    "http://schemas.microsoft.com/office/spreadsheetml/2018/threadedcomments" => Some("xltc"),
    "http://schemas.microsoft.com/office/spreadsheetml/2020/threadedcomments2" => Some("xltc2"),
    "http://schemas.microsoft.com/office/spreadsheetml/2024/workbookCompatibilityVersion" => {
      Some("xlwcv")
    }
    "http://www.w3.org/XML/1998/namespace" => Some("xml"),
    "http://schemas.microsoft.com/office/excel/2006/main" => Some("xne"),
    "http://schemas.microsoft.com/office/spreadsheetml/2019/namedsheetviews" => Some("xnsv"),
    "http://schemas.microsoft.com/office/spreadsheetml/2016/pivotdefaultlayout" => Some("xpdl"),
    "http://schemas.microsoft.com/office/spreadsheetml/2022/pivotRichData" => Some("xprd"),
    "http://schemas.microsoft.com/office/spreadsheetml/2014/revision" => Some("xr"),
    "http://schemas.microsoft.com/office/spreadsheetml/2016/revision10" => Some("xr10"),
    "http://schemas.microsoft.com/office/spreadsheetml/2017/revision16" => Some("xr16"),
    "http://schemas.microsoft.com/office/spreadsheetml/2015/revision2" => Some("xr2"),
    "http://schemas.microsoft.com/office/spreadsheetml/2016/revision3" => Some("xr3"),
    "http://schemas.microsoft.com/office/spreadsheetml/2016/revision5" => Some("xr5"),
    "http://schemas.microsoft.com/office/spreadsheetml/2016/revision6" => Some("xr6"),
    "http://schemas.microsoft.com/office/spreadsheetml/2016/revision9" => Some("xr9"),
    "http://www.w3.org/2001/XMLSchema" => Some("xsd"),
    "urn:schemas-microsoft-com:office:excel" => Some("xvml"),
    "http://schemas.microsoft.com/office/spreadsheetml/2023/dataSourceVersioning" => Some("xxdsv"),
    "http://schemas.microsoft.com/office/spreadsheetml/2021/extlinks2021" => Some("xxl21"),
    "http://schemas.microsoft.com/office/spreadsheetml/2019/extlinksprops" => Some("xxlnp"),
    "http://schemas.microsoft.com/office/spreadsheetml/2020/pivotNov2020" => Some("xxpim"),
    "http://schemas.microsoft.com/office/spreadsheetml/2022/pivotVersionInfo" => Some("xxpvi"),
    _ => None,
  }
}
